# PMM Dynamic Screener — MEXC Public REST

This notebook screens **MEXC** markets for **PMM Dynamic (Predictive Market Making)** using only public market-data endpoints. It is a **pre-ingestion gate**: the output is a ranked shortlist plus a candle-ingestor manifest, selected `BASE-QUOTE` pairs, and rule-estimate metadata.

This notebook is **public-data only**. It uses unauthenticated MEXC spot market endpoints and does not require or send any account credentials.

Stop-ship stance: a pair passing this notebook is **fit for research and ingestion only** until it survives candle-quality checks, walk-forward validation, and live microstructure review.

In [1]:
import os
import sys
import subprocess
import logging
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from IPython.display import display, Markdown

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 160)
pd.set_option("display.max_colwidth", 120)

CANDIDATE_DIRS = [
    Path("/quants-lab/research_notebooks/market_lab/pmm_dynamic"),
    Path.cwd(),
    Path.cwd().parent,
    Path.cwd().parent.parent,
]
PMM_DIR = next((p.resolve() for p in CANDIDATE_DIRS if (p / "pyproject.toml").exists() and (p / "pmm_lab").exists()), None)
if PMM_DIR is None:
    raise FileNotFoundError("Could not locate the pmm_dynamic project root. Open this notebook from inside the pmm_dynamic repo.")

if str(PMM_DIR) not in sys.path:
    sys.path.insert(0, str(PMM_DIR))
subprocess.check_call(
    [sys.executable, "-m", "pip", "install", "-e", str(PMM_DIR), "--quiet"],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL,
)

logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("pmm_lab").setLevel(logging.WARNING)

print(f"PMM project root: {PMM_DIR}")


from pmm_lab.screener import MEXCPublicScreener, default_mexc_config, export_screening_artifacts
from pmm_lab.screener.common import compute_coarse_scores, select_shortlist
from pmm_lab.screener.mexc_public import MEXC_BASE_URL

PMM project root: /quants-lab/research_notebooks/market_lab/pmm_dynamic

## 1. Configuration

Edit the universe, thresholds, and output path here. Keep the defaults conservative unless you explicitly want a wider exploratory net.

In [2]:
# ============================================================
# USER CONFIG — edit these, then Run All
# ============================================================
QUOTE_ASSET = "*"
INTERVAL = "1m"
UNIVERSE_TOP_K = 100
FINAL_TOP_N = 30
CANDLE_LIMIT = 288
DEPTH_LIMIT = 200
RECENT_TRADE_LIMIT = 500

# Optional pair overrides.
# Keep INCLUDE_SYMBOLS empty to use the full eligible universe.
INCLUDE_SYMBOLS = []
EXCLUDE_SYMBOLS = []

OUTPUT_ROOT = (
    PMM_DIR / "artifacts" / "screener" / "mexc" /
    datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
)

cfg = default_mexc_config()
cfg.quote_asset = QUOTE_ASSET
cfg.interval = INTERVAL
cfg.universe_top_k = UNIVERSE_TOP_K
cfg.final_top_n = FINAL_TOP_N
cfg.candle_limit = CANDLE_LIMIT
cfg.depth_limit = DEPTH_LIMIT
cfg.recent_trade_limit = RECENT_TRADE_LIMIT
cfg.include_symbols = tuple(INCLUDE_SYMBOLS)
cfg.exclude_symbols = tuple(EXCLUDE_SYMBOLS)

# Conservative defaults. Loosen only if you explicitly want more exploratory coverage.
cfg.min_quote_volume_24h = 1000000.0
cfg.max_spread_bps = 50.0
cfg.min_top_of_book_quote = 250.0
cfg.min_depth_10bps_quote = 1000.0
cfg.max_last_trade_age_sec = 1800.0
cfg.min_recent_trade_count = 100
cfg.min_candle_count = 240
cfg.min_candle_coverage_ratio = 0.97
cfg.max_zero_volume_fraction = 0.2
cfg.min_natr_bps = 10.0
cfg.max_natr_bps = 250.0

print("Screener config")
display(pd.Series(cfg.as_dict()).to_frame("value"))
print(f"Output root: {OUTPUT_ROOT}")

Screener config

                                                                                                                                         value
connector                                                                                                                                 mexc
quote_asset                                                                                                                                  *
interval                                                                                                                                    1m
universe_top_k                                                                                                                             100
final_top_n                                                                                                                                 30
candle_limit                                                                                                                               288
depth_limit                                                                                                                                200
recent_trade_limit                                                                                                                         500
request_pause_sec                                                                                                                         0.12
timeout_seconds                                                                                                                           30.0
max_retries                                                                                                                                  3
retry_backoff                                                                                                                              1.8
user_agent                                                                                                                pmm-lab-screener/0.1
min_quote_volume_24h                                                                                                                 1000000.0
max_spread_bps                                                                                                                            50.0
min_top_of_book_quote                                                                                                                    250.0
min_depth_10bps_quote                                                                                                                   1000.0
min_depth_50bps_quote                                                                                                                      0.0
min_depth_1xspread_quote                                                                                                                   0.0
max_last_trade_age_sec                                                                                                                  1800.0
min_recent_trade_count                                                                                                                     100
min_candle_count                                                                                                                           240
min_candle_coverage_ratio                                                                                                                 0.97
max_zero_volume_fraction                                                                                                                   0.2
min_natr_bps                                                                                                                              10.0
max_natr_bps                                                                                                                             250.0
natr_soft_min                                                                                                                              6.0
natr_target_min                                                                                                                           15.0
natr_target_max                                                                                                                          120.0
natr_soft_max                                                                                                                            250.0
efficiency_soft_min                                                                                                                        0.0
efficiency_target_min                                                                                                                     0.05
efficiency_target_max                                                                                                                      0.4
efficiency_soft_max                                                                                                                       0.75
vol_to_spread_soft_min                                                                                                                     1.0
vol_to_spread_target_min                                                                                                                   3.0
vol_to_spread_target_max                                                                                                                  20.0
vol_to_spread_soft_max                                                                                                                    50.0
exclude_regex                                                                             ((?:^|[^A-Z])(3L|3S|5L|5S)$, (?:UP|DOWN|BULL|BEAR)$)
include_symbols                                                                                                                             ()
exclude_symbols                                                                                                                             ()
score_weights              {'volume': 0.24, 'depth': 0.2, 'spread': 0.16, 'top_of_book': 0.08, 'activity': 0.12, 'quality': 0.1, 'alpha': 0.1}
selection_mode                                                                                                                          strict
fallback_if_empty                                                                                                                        False
interval_seconds                                                                                                                            60

Output root: /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511

## 2. Build the cheap universe snapshot

This step uses only batch endpoints to discover the broad market universe and assign a coarse score before any per-pair enrichment calls are made.

In [3]:
screener = MEXCPublicScreener(cfg)

universe = screener.build_universe()
universe = compute_coarse_scores(universe)
shortlist = select_shortlist(universe, cfg)

summary = pd.DataFrame([
    {
        "connector": cfg.connector,
        "quote_asset": cfg.quote_asset,
        "interval": cfg.interval,
        "universe_rows": len(universe),
        "shortlist_rows": len(shortlist),
    }
])
display(summary)

preview_cols = [
    c for c in [
        "trading_pair",
        "exchange_symbol",
        "quote_volume_24h",
        "spread_bps",
        "coarse_score",
        "price_tick_estimate",
        "amount_step_estimate",
        "status_detail",
    ]
    if c in universe.columns
]

display(universe.loc[:, preview_cols].head(20))
print(f"Shortlist for detailed enrichment: {len(shortlist)}")
display(shortlist.loc[:, preview_cols].head(min(25, len(shortlist))))

  connector quote_asset interval  universe_rows  shortlist_rows
0      mexc           *       1m           2413             100

       trading_pair exchange_symbol  quote_volume_24h  spread_bps  coarse_score  price_tick_estimate  amount_step_estimate status_detail
0          ETH-USDT         ETHUSDT      4.834973e+08    0.046106     99.877663              0.01000              0.000100             1
1          BTC-USDT         BTCUSDT      8.284443e+08    0.001402     99.873496              0.01000              0.000001             1
2         USDC-USDT        USDCUSDT      2.388074e+07    0.999850     99.577109              0.00010              1.000000             1
3   GOLD(PAXG)-USDT  GOLD(PAXG)USDT      1.546512e+07    0.022220     99.467272              0.01000              0.000001             1
4   GOLD(XAUT)-USDT  GOLD(XAUT)USDT      5.386325e+07    0.222521     99.301195              0.10000              0.001000             1
5         USD1-USDT        USD1USDT      9.560159e+06    1.000350     99.257929              0.00010              0.000000             1
6          BNB-USDT         BNBUSDT      2.314509e+07    0.154406     99.234946              0.01000              0.001000             1
7          XRP-USDT         XRPUSDT      6.856743e+07    1.413927     99.118680              0.00010              0.100000             1
8         DOGE-USDT        DOGEUSDT      3.161097e+07    1.040096     98.946628              0.00001              1.000000             1
9         USDE-USDT        USDEUSDT      4.150448e+06    1.000250     98.786530              0.00010              0.000000             1
10         EUR-USDT         EURUSDT      3.056805e+06    0.864790     98.589762              0.00010              0.000000             1
11         LTC-USDT         LTCUSDT      9.200621e+06    1.765693     98.573622              0.01000              0.001000             1
12         ADA-USDT         ADAUSDT      1.356976e+07    3.696174     98.179443              0.00010              0.100000             1
13        LINK-USDT        LINKUSDT      1.589637e+07    2.133106     98.164889              0.00100              0.010000             1
14         TRX-USDT         TRXUSDT      6.882673e+06    3.174099     98.150675              0.00010              1.000000             1
15        XUSD-USDT        XUSDUSDT      1.727486e+06    0.999450     97.909001              0.00010              0.000000             1
16         UNI-USDT         UNIUSDT      6.106769e+06    2.699420     97.903984              0.00100              0.001000             1
17         WLD-USDT         WLDUSDT      4.334214e+06    3.079292     97.665588              0.00010              0.000000             1
18       ETHFI-USDT       ETHFIUSDT      3.551667e+06    1.784599     97.358813              0.00010              0.000000             1
19         BTC-USDC         BTCUSDC      1.745556e+07    1.146929     97.349855              0.01000              0.000001             1

Shortlist for detailed enrichment: 100

       trading_pair exchange_symbol  quote_volume_24h  spread_bps  coarse_score  price_tick_estimate  amount_step_estimate status_detail
0          ETH-USDT         ETHUSDT      4.834973e+08    0.046106     99.877663              0.01000              0.000100             1
1          BTC-USDT         BTCUSDT      8.284443e+08    0.001402     99.873496              0.01000              0.000001             1
2         USDC-USDT        USDCUSDT      2.388074e+07    0.999850     99.577109              0.00010              1.000000             1
3   GOLD(PAXG)-USDT  GOLD(PAXG)USDT      1.546512e+07    0.022220     99.467272              0.01000              0.000001             1
4   GOLD(XAUT)-USDT  GOLD(XAUT)USDT      5.386325e+07    0.222521     99.301195              0.10000              0.001000             1
5         USD1-USDT        USD1USDT      9.560159e+06    1.000350     99.257929              0.00010              0.000000             1
6          BNB-USDT         BNBUSDT      2.314509e+07    0.154406     99.234946              0.01000              0.001000             1
7          XRP-USDT         XRPUSDT      6.856743e+07    1.413927     99.118680              0.00010              0.100000             1
8         DOGE-USDT        DOGEUSDT      3.161097e+07    1.040096     98.946628              0.00001              1.000000             1
9         USDE-USDT        USDEUSDT      4.150448e+06    1.000250     98.786530              0.00010              0.000000             1
10         EUR-USDT         EURUSDT      3.056805e+06    0.864790     98.589762              0.00010              0.000000             1
11         LTC-USDT         LTCUSDT      9.200621e+06    1.765693     98.573622              0.01000              0.001000             1
12         ADA-USDT         ADAUSDT      1.356976e+07    3.696174     98.179443              0.00010              0.100000             1
13        LINK-USDT        LINKUSDT      1.589637e+07    2.133106     98.164889              0.00100              0.010000             1
14         TRX-USDT         TRXUSDT      6.882673e+06    3.174099     98.150675              0.00010              1.000000             1
15        XUSD-USDT        XUSDUSDT      1.727486e+06    0.999450     97.909001              0.00010              0.000000             1
16         UNI-USDT         UNIUSDT      6.106769e+06    2.699420     97.903984              0.00100              0.001000             1
17         WLD-USDT         WLDUSDT      4.334214e+06    3.079292     97.665588              0.00010              0.000000             1
18       ETHFI-USDT       ETHFIUSDT      3.551667e+06    1.784599     97.358813              0.00010              0.000000             1
19         BTC-USDC         BTCUSDC      1.745556e+07    1.146929     97.349855              0.01000              0.000001             1
20         XLM-USDT         XLMUSDT      7.458928e+06    5.635390     97.215321              0.00010              0.100000             1
21       TRUMP-USDT       TRUMPUSDT      3.809494e+06    3.044603     97.136818              0.00100              0.000000             1
22         FET-USDT         FETUSDT      3.612312e+06    3.854307     97.026962              0.00010              0.001000             1
23        AAVE-USDT        AAVEUSDT      6.416675e+06    0.888455     96.993535              0.01000              0.000100             1
24         ZEC-USDT         ZECUSDT      1.028996e+07    0.432386     96.926908              0.01000              0.001000             1

## 3. Run the detailed screener

This step enriches the shortlist with order-book depth, recent trades, and candles, then applies hard gates plus the final PMM-oriented score.

In [4]:
run = screener.screen_from_universe(universe)
final_df = run.final.copy()
selected_df = run.selected.copy()

status_counts = pd.DataFrame([
    {
        "enriched_rows": len(final_df),
        "selected_rows": len(selected_df),
        "pass_rate": float(selected_df.shape[0] / final_df.shape[0]) if len(final_df) else 0.0,
    }
])
display(status_counts)

final_cols = [
    c for c in [
        "trading_pair",
        "screen_score",
        "passed_filters",
        "quote_volume_24h",
        "spread_bps",
        "top_of_book_quote",
        "sym_depth_quote_10bps",
        "recent_trade_count",
        "last_trade_age_sec",
        "n_candles",
        "coverage_ratio",
        "zero_volume_fraction",
        "natr_bps_mean",
        "efficiency_ratio",
        "rejection_reason",
    ]
    if c in final_df.columns
]
display(final_df.loc[:, final_cols].head(min(50, len(final_df))))

   enriched_rows  selected_rows  pass_rate
0            100             11       0.11

,trading_pair,screen_score,passed_filters,quote_volume_24h,spread_bps,top_of_book_quote,sym_depth_quote_10bps,recent_trade_count,last_trade_age_sec,n_candles,coverage_ratio,zero_volume_fraction,natr_bps_mean,efficiency_ratio,rejection_reason
0,WLD-USDT,75.208706,True,4.334214e+06,3.078344,1.262509e+03,1.452405e+04,500,11.957346,288,1.0,0.003472,13.067693,0.071533,
1,XLM-USDT,67.632176,True,7.458928e+06,5.635390,2.285632e+03,1.446896e+04,500,11.257934,288,1.0,0.003472,11.830729,0.000000,
2,DOT-USDT,66.410158,True,5.942912e+06,7.334067,4.136623e+03,4.136623e+03,500,4.005268,288,1.0,0.000000,14.545894,0.031142,
3,PEPE-USDT,64.085056,True,9.875603e+06,5.654509,4.255117e+02,4.497284e+03,500,24.104647,288,1.0,0.013889,10.269020,0.003425,
4,PUMP-USDT,63.123755,True,2.728063e+06,5.247966,7.840261e+02,9.037849e+03,500,19.034189,288,1.0,0.000000,15.277548,0.011628,
5,FET-USDT,62.265920,True,3.612312e+06,3.851338,6.210154e+02,2.910057e+03,500,5.803531,288,1.0,0.000000,31.307601,0.002674,
6,JST-USDT,54.755353,True,1.357469e+06,1.669867,3.311364e+02,1.499475e+03,500,16.589831,288,1.0,0.006944,10.384628,0.078845,
7,RENDER-USDT,51.765408,True,1.096228e+06,5.377790,7.053976e+02,7.327346e+03,500,8.734355,288,1.0,0.000000,12.912593,0.040650,
8,CRV-USDT,49.752072,True,1.118541e+06,4.256225,3.561272e+02,1.317887e+03,500,47.511124,288,1.0,0.000000,11.150053,0.033557,
9,OP-USDT,47.048008,True,1.185640e+06,8.814456,4.611672e+03,4.611672e+03,500,25.804487,288,1.0,0.038194,13.497043,0.008547,
10,ETC-USDT,46.710419,True,1.781712e+06,11.527378,2.933850e+03,2.933850e+03,500,61.642644,288,1.0,0.052083,14.233673,0.000000,
11,BTC-USDT,89.807333,False,8.284443e+08,0.001402,3.704000e+03,3.968469e+05,500,2.475616,288,1.0,0.000000,4.918111,0.061919,natr_bps_mean<10
12,XRP-USDT,88.235575,False,6.856743e+07,0.706939,8.506697e+02,4.958269e+05,500,3.342901,288,1.0,0.000000,6.078119,0.013640,natr_bps_mean<10
13,SUI-USDT,84.665315,False,1.271243e+07,1.032258,7.950854e+03,1.293357e+05,500,7.637360,288,1.0,0.000000,7.982055,0.035608,natr_bps_mean<10
14,TAO-USDT,84.213227,False,4.190591e+07,1.157039,3.664738e+01,3.673540e+04,500,1.063677,288,1.0,0.000000,28.022283,0.085912,top_of_book_quote<250
15,ETH-USDT,84.127849,False,4.834973e+08,0.046106,2.582339e+04,1.723962e+05,500,1.436906,288,1.0,0.000000,5.905857,0.008548,natr_bps_mean<10
16,USDC-USDT,82.530006,False,2.388074e+07,0.999850,3.333745e+06,1.280132e+07,500,28.289637,288,1.0,0.000000,0.999854,0.000000,natr_bps_mean<10
17,LTC-USDT,81.939973,False,9.200621e+06,1.765381,2.111459e+03,6.686821e+04,500,6.407820,288,1.0,0.000000,6.214127,0.056466,natr_bps_mean<10
18,SOL-USDT,81.324875,False,9.698271e+07,1.090334,1.348284e+01,9.897537e+05,500,3.972389,288,1.0,0.000000,7.510984,0.003509,top_of_book_quote<250; natr_bps_mean<10
19,BTC-USDC,81.290667,False,1.745556e+07,1.651731,2.706070e+02,1.501013e+05,500,5.504644,288,1.0,0.000000,5.404698,0.066084,natr_bps_mean<10
20,USD1-USDT,80.862400,False,9.560159e+06,1.000350,3.376553e+05,8.528423e+06,500,9.796901,288,1.0,0.000000,1.003822,0.007194,natr_bps_mean<10
21,BNB-USDT,80.546560,False,2.314509e+07,0.154406,7.017827e+02,7.299073e+04,500,14.570574,288,1.0,0.000000,3.929719,0.022723,natr_bps_mean<10
22,GOLD(PAXG)-USDT,80.288462,False,1.546512e+07,0.022220,1.972578e+03,9.657521e+04,500,15.129881,288,1.0,0.000000,6.599769,0.036695,natr_bps_mean<10
23,GOLD(XAUT)-USDT,79.264446,False,5.386325e+07,0.222526,1.038091e+01,1.911273e+05,500,18.013146,288,1.0,0.000000,6.581643,0.033777,top_of_book_quote<250; natr_bps_mean<10
24,DOGE-USDT,79.199078,False,3.161097e+07,1.039879,1.784915e+01,2.513574e+05,500,4.107522,288,1.0,0.000000,6.494805,0.007042,top_of_book_quote<250; natr_bps_mean<10
25,ADA-USDT,78.105901,False,1.356976e+07,3.696174,1.660722e+04,1.080268e+05,500,7.178397,288,1.0,0.000000,9.107701,0.007481,natr_bps_mean<10
26,LINK-USDT,77.474135,False,1.589637e+07,2.133333,3.346294e+02,6.634835e+04,500,27.940183,288,1.0,0.017361,6.615319,0.036705,natr_bps_mean<10
27,TRX-USDT,77.000873,False,6.882673e+06,3.174099,2.992332e+04,1.353919e+05,500,8.709630,288,1.0,0.000000,5.177547,0.033613,natr_bps_mean<10
28,USDE-USDT,70.094881,False,4.150448e+06,1.000250,2.858197e+05,2.165761e+06,500,40.878147,288,1.0,0.003472,0.989892,0.005348,natr_bps_mean<10
29,UNI-USDT,69.576632,False,6.106769e+06,2.698691,8.231769e+02,2.060755e+04,500,33.201737,288,1.0,0.003472,7.896326,0.015209,natr_bps_mean<10
30,HYPE-USDT,69.240343,False,1.214829e+07,2.483547,2.347741e+02,3.902838e+03,500,45.216108,288,1.0,0.003472,10.713369,0.031724,top_of_book_quote<250
31,ZEC-USDT,68.866728,False,1.028996e+07,1.296709,1.299205e+02,3.487333e+03,500,20.471907,288,1.0,0.000000,11.049165,0.071372,top_of_book_quote<250
32,AAVE-USDT,68.695000,False,6.416675e+06,0.888376,8.566577e+01,6.063202e+03,500,14.633528,288,1.0,0.003472,8.316796,0.004608,top_of_book_quote<250; natr_bps_mean<10
33,LTC-USDC,67.962484,False,1.564295e+06,1.764758,2.436380e+01,4.219381e+02,500,4.369627,288,1.0,0.000000,6.301905,0.063063,top_of_book_quote<250; depth_10bps<1000; natr_bps_mean<10
34,HBAR-USDT,66.929567,False,2.954170e+06,1.056133,3.307332e+02,7.968104e+03,500,16.260701,288,1.0,0.003472,5.858407,0.004558,natr_bps_mean<10
35,AVAX-USDT,66.289356,False,8.604068e+06,2.066970,3.618450e+01,3.869533e+04,500,52.366378,288,1.0,0.020833,6.005597,0.001698,top_of_book_quote<250; natr_bps_mean<10
36,TRUMP-USDT,65.495976,False,3.809494e+06,3.044603,1.787040e+02,2.232640e+04,500,33.041673,288,1.0,0.017361,8.896383,0.007380,top_of_book_quote<250; natr_bps_mean<10
37,TAO-USDC,64.490203,False,8.656659e+06,10.416968,2.904468e+02,5.844278e+02,500,2.863790,288,1.0,0.000000,28.077084,0.083026,depth_10bps<1000
38,EUR-USDT,63.764327,False,3.056805e+06,0.864715,1.266998e+03,2.019870e+05,500,146.655260,288,1.0,0.006944,0.981870,0.006897,natr_bps_mean<10
39,ETHFI-USDT,63.036231,False,3.551667e+06,1.784599,4.038754e+02,5.357368e+02,500,20.738514,288,1.0,0.000000,11.355073,0.016733,depth_10bps<1000
40,SAHARA-USDT,61.352000,False,2.415628e+07,3.670398,1.181560e+01,1.079428e+03,500,21.332576,288,1.0,0.000000,18.408205,0.065662,top_of_book_quote<250
41,WXT-USDT,59.701235,False,3.306938e+06,1.863152,3.264021e+02,9.841515e+03,500,17.143318,288,1.0,0.000000,4.480888,0.002183,natr_bps_mean<10
42,BNB-USDC,58.087116,False,1.215865e+06,0.154453,3.884640e+01,1.424390e+02,500,18.002708,288,1.0,0.000000,3.981318,0.022195,top_of_book_quote<250; depth_10bps<1000; natr_bps_mean<10
43,WBTC-USDT,57.601333,False,1.156334e+06,0.001405,1.356058e+02,1.807033e+04,500,4.883522,288,1.0,0.000000,4.110251,0.062502,top_of_book_quote<250; natr_bps_mean<10
44,ZRO-USDT,56.814974,False,9.889748e+05,4.658747,2.045447e+02,2.535285e+03,500,21.139197,288,1.0,0.000000,12.130590,0.062222,quote_volume_24h<1e+06; top_of_book_quote<250
45,FIL-USDT,56.050117,False,2.542897e+06,3.234327,1.728676e+01,3.461110e+03,500,10.418893,288,1.0,0.031250,7.104346,0.007942,top_of_book_quote<250; natr_bps_mean<10
46,ETH-USDC,55.822174,False,2.066179e+06,2.904357,2.286621e+01,4.460920e+04,500,9.431154,288,1.0,0.010417,4.517167,0.016433,top_of_book_quote<250; natr_bps_mean<10
47,SHIB-USDT,55.759548,False,2.115624e+06,4.893565,6.975245e+02,2.507329e+03,500,5.577317,288,1.0,0.031250,6.611591,0.023018,natr_bps_mean<10
48,FDUSD-USDT,55.583401,False,3.403717e+05,1.000250,2.819552e+05,4.978108e+06,500,34.999472,288,1.0,0.000000,1.000245,0.010101,quote_volume_24h<1e+06; natr_bps_mean<10
49,DAI-USDT,54.930441,False,1.453359e+06,1.000150,3.271673e+01,1.359866e+04,500,6.034047,288,1.0,0.048611,1.020913,0.017544,top_of_book_quote<250; natr_bps_mean<10

## 4. Diagnostics

Inspect which pairs passed, which pairs failed, and why. Rejection counts are often more useful than raw rankings because they show whether you are liquidity-bound, spread-bound, or data-quality-bound.

In [5]:
if final_df.empty:
    print("No enriched rows returned.")
else:
    passed = final_df[final_df["passed_filters"]].copy()
    rejected = final_df[~final_df["passed_filters"]].copy()

    print(f"Passed: {{len(passed)}} | Rejected: {{len(rejected)}}")

    if not passed.empty:
        display(
            passed.loc[:, [
                c for c in [
                    "trading_pair",
                    "screen_score",
                    "quote_volume_24h",
                    "spread_bps",
                    "top_of_book_quote",
                    "sym_depth_quote_10bps",
                    "recent_trade_count",
                    "last_trade_age_sec",
                    "natr_bps_mean",
                    "efficiency_ratio",
                ] if c in passed.columns
            ]].head(cfg.final_top_n)
        )

    if not rejected.empty:
        reject_counts = (
            rejected["rejection_reason"]
            .fillna("")
            .str.split("; ")
            .explode()
            .loc[lambda s: s.ne("")]
            .value_counts()
            .rename_axis("rejection_reason")
            .to_frame("count")
        )
        display(reject_counts.head(20))

Passed: {len(passed)} | Rejected: {len(rejected)}

,trading_pair,screen_score,quote_volume_24h,spread_bps,top_of_book_quote,sym_depth_quote_10bps,recent_trade_count,last_trade_age_sec,natr_bps_mean,efficiency_ratio
0,WLD-USDT,75.208706,4.334214e+06,3.078344,1262.509416,14524.045701,500,11.957346,13.067693,0.071533
1,XLM-USDT,67.632176,7.458928e+06,5.635390,2285.632000,14468.960032,500,11.257934,11.830729,0.000000
2,DOT-USDT,66.410158,5.942912e+06,7.334067,4136.623220,4136.623220,500,4.005268,14.545894,0.031142
3,PEPE-USDT,64.085056,9.875603e+06,5.654509,425.511722,4497.283789,500,24.104647,10.269020,0.003425
4,PUMP-USDT,63.123755,2.728063e+06,5.247966,784.026067,9037.848564,500,19.034189,15.277548,0.011628
5,FET-USDT,62.265920,3.612312e+06,3.851338,621.015416,2910.056840,500,5.803531,31.307601,0.002674
6,JST-USDT,54.755353,1.357469e+06,1.669867,331.136400,1499.474993,500,16.589831,10.384628,0.078845
7,RENDER-USDT,51.765408,1.096228e+06,5.377790,705.397550,7327.346490,500,8.734355,12.912593,0.040650
8,CRV-USDT,49.752072,1.118541e+06,4.256225,356.127192,1317.886776,500,47.511124,11.150053,0.033557
9,OP-USDT,47.048008,1.185640e+06,8.814456,4611.671845,4611.671845,500,25.804487,13.497043,0.008547
10,ETC-USDT,46.710419,1.781712e+06,11.527378,2933.849970,2933.849970,500,61.642644,14.233673,0.000000

                           count
rejection_reason
natr_bps_mean<10              58
top_of_book_quote<250         51
quote_volume_24h<1e+06        34
depth_10bps<1000              33
zero_volume_fraction>0.20      3

## 5. Export artifacts

This writes CSV, JSON, a Markdown report, a candle-ingestor manifest, and an exchange-rules patch for the selected pairs.

In [6]:
artifact_paths = export_screening_artifacts(
    run,
    output_dir=str(OUTPUT_ROOT),
    base_url=MEXC_BASE_URL,
    trade_limit=cfg.recent_trade_limit,
)

print("Artifacts written")
display(pd.Series(asdict(artifact_paths)).to_frame("path"))

Artifacts written

                                                                                                                                                  path
root_dir                                                 /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511
universe_csv                                /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/universe.csv
shortlist_csv                              /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/shortlist.csv
final_csv                               /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/final_screen.csv
selected_csv                          /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/selected_pairs.csv
selected_pairs_txt                    /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/selected_pairs.txt
selected_pairs_json                  /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/selected_pairs.json
symbol_metadata_json                /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/symbol_metadata.json
candle_ingestor_manifest_yaml  /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/candle_ingestor_manife...
exchange_rules_patch_yaml      /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/exchange_rules_patch.yaml
screening_report_md                  /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/screening_report.md
run_metadata_json                      /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260325_235511/run_metadata.json

## 6. Merge into candle ingestion

The manifest below follows the same `exchanges -> pairs -> intervals` structure already used by your candle-ingest and candle-gap-repair tooling, with slash-formatted exchange pairs and Hummingbot-normalized selected pair files alongside it.

In [7]:
from pathlib import Path

print("Selected Hummingbot pairs")
print("-" * 80)
print(Path(artifact_paths.selected_pairs_txt).read_text())

print("\nCandle ingestor manifest")
print("-" * 80)
print(Path(artifact_paths.candle_ingestor_manifest_yaml).read_text())

print("\nExchange rules patch (estimates only)")
print("-" * 80)
print(Path(artifact_paths.exchange_rules_patch_yaml).read_text())

Selected Hummingbot pairs
--------------------------------------------------------------------------------
WLD-USDT
XLM-USDT
DOT-USDT
PEPE-USDT
PUMP-USDT
FET-USDT
JST-USDT
RENDER-USDT
CRV-USDT
OP-USDT
ETC-USDT


Candle ingestor manifest
--------------------------------------------------------------------------------
backfill_days: 180
request_delay: 0.5
overlap_candles: 2
include_open_candle: false
http:
  timeout_seconds: 30.0
  max_retries: 3
  retry_backoff: 1.8
  user_agent: pmm-lab-screener/0.1
exchanges:
  mexc:
    enabled: true
    base_url: https://api.mexc.com
    pairs:
    - WLD/USDT
    - XLM/USDT
    - DOT/USDT
    - PEPE/USDT
    - PUMP/USDT
    - FET/USDT
    - JST/USDT
    - RENDER/USDT
    - CRV/USDT
    - OP/USDT
    - ETC/USDT
    intervals:
    - 1m
    trades:
      enabled: true
      limit: 500
      update_recent_candles: false
      recent_window_minutes: 120


Exchange rules patch (estimates only)
--------------------------------------------------------------------------------
connectors:
  mexc:
    pairs:
      WLD-USDT:
        price_tick: 0.0001
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      XLM-USDT:
        price_tick: 0.0001
        amount_step: 0.1
        min_notional_quote: 1.0
        min_order_size_base: 0.1
      DOT-USDT:
        price_tick: 0.001
        amount_step: 0.001
        min_notional_quote: 1.0
        min_order_size_base: 0.001
      PEPE-USDT:
        price_tick: 1.0e-09
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      PUMP-USDT:
        price_tick: 1.0e-06
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      FET-USDT:
        price_tick: 0.0001
        amount_step: 0.001
        min_notional_quote: 1.0
        min_order_size_base: 0.001
      JST-USDT:
        price_tick: 1.0e-05
        amount_step: 1.0
        min_notional_quote: 1.0
        min_order_size_base: 1.0
      RENDER-USDT:
        price_tick: 0.001
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      CRV-USDT:
        price_tick: 0.0001
        amount_step: 0.01
        min_notional_quote: 1.0
        min_order_size_base: 0.01
      OP-USDT:
        price_tick: 0.0001
        amount_step: 0.01
        min_notional_quote: 1.0
        min_order_size_base: 0.01
      ETC-USDT:
        price_tick: 0.01
        amount_step: 0.1
        min_notional_quote: 1.0
        min_order_size_base: 0.1