# PMM Dynamic Screener — NonKYC Public REST

This notebook screens **NONKYC** markets for **PMM Dynamic (Predictive Market Making)** using only public market-data endpoints. It is a **pre-ingestion gate**: the output is a ranked shortlist plus a candle-ingestor manifest, selected `BASE-QUOTE` pairs, and rule-estimate metadata.

By default this notebook screens **all quote assets** available on NonKYC (USDT, XMR, BTC, USDC, etc.). To restrict to a single quote, set `QUOTE_ASSET` to e.g. `'USDT'`. To screen a specific set, use comma-separated values like `'USDT,XMR'`. The notebook uses the documented public REST endpoints for markets, tickers, order books, candles, and trades.

Stop-ship stance: a pair passing this notebook is **fit for research and ingestion only** until it survives candle-quality checks, walk-forward validation, and live microstructure review.

In [1]:
import os
import sys
import subprocess
import logging
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from IPython.display import display, Markdown

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 160)
pd.set_option("display.max_colwidth", 120)

CANDIDATE_DIRS = [
    Path("/quants-lab/research_notebooks/market_lab/pmm_dynamic"),
    Path.cwd(),
    Path.cwd().parent,
    Path.cwd().parent.parent,
]
PMM_DIR = next((p.resolve() for p in CANDIDATE_DIRS if (p / "pyproject.toml").exists() and (p / "pmm_lab").exists()), None)
if PMM_DIR is None:
    raise FileNotFoundError("Could not locate the pmm_dynamic project root. Open this notebook from inside the pmm_dynamic repo.")

if str(PMM_DIR) not in sys.path:
    sys.path.insert(0, str(PMM_DIR))
subprocess.check_call(
    [sys.executable, "-m", "pip", "install", "-e", str(PMM_DIR), "--quiet"],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL,
)

logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("pmm_lab").setLevel(logging.WARNING)

print(f"PMM project root: {PMM_DIR}")


from pmm_lab.screener import NonKYCPublicScreener, default_nonkyc_config, export_screening_artifacts
from pmm_lab.screener.common import compute_coarse_scores, select_shortlist
from pmm_lab.screener.nonkyc_public import NONKYC_BASE_URL

PMM project root: /quants-lab/research_notebooks/market_lab/pmm_dynamic

## 1. Configuration

Edit the universe, thresholds, and output path here. Keep the defaults conservative unless you explicitly want a wider exploratory net.

In [2]:
# ============================================================
# USER CONFIG — edit these, then Run All
# ============================================================
QUOTE_ASSET = "*"
INTERVAL = "5m"
UNIVERSE_TOP_K = 80
FINAL_TOP_N = 15
CANDLE_LIMIT = 288
DEPTH_LIMIT = 200
RECENT_TRADE_LIMIT = 500

# Optional pair overrides.
# Keep INCLUDE_SYMBOLS empty to use the full eligible universe.
INCLUDE_SYMBOLS = []
EXCLUDE_SYMBOLS = []

OUTPUT_ROOT = (
    PMM_DIR / "artifacts" / "screener" / "nonkyc" /
    datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
)

cfg = default_nonkyc_config()
cfg.quote_asset = QUOTE_ASSET
cfg.interval = INTERVAL
cfg.universe_top_k = UNIVERSE_TOP_K
cfg.final_top_n = FINAL_TOP_N
cfg.candle_limit = CANDLE_LIMIT
cfg.depth_limit = DEPTH_LIMIT
cfg.recent_trade_limit = RECENT_TRADE_LIMIT
cfg.include_symbols = tuple(INCLUDE_SYMBOLS)
cfg.exclude_symbols = tuple(EXCLUDE_SYMBOLS)

# Conservative defaults. Loosen only if you explicitly want more exploratory coverage.
cfg.min_quote_volume_24h = 50000.0
cfg.max_spread_bps = 120.0
cfg.min_top_of_book_quote = 5.0
cfg.min_depth_10bps_quote = 0.0
cfg.max_last_trade_age_sec = 3600.0
cfg.min_recent_trade_count = 40
cfg.min_candle_count = 220
cfg.min_candle_coverage_ratio = 0.9
cfg.max_zero_volume_fraction = 0.3
cfg.min_natr_bps = 12.0
cfg.max_natr_bps = 400.0

print("Screener config")
display(pd.Series(cfg.as_dict()).to_frame("value"))
print(f"Output root: {OUTPUT_ROOT}")

Screener config

                                                                                                                                         value
connector                                                                                                                               nonkyc
quote_asset                                                                                                                                  *
interval                                                                                                                                    5m
universe_top_k                                                                                                                              80
final_top_n                                                                                                                                 15
candle_limit                                                                                                                               288
depth_limit                                                                                                                                200
recent_trade_limit                                                                                                                         500
request_pause_sec                                                                                                                          0.2
timeout_seconds                                                                                                                           30.0
max_retries                                                                                                                                  3
retry_backoff                                                                                                                              1.8
user_agent                                                                                                                pmm-lab-screener/0.1
min_quote_volume_24h                                                                                                                   50000.0
max_spread_bps                                                                                                                           120.0
min_top_of_book_quote                                                                                                                      5.0
min_depth_10bps_quote                                                                                                                      0.0
min_depth_50bps_quote                                                                                                                      0.0
min_depth_1xspread_quote                                                                                                                   0.0
max_last_trade_age_sec                                                                                                                  3600.0
min_recent_trade_count                                                                                                                      40
min_candle_count                                                                                                                           220
min_candle_coverage_ratio                                                                                                                  0.9
max_zero_volume_fraction                                                                                                                   0.3
min_natr_bps                                                                                                                              12.0
max_natr_bps                                                                                                                             400.0
natr_soft_min                                                                                                                              8.0
natr_target_min                                                                                                                           20.0
natr_target_max                                                                                                                          180.0
natr_soft_max                                                                                                                            350.0
efficiency_soft_min                                                                                                                        0.0
efficiency_target_min                                                                                                                     0.05
efficiency_target_max                                                                                                                     0.45
efficiency_soft_max                                                                                                                        0.8
vol_to_spread_soft_min                                                                                                                     1.0
vol_to_spread_target_min                                                                                                                   3.0
vol_to_spread_target_max                                                                                                                  25.0
vol_to_spread_soft_max                                                                                                                    60.0
exclude_regex                                                                             ((?:^|[^A-Z])(3L|3S|5L|5S)$, (?:UP|DOWN|BULL|BEAR)$)
include_symbols                                                                                                                             ()
exclude_symbols                                                                                                                             ()
score_weights              {'volume': 0.24, 'depth': 0.2, 'spread': 0.16, 'top_of_book': 0.08, 'activity': 0.12, 'quality': 0.1, 'alpha': 0.1}
selection_mode                                                                                                                          strict
fallback_if_empty                                                                                                                         True
interval_seconds                                                                                                                           300

Output root: /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054

## 2. Build the cheap universe snapshot

This step uses only batch endpoints to discover the broad market universe and assign a coarse score before any per-pair enrichment calls are made.

In [3]:
screener = NonKYCPublicScreener(cfg)

universe = screener.build_universe()
universe = compute_coarse_scores(universe)
shortlist = select_shortlist(universe, cfg)

summary = pd.DataFrame([
    {
        "connector": cfg.connector,
        "quote_asset": cfg.quote_asset,
        "interval": cfg.interval,
        "universe_rows": len(universe),
        "shortlist_rows": len(shortlist),
    }
])
display(summary)

preview_cols = [
    c for c in [
        "trading_pair",
        "exchange_symbol",
        "quote_volume_24h",
        "spread_bps",
        "coarse_score",
        "price_tick_estimate",
        "amount_step_estimate",
        "status_detail",
    ]
    if c in universe.columns
]

display(universe.loc[:, preview_cols].head(20))
print(f"Shortlist for detailed enrichment: {len(shortlist)}")
display(shortlist.loc[:, preview_cols].head(min(25, len(shortlist))))

  connector quote_asset interval  universe_rows  shortlist_rows
0    nonkyc           *       5m            345              80

   trading_pair exchange_symbol  quote_volume_24h  spread_bps  coarse_score  price_tick_estimate  amount_step_estimate status_detail
0     NKYC-USDT       NKYC/USDT      1.685141e+05   10.514318     76.545639         1.000000e-06              0.000100        active
1      SUN-USDT        SUN/USDT      1.458112e+05   11.180055     76.080600         1.000000e-06              0.010000        active
2     ARRR-USDT       ARRR/USDT      2.814920e+05   24.737313     75.708111         1.000000e-06              0.000100        active
3      LTC-USDT        LTC/USDT      8.153326e+05   40.848948     75.435164         1.000000e-02              0.000100        active
4      XRP-USDT        XRP/USDT      2.103925e+06   54.607993     75.075896         1.000000e-04              0.010000        active
5      BTC-USDC        BTC/USDC      7.075347e+05   43.311014     74.983346         1.000000e-02              0.000001        active
6     USDC-USDT       USDC/USDT      1.683752e+06   51.994801     74.816934         1.000000e-04              0.010000        active
7      SOL-USDT        SOL/USDT      2.026641e+06   61.208875     74.404780         1.000000e-02              0.010000        active
8     LINK-USDT       LINK/USDT      1.074873e+06   53.734551     74.351894         1.000000e-02              0.010000        active
9      ETH-USDT        ETH/USDT      7.457523e+06   65.660003     73.627129         1.000000e-02              0.000010        active
10     TRX-USDT        TRX/USDT      2.715005e+05   50.793651     73.209509         1.000000e-04              0.010000        active
11     BTC-USDT        BTC/USDT      1.284782e+07   73.723910     72.982456         1.000000e-02              0.000001        active
12     BC2-USDT        BC2/USDT      8.185530e+04   33.851524     72.658912         1.000000e-06              0.000100        active
13     PEP-USDT        PEP/USDT      4.606293e+04    8.837826     72.387490         1.000000e-08              0.000100        active
14    SHIB-USDT       SHIB/USDT      2.198089e+05   63.720284     71.880498         1.000000e-09              1.000000        active
15     SEI-USDT        SEI/USDT      1.036175e+05   49.140049     71.748284         1.000000e-04              0.010000        active
16    DOGE-USDT       DOGE/USDT      3.351607e+05   66.805846     71.494788         1.000000e-05              0.010000        active
17    PEPE-USDT       PEPE/USDT      1.196857e+05   56.657224     71.276252         1.000000e-08              1.000000        active
18     XLM-USDT        XLM/USDT      3.170935e+05   67.643743     71.262268         1.000000e-04              0.010000        active
19     OPN-USDT        OPN/USDT      4.561696e+04   22.920009     70.985380         1.000000e-04              0.010000        active

Shortlist for detailed enrichment: 80

   trading_pair exchange_symbol  quote_volume_24h  spread_bps  coarse_score  price_tick_estimate  amount_step_estimate status_detail
0     NKYC-USDT       NKYC/USDT      1.685141e+05   10.514318     76.545639         1.000000e-06              0.000100        active
1      SUN-USDT        SUN/USDT      1.458112e+05   11.180055     76.080600         1.000000e-06              0.010000        active
2     ARRR-USDT       ARRR/USDT      2.814920e+05   24.737313     75.708111         1.000000e-06              0.000100        active
3      LTC-USDT        LTC/USDT      8.153326e+05   40.848948     75.435164         1.000000e-02              0.000100        active
4      XRP-USDT        XRP/USDT      2.103925e+06   54.607993     75.075896         1.000000e-04              0.010000        active
5      BTC-USDC        BTC/USDC      7.075347e+05   43.311014     74.983346         1.000000e-02              0.000001        active
6     USDC-USDT       USDC/USDT      1.683752e+06   51.994801     74.816934         1.000000e-04              0.010000        active
7      SOL-USDT        SOL/USDT      2.026641e+06   61.208875     74.404780         1.000000e-02              0.010000        active
8     LINK-USDT       LINK/USDT      1.074873e+06   53.734551     74.351894         1.000000e-02              0.010000        active
9      ETH-USDT        ETH/USDT      7.457523e+06   65.660003     73.627129         1.000000e-02              0.000010        active
10     TRX-USDT        TRX/USDT      2.715005e+05   50.793651     73.209509         1.000000e-04              0.010000        active
11     BTC-USDT        BTC/USDT      1.284782e+07   73.723910     72.982456         1.000000e-02              0.000001        active
12     BC2-USDT        BC2/USDT      8.185530e+04   33.851524     72.658912         1.000000e-06              0.000100        active
13     PEP-USDT        PEP/USDT      4.606293e+04    8.837826     72.387490         1.000000e-08              0.000100        active
14    SHIB-USDT       SHIB/USDT      2.198089e+05   63.720284     71.880498         1.000000e-09              1.000000        active
15     SEI-USDT        SEI/USDT      1.036175e+05   49.140049     71.748284         1.000000e-04              0.010000        active
16    DOGE-USDT       DOGE/USDT      3.351607e+05   66.805846     71.494788         1.000000e-05              0.010000        active
17    PEPE-USDT       PEPE/USDT      1.196857e+05   56.657224     71.276252         1.000000e-08              1.000000        active
18     XLM-USDT        XLM/USDT      3.170935e+05   67.643743     71.262268         1.000000e-04              0.010000        active
19     OPN-USDT        OPN/USDT      4.561696e+04   22.920009     70.985380         1.000000e-04              0.010000        active
20     UNI-USDT        UNI/USDT      3.632007e+05   78.346616     70.644038         1.000000e-03              0.010000        active
21     BCH-USDT        BCH/USDT      1.328396e+05   65.352588     70.571701         1.000000e-01              0.000010        active
22      FF-USDT         FF/USDT      1.113272e+05   64.183061     70.299517         1.000000e-05              0.010000        active
23    ALGO-USDT       ALGO/USDT      5.755412e+04   45.766590     69.895118         1.000000e-04              0.010000        active
24    AVAX-USDT       AVAX/USDT      5.110441e+05   82.730093     69.853166         1.000000e-02              0.010000        active

## 3. Run the detailed screener

This step enriches the shortlist with order-book depth, recent trades, and candles, then applies hard gates plus the final PMM-oriented score.

In [4]:
run = screener.screen_from_universe(universe)
final_df = run.final.copy()
selected_df = run.selected.copy()

status_counts = pd.DataFrame([
    {
        "enriched_rows": len(final_df),
        "selected_rows": len(selected_df),
        "pass_rate": float(selected_df.shape[0] / final_df.shape[0]) if len(final_df) else 0.0,
    }
])
display(status_counts)

final_cols = [
    c for c in [
        "trading_pair",
        "screen_score",
        "passed_filters",
        "quote_volume_24h",
        "spread_bps",
        "top_of_book_quote",
        "sym_depth_quote_10bps",
        "recent_trade_count",
        "last_trade_age_sec",
        "n_candles",
        "coverage_ratio",
        "zero_volume_fraction",
        "natr_bps_mean",
        "efficiency_ratio",
        "rejection_reason",
    ]
    if c in final_df.columns
]
display(final_df.loc[:, final_cols].head(min(50, len(final_df))))

GET https://api.nonkyc.io/api/v2/market/orderbook?symbol=MANA%2FUSDT&limit=200 failed on attempt 1/3: HTTP Error 502: Bad Gateway
GET https://api.nonkyc.io/api/v2/market/orderbook?symbol=MORPHO%2FUSDT&limit=200 failed on attempt 1/3: HTTP Error 502: Bad Gateway
GET https://api.nonkyc.io/api/v2/market/trades?symbol=DIVI%2FUSDT&limit=500 failed on attempt 1/3: HTTP Error 502: Bad Gateway
GET https://api.nonkyc.io/api/v2/market/orderbook?symbol=EIGEN%2FUSDT&limit=200 failed on attempt 1/3: HTTP Error 502: Bad Gateway
GET https://api.nonkyc.io/api/v2/market/orderbook?symbol=ERG%2FUSDT&limit=200 failed on attempt 1/3: HTTP Error 502: Bad Gateway
GET https://api.nonkyc.io/api/v2/market/trades?symbol=ERG%2FUSDT&limit=500 failed on attempt 1/3: HTTP Error 502: Bad Gateway

   enriched_rows  selected_rows  pass_rate
0             80             10      0.125

,trading_pair,screen_score,passed_filters,quote_volume_24h,spread_bps,top_of_book_quote,sym_depth_quote_10bps,recent_trade_count,last_trade_age_sec,n_candles,coverage_ratio,zero_volume_fraction,natr_bps_mean,efficiency_ratio,rejection_reason
0,USDC-USDT,82.172668,True,1.683752e+06,51.994801,472.973590,0.000000,200,0.459929,288,1.000000,0.000000,15.033446,0.001821,
1,SOL-USDT,78.261385,True,2.026641e+06,61.208875,1596.798000,0.000000,200,7.193323,288,1.000000,0.000000,27.132022,0.027983,
2,UNI-USDT,74.166667,True,3.632007e+05,78.346616,2204.442680,0.000000,200,21.495398,288,1.000000,0.000000,26.936767,0.063014,
3,LTC-USDT,72.022096,True,8.153326e+05,40.848948,28.238210,0.000000,200,9.173946,288,1.000000,0.000000,22.615545,0.004969,
4,AVAX-USDT,71.221316,True,5.110441e+05,82.730093,258.771500,0.000000,200,12.886237,288,0.989691,0.000000,23.203397,0.031008,
5,AAVE-USDT,70.953422,True,1.001274e+05,65.736875,369.313800,0.000000,200,2.164241,288,1.000000,0.000000,26.030989,0.016089,
6,RENDER-USDT,69.469167,True,1.126968e+05,75.471698,887.040000,0.000000,200,12.215571,288,1.000000,0.000000,40.651349,0.086482,
7,NKYC-USDT,69.279822,True,1.685141e+05,10.514318,36.864207,36.864207,200,28.938642,288,1.000000,0.000000,13.821795,0.004851,
8,PEPE-USDT,67.895280,True,1.196857e+05,56.657224,119.553022,0.000000,200,18.749890,288,0.911392,0.000000,13.046437,0.063291,
9,BCH-USDT,64.723030,True,1.328396e+05,65.352588,5.664144,0.000000,200,8.646626,288,1.000000,0.003472,27.252494,0.012567,
10,BTC-USDT,79.093854,False,1.284782e+07,73.723910,3.217500,0.000000,200,3.033112,288,1.000000,0.000000,23.026281,0.030908,top_of_book_quote<5
11,XRP-USDT,77.034620,False,2.103925e+06,54.607993,1.498734,0.000000,200,10.744948,288,1.000000,0.000000,28.790893,0.002194,top_of_book_quote<5
12,DOGE-USDT,75.951324,False,3.351607e+05,1.040312,0.200912,0.200912,200,7.304196,288,1.000000,0.000000,36.285507,0.027346,top_of_book_quote<5
13,TRX-USDT,75.827694,False,2.715005e+05,50.793651,0.164216,0.000000,200,17.103238,288,0.979592,0.000000,18.130779,0.162887,top_of_book_quote<5
14,ETH-USDT,74.690975,False,7.457523e+06,65.660003,0.086404,0.000000,200,6.217140,288,1.000000,0.000000,27.873987,0.016202,top_of_book_quote<5
15,BTC-USDC,72.041481,False,7.075347e+05,39.509216,0.641345,0.000000,200,1.076237,288,1.000000,0.000000,26.621565,0.037547,top_of_book_quote<5
16,SHIB-USDT,71.737397,False,2.198089e+05,63.720284,0.177417,0.000000,200,18.925029,288,1.000000,0.000000,28.626894,0.037523,top_of_book_quote<5
17,BNB-USDT,69.671667,False,1.397475e+06,105.111836,0.643530,0.000000,200,18.724731,288,1.000000,0.000000,28.977628,0.067142,top_of_book_quote<5
18,PEP-USDT,68.043469,False,4.606293e+04,8.837826,1.605368,1.605368,200,10.004188,288,0.996540,0.000000,86.183303,0.054669,quote_volume_24h<50000; top_of_book_quote<5
19,ALGO-USDT,66.303509,False,5.755412e+04,57.175529,0.173528,0.000000,200,1.147918,288,0.979592,0.000000,20.179339,0.009524,top_of_book_quote<5
20,LINK-USDT,66.229685,False,1.074873e+06,53.734551,0.653100,0.000000,200,5.312110,288,0.926045,0.000000,24.357700,0.045872,top_of_book_quote<5
21,ONDO-USDT,65.509167,False,1.576964e+05,84.073215,0.175798,0.000000,200,24.446572,288,1.000000,0.000000,38.638475,0.094369,top_of_book_quote<5
22,ARRR-USDT,64.899761,False,2.814920e+05,24.737313,0.288427,0.000000,200,25.929386,288,0.986301,0.000000,67.645723,0.050428,top_of_book_quote<5
23,POL-USDT,63.221076,False,6.285804e+04,40.774720,0.165144,0.000000,200,7.814135,288,0.976271,0.000000,18.523706,0.083333,top_of_book_quote<5
24,XMR-USDT,63.134601,False,2.008527e+06,114.484159,1.366920,0.000000,200,5.394732,288,1.000000,0.000000,36.547886,0.009544,top_of_book_quote<5
25,BC2-USDT,63.059925,False,8.185530e+04,33.851524,2.273254,0.000000,200,35.020967,288,1.000000,0.000000,89.034874,0.009257,top_of_book_quote<5
26,XLM-USDT,62.757233,False,3.170935e+05,67.643743,0.153080,0.000000,200,16.278543,288,0.993103,0.000000,29.743422,0.039890,top_of_book_quote<5
27,UNI-USDC,62.156667,False,7.591287e+04,97.218472,0.184250,0.000000,200,2.151900,288,1.000000,0.000000,31.940950,0.066910,top_of_book_quote<5
28,BDX-USDT,61.941941,False,2.328758e+04,22.856037,9.217982,0.000000,200,0.554903,288,0.993103,0.000000,17.032322,0.029376,quote_volume_24h<50000
29,W-USDT,60.794859,False,1.281130e+05,89.739755,0.182042,0.000000,200,19.985226,288,1.000000,0.000000,32.735499,0.013035,top_of_book_quote<5
30,SUN-USDT,60.784459,False,1.458112e+05,11.180055,0.173784,0.173784,200,8.514714,288,0.993103,0.000000,32.897657,0.002985,top_of_book_quote<5
31,ZEC-USDT,59.457340,False,7.640207e+04,78.326734,0.785078,0.000000,200,4.633817,288,0.923077,0.020833,36.373106,0.057404,top_of_book_quote<5
32,ARB-USDT,58.951717,False,6.542137e+04,70.957932,0.201515,0.000000,200,1.428913,288,0.989691,0.000000,25.828617,0.027864,top_of_book_quote<5
33,OPN-USDT,58.474790,False,4.561696e+04,18.331806,0.428064,0.428064,200,20.230302,288,0.996540,0.000000,51.104759,0.022063,quote_volume_24h<50000; top_of_book_quote<5
34,ETC-USDT,57.125833,False,4.915039e+04,69.204152,0.181440,0.000000,200,9.561596,288,1.000000,0.000000,22.021212,0.000000,quote_volume_24h<50000; top_of_book_quote<5
35,POL-USDC,57.069167,False,1.764812e+04,61.162080,0.167280,0.000000,200,5.674955,288,1.000000,0.000000,24.470023,0.071651,quote_volume_24h<50000; top_of_book_quote<5
36,SHIB-USDC,56.980127,False,2.148110e+04,84.988377,0.177889,0.000000,200,16.048397,288,1.000000,0.000000,31.814361,0.044802,quote_volume_24h<50000; top_of_book_quote<5
37,MANA-USDT,56.818346,False,7.267353e+04,83.323950,0.170334,0.000000,200,23.183730,288,1.000000,0.000000,40.013890,0.010538,top_of_book_quote<5
38,BCH2-USDT,56.480000,False,1.385512e+04,34.011792,1.105713,0.000000,200,18.547096,288,1.000000,0.000000,152.833533,0.057373,quote_volume_24h<50000; top_of_book_quote<5
39,SCASH-USDT,55.673838,False,1.128749e+04,14.284085,77.998844,77.998844,200,199.998365,288,1.000000,0.000000,27.318909,0.008582,quote_volume_24h<50000
40,INJ-USDT,54.567622,False,5.986064e+04,64.935065,0.061400,0.000000,200,611.535671,288,0.941176,0.000000,14.022145,0.050847,top_of_book_quote<5
41,FUSD-USDT,54.142163,False,4.777253e+03,1.001352,480.406588,1591.259531,200,496.508088,288,0.721805,0.000000,2.700397,0.011877,quote_volume_24h<50000; coverage_ratio<0.90; natr_bps_mean<12
42,IMX-USDT,53.494561,False,2.180034e+04,65.789474,0.158600,0.000000,200,19.525947,288,1.000000,0.000000,26.062081,0.036093,quote_volume_24h<50000; top_of_book_quote<5
43,ZEPH-USDT,53.403504,False,1.097406e+04,12.502192,0.255341,0.255341,200,23.486513,288,1.000000,0.000000,43.999497,0.046003,quote_volume_24h<50000; top_of_book_quote<5
44,EIGEN-USDT,53.381214,False,3.937631e+04,85.277151,0.168168,0.000000,200,13.768142,288,0.956811,0.000000,29.551499,0.031169,quote_volume_24h<50000; top_of_book_quote<5
45,CAT-USDT,52.252731,False,1.640145e+04,3.691709,0.201330,0.201330,200,13.017019,288,0.996540,0.000000,12.392343,0.078402,quote_volume_24h<50000; top_of_book_quote<5
46,S-USDT,51.205789,False,2.127633e+04,45.871560,10.000215,0.000000,200,9.287302,288,0.886154,0.000000,17.793590,0.006623,quote_volume_24h<50000; coverage_ratio<0.90
47,SEI-USDT,51.076221,False,1.036175e+05,49.140049,0.159732,0.000000,200,8.537791,288,1.000000,0.000000,21.690980,0.023256,top_of_book_quote<5
48,BONK-USDT,49.914638,False,1.172170e+04,64.412238,0.179275,0.000000,200,14.286304,288,0.976271,0.000000,19.639974,0.012552,quote_volume_24h<50000; top_of_book_quote<5
49,PEP-DOGE,49.574966,False,4.188273e+04,85.003348,1.188133,0.000000,200,9.344800,288,0.989691,0.000000,76.437941,0.070571,quote_volume_24h<50000; top_of_book_quote<5

## 4. Diagnostics

Inspect which pairs passed, which pairs failed, and why. Rejection counts are often more useful than raw rankings because they show whether you are liquidity-bound, spread-bound, or data-quality-bound.

In [5]:
if final_df.empty:
    print("No enriched rows returned.")
else:
    passed = final_df[final_df["passed_filters"]].copy()
    rejected = final_df[~final_df["passed_filters"]].copy()

    print(f"Passed: {{len(passed)}} | Rejected: {{len(rejected)}}")

    if not passed.empty:
        display(
            passed.loc[:, [
                c for c in [
                    "trading_pair",
                    "screen_score",
                    "quote_volume_24h",
                    "spread_bps",
                    "top_of_book_quote",
                    "sym_depth_quote_10bps",
                    "recent_trade_count",
                    "last_trade_age_sec",
                    "natr_bps_mean",
                    "efficiency_ratio",
                ] if c in passed.columns
            ]].head(cfg.final_top_n)
        )

    if not rejected.empty:
        reject_counts = (
            rejected["rejection_reason"]
            .fillna("")
            .str.split("; ")
            .explode()
            .loc[lambda s: s.ne("")]
            .value_counts()
            .rename_axis("rejection_reason")
            .to_frame("count")
        )
        display(reject_counts.head(20))

Passed: {len(passed)} | Rejected: {len(rejected)}

,trading_pair,screen_score,quote_volume_24h,spread_bps,top_of_book_quote,sym_depth_quote_10bps,recent_trade_count,last_trade_age_sec,natr_bps_mean,efficiency_ratio
0,USDC-USDT,82.172668,1.683752e+06,51.994801,472.973590,0.000000,200,0.459929,15.033446,0.001821
1,SOL-USDT,78.261385,2.026641e+06,61.208875,1596.798000,0.000000,200,7.193323,27.132022,0.027983
2,UNI-USDT,74.166667,3.632007e+05,78.346616,2204.442680,0.000000,200,21.495398,26.936767,0.063014
3,LTC-USDT,72.022096,8.153326e+05,40.848948,28.238210,0.000000,200,9.173946,22.615545,0.004969
4,AVAX-USDT,71.221316,5.110441e+05,82.730093,258.771500,0.000000,200,12.886237,23.203397,0.031008
5,AAVE-USDT,70.953422,1.001274e+05,65.736875,369.313800,0.000000,200,2.164241,26.030989,0.016089
6,RENDER-USDT,69.469167,1.126968e+05,75.471698,887.040000,0.000000,200,12.215571,40.651349,0.086482
7,NKYC-USDT,69.279822,1.685141e+05,10.514318,36.864207,36.864207,200,28.938642,13.821795,0.004851
8,PEPE-USDT,67.895280,1.196857e+05,56.657224,119.553022,0.000000,200,18.749890,13.046437,0.063291
9,BCH-USDT,64.723030,1.328396e+05,65.352588,5.664144,0.000000,200,8.646626,27.252494,0.012567

                        count
rejection_reason
top_of_book_quote<5        66
quote_volume_24h<50000     44
coverage_ratio<0.90         7
natr_bps_mean<12            4

## 5. Export artifacts

This writes CSV, JSON, a Markdown report, a candle-ingestor manifest, and an exchange-rules patch for the selected pairs.

In [6]:
artifact_paths = export_screening_artifacts(
    run,
    output_dir=str(OUTPUT_ROOT),
    base_url=NONKYC_BASE_URL,
    trade_limit=cfg.recent_trade_limit,
)

print("Artifacts written")
display(pd.Series(asdict(artifact_paths)).to_frame("path"))

Artifacts written

                                                                                                                                                  path
root_dir                                               /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054
universe_csv                              /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/universe.csv
shortlist_csv                            /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/shortlist.csv
final_csv                             /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/final_screen.csv
selected_csv                        /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/selected_pairs.csv
selected_pairs_txt                  /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/selected_pairs.txt
selected_pairs_json                /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/selected_pairs.json
symbol_metadata_json              /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/symbol_metadata.json
candle_ingestor_manifest_yaml  /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/candle_ingestor_mani...
exchange_rules_patch_yaml      /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/exchange_rules_patch...
screening_report_md                /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/screening_report.md
run_metadata_json                    /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260325_235054/run_metadata.json

## 6. Merge into candle ingestion

The manifest below follows the same `exchanges -> pairs -> intervals` structure already used by your candle-ingest and candle-gap-repair tooling, with slash-formatted exchange pairs and Hummingbot-normalized selected pair files alongside it.

In [7]:
from pathlib import Path

print("Selected Hummingbot pairs")
print("-" * 80)
print(Path(artifact_paths.selected_pairs_txt).read_text())

print("\nCandle ingestor manifest")
print("-" * 80)
print(Path(artifact_paths.candle_ingestor_manifest_yaml).read_text())

print("\nExchange rules patch (estimates only)")
print("-" * 80)
print(Path(artifact_paths.exchange_rules_patch_yaml).read_text())

Selected Hummingbot pairs
--------------------------------------------------------------------------------
USDC-USDT
SOL-USDT
UNI-USDT
LTC-USDT
AVAX-USDT
AAVE-USDT
RENDER-USDT
NKYC-USDT
PEPE-USDT
BCH-USDT


Candle ingestor manifest
--------------------------------------------------------------------------------
backfill_days: 180
request_delay: 0.5
overlap_candles: 2
include_open_candle: false
http:
  timeout_seconds: 30.0
  max_retries: 3
  retry_backoff: 1.8
  user_agent: pmm-lab-screener/0.1
exchanges:
  nonkyc:
    enabled: true
    base_url: https://api.nonkyc.io/api/v2
    pairs:
    - USDC/USDT
    - SOL/USDT
    - UNI/USDT
    - LTC/USDT
    - AVAX/USDT
    - AAVE/USDT
    - RENDER/USDT
    - NKYC/USDT
    - PEPE/USDT
    - BCH/USDT
    intervals:
    - 5m
    trades:
      enabled: true
      limit: 500
      update_recent_candles: false
      recent_window_minutes: 120


Exchange rules patch (estimates only)
--------------------------------------------------------------------------------
connectors:
  nonkyc:
    pairs:
      USDC-USDT:
        price_tick: 0.0001
        amount_step: 0.01
      SOL-USDT:
        price_tick: 0.01
        amount_step: 0.01
      UNI-USDT:
        price_tick: 0.001
        amount_step: 0.01
      LTC-USDT:
        price_tick: 0.01
        amount_step: 0.0001
      AVAX-USDT:
        price_tick: 0.01
        amount_step: 0.01
      AAVE-USDT:
        price_tick: 0.01
        amount_step: 0.001
      RENDER-USDT:
        price_tick: 0.001
        amount_step: 0.01
      NKYC-USDT:
        price_tick: 1.0e-06
        amount_step: 0.0001
      PEPE-USDT:
        price_tick: 1.0e-08
        amount_step: 1.0
      BCH-USDT:
        price_tick: 0.1
        amount_step: 1.0e-05