# PMM Dynamic Screener — MEXC Public REST

This notebook screens **MEXC** markets for **PMM Dynamic (Predictive Market Making)** using only public market-data endpoints. It is a **pre-ingestion gate**: the output is a ranked shortlist plus a candle-ingestor manifest, selected `BASE-QUOTE` pairs, and rule-estimate metadata.

This notebook is **public-data only**. It uses unauthenticated MEXC spot market endpoints and does not require or send any account credentials.

Stop-ship stance: a pair passing this notebook is **fit for research and ingestion only** until it survives candle-quality checks, walk-forward validation, and live microstructure review.

In [1]:
import os
import sys
import subprocess
import logging
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from IPython.display import display, Markdown

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 160)
pd.set_option("display.max_colwidth", 120)

CANDIDATE_DIRS = [
    Path("/quants-lab/research_notebooks/market_lab/pmm_dynamic"),
    Path.cwd(),
    Path.cwd().parent,
    Path.cwd().parent.parent,
]
PMM_DIR = next((p.resolve() for p in CANDIDATE_DIRS if (p / "pyproject.toml").exists() and (p / "pmm_lab").exists()), None)
if PMM_DIR is None:
    raise FileNotFoundError("Could not locate the pmm_dynamic project root. Open this notebook from inside the pmm_dynamic repo.")

if str(PMM_DIR) not in sys.path:
    sys.path.insert(0, str(PMM_DIR))
subprocess.check_call(
    [sys.executable, "-m", "pip", "install", "-e", str(PMM_DIR), "--quiet"],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL,
)

logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("pmm_lab").setLevel(logging.WARNING)

print(f"PMM project root: {PMM_DIR}")


from pmm_lab.screener import MEXCPublicScreener, default_mexc_config, export_screening_artifacts
from pmm_lab.screener.common import compute_coarse_scores, select_shortlist
from pmm_lab.screener.mexc_public import MEXC_BASE_URL

PMM project root: /quants-lab/research_notebooks/market_lab/pmm_dynamic

## 1. Configuration

Edit the universe, thresholds, and output path here. Keep the defaults conservative unless you explicitly want a wider exploratory net.

In [2]:
# ============================================================
# USER CONFIG — edit these, then Run All
# ============================================================
QUOTE_ASSET = "*"
INTERVAL = "5m"
UNIVERSE_TOP_K = 100
FINAL_TOP_N = 30
CANDLE_LIMIT = 288
DEPTH_LIMIT = 200
RECENT_TRADE_LIMIT = 500

# Optional pair overrides.
# Keep INCLUDE_SYMBOLS empty to use the full eligible universe.
INCLUDE_SYMBOLS = []
EXCLUDE_SYMBOLS = []

OUTPUT_ROOT = (
    PMM_DIR / "artifacts" / "screener" / "mexc" /
    datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
)

cfg = default_mexc_config()
cfg.quote_asset = QUOTE_ASSET
cfg.interval = INTERVAL
cfg.universe_top_k = UNIVERSE_TOP_K
cfg.final_top_n = FINAL_TOP_N
cfg.candle_limit = CANDLE_LIMIT
cfg.depth_limit = DEPTH_LIMIT
cfg.recent_trade_limit = RECENT_TRADE_LIMIT
cfg.include_symbols = tuple(INCLUDE_SYMBOLS)
cfg.exclude_symbols = tuple(EXCLUDE_SYMBOLS)

# Conservative defaults. Loosen only if you explicitly want more exploratory coverage.
cfg.min_quote_volume_24h = 1000000.0
cfg.max_spread_bps = 50.0
cfg.min_top_of_book_quote = 250.0
cfg.min_depth_10bps_quote = 1000.0
cfg.max_last_trade_age_sec = 1800.0
cfg.min_recent_trade_count = 100
cfg.min_candle_count = 240
cfg.min_candle_coverage_ratio = 0.97
cfg.max_zero_volume_fraction = 0.2
cfg.min_natr_bps = 10.0
cfg.max_natr_bps = 250.0

print("Screener config")
display(pd.Series(cfg.as_dict()).to_frame("value"))
print(f"Output root: {OUTPUT_ROOT}")

Screener config

                                                                                                                                         value
connector                                                                                                                                 mexc
quote_asset                                                                                                                                  *
interval                                                                                                                                    5m
universe_top_k                                                                                                                             100
final_top_n                                                                                                                                 30
candle_limit                                                                                                                               288
depth_limit                                                                                                                                200
recent_trade_limit                                                                                                                         500
request_pause_sec                                                                                                                         0.12
timeout_seconds                                                                                                                           30.0
max_retries                                                                                                                                  3
retry_backoff                                                                                                                              1.8
user_agent                                                                                                                pmm-lab-screener/0.1
min_quote_volume_24h                                                                                                                 1000000.0
max_spread_bps                                                                                                                            50.0
min_top_of_book_quote                                                                                                                    250.0
min_depth_10bps_quote                                                                                                                   1000.0
min_depth_50bps_quote                                                                                                                      0.0
min_depth_1xspread_quote                                                                                                                   0.0
max_last_trade_age_sec                                                                                                                  1800.0
min_recent_trade_count                                                                                                                     100
min_candle_count                                                                                                                           240
min_candle_coverage_ratio                                                                                                                 0.97
max_zero_volume_fraction                                                                                                                   0.2
min_natr_bps                                                                                                                              10.0
max_natr_bps                                                                                                                             250.0
natr_soft_min                                                                                                                              6.0
natr_target_min                                                                                                                           15.0
natr_target_max                                                                                                                          120.0
natr_soft_max                                                                                                                            250.0
efficiency_soft_min                                                                                                                        0.0
efficiency_target_min                                                                                                                     0.05
efficiency_target_max                                                                                                                      0.4
efficiency_soft_max                                                                                                                       0.75
vol_to_spread_soft_min                                                                                                                     1.0
vol_to_spread_target_min                                                                                                                   3.0
vol_to_spread_target_max                                                                                                                  20.0
vol_to_spread_soft_max                                                                                                                    50.0
exclude_regex                                                                             ((?:^|[^A-Z])(3L|3S|5L|5S)$, (?:UP|DOWN|BULL|BEAR)$)
include_symbols                                                                                                                             ()
exclude_symbols                                                                                                                             ()
score_weights              {'volume': 0.24, 'depth': 0.2, 'spread': 0.16, 'top_of_book': 0.08, 'activity': 0.12, 'quality': 0.1, 'alpha': 0.1}
selection_mode                                                                                                                          strict
fallback_if_empty                                                                                                                        False
interval_seconds                                                                                                                           300

Output root: /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949

## 2. Build the cheap universe snapshot

This step uses only batch endpoints to discover the broad market universe and assign a coarse score before any per-pair enrichment calls are made.

In [3]:
screener = MEXCPublicScreener(cfg)

universe = screener.build_universe()
universe = compute_coarse_scores(universe)
shortlist = select_shortlist(universe, cfg)

summary = pd.DataFrame([
    {
        "connector": cfg.connector,
        "quote_asset": cfg.quote_asset,
        "interval": cfg.interval,
        "universe_rows": len(universe),
        "shortlist_rows": len(shortlist),
    }
])
display(summary)

preview_cols = [
    c for c in [
        "trading_pair",
        "exchange_symbol",
        "quote_volume_24h",
        "spread_bps",
        "coarse_score",
        "price_tick_estimate",
        "amount_step_estimate",
        "status_detail",
    ]
    if c in universe.columns
]

display(universe.loc[:, preview_cols].head(20))
print(f"Shortlist for detailed enrichment: {len(shortlist)}")
display(shortlist.loc[:, preview_cols].head(min(25, len(shortlist))))

  connector quote_asset interval  universe_rows  shortlist_rows
0      mexc           *       5m           2403             100

       trading_pair exchange_symbol  quote_volume_24h  spread_bps  coarse_score  price_tick_estimate  amount_step_estimate status_detail
0          ETH-USDT         ETHUSDT      9.092971e+08    0.046590     99.904256             0.010000              0.000100             1
1   GOLD(PAXG)-USDT  GOLD(PAXG)USDT      5.719428e+07    0.022924     99.764827             0.010000              0.000001             1
2         USDC-USDT        USDCUSDT      3.251860e+07    0.999750     99.598328             0.000100              1.000000             1
3         USD1-USDT        USD1USDT      1.586873e+07    1.000350     99.349653             0.000100              0.000000             1
4          BNB-USDT         BNBUSDT      4.900773e+07    0.158074     99.314170             0.010000              0.001000             1
5          XRP-USDT         XRPUSDT      1.164552e+08    1.414527     99.132011             0.000100              0.100000             1
6          SUI-USDT         SUIUSDT      2.342215e+07    1.061740     98.926009             0.000100              0.000000             1
7          SOL-USDT         SOLUSDT      1.536872e+08    1.103205     98.903017             0.010000              0.010000             1
8         USDE-USDT        USDEUSDT      5.753759e+06    1.000450     98.859627             0.000100              0.000000             1
9          LTC-USDT         LTCUSDT      1.037177e+07    1.801315     98.699220             0.010000              0.001000             1
10        LINK-USDT        LINKUSDT      3.241892e+07    1.096551     98.678271             0.001000              0.010000             1
11         EUR-USDT         EURUSDT      7.127868e+06    0.863371     98.428650             0.000100              0.000000             1
12         TRX-USDT         TRXUSDT      1.082191e+07    3.230496     98.403614             0.000100              1.000000             1
13        XUSD-USDT        XUSDUSDT      2.752354e+06    0.999650     98.345710             0.000100              0.000000             1
14         ADA-USDT         ADAUSDT      1.987415e+07    3.821899     98.324437             0.000100              0.100000             1
15         UNI-USDT         UNIUSDT      6.555532e+06    2.789789     97.920778             0.001000              0.001000             1
16         WLD-USDT         WLDUSDT      5.828356e+06    3.104144     97.879184             0.000100              0.000000             1
17         DAI-USDT         DAIUSDT      1.981967e+06    0.999850     97.446631             0.000100              0.500000             1
18         WXT-USDT         WXTUSDT      2.021879e+06    1.895196     97.311318             0.000001              0.000000             1
19        HYPE-USDT        HYPEUSDT      1.664101e+07    2.624328     97.125455             0.010000              0.000000             1

Shortlist for detailed enrichment: 100

       trading_pair exchange_symbol  quote_volume_24h  spread_bps  coarse_score  price_tick_estimate  amount_step_estimate status_detail
0          ETH-USDT         ETHUSDT      9.092971e+08    0.046590     99.904256             0.010000              0.000100             1
1   GOLD(PAXG)-USDT  GOLD(PAXG)USDT      5.719428e+07    0.022924     99.764827             0.010000              0.000001             1
2         USDC-USDT        USDCUSDT      3.251860e+07    0.999750     99.598328             0.000100              1.000000             1
3         USD1-USDT        USD1USDT      1.586873e+07    1.000350     99.349653             0.000100              0.000000             1
4          BNB-USDT         BNBUSDT      4.900773e+07    0.158074     99.314170             0.010000              0.001000             1
5          XRP-USDT         XRPUSDT      1.164552e+08    1.414527     99.132011             0.000100              0.100000             1
6          SUI-USDT         SUIUSDT      2.342215e+07    1.061740     98.926009             0.000100              0.000000             1
7          SOL-USDT         SOLUSDT      1.536872e+08    1.103205     98.903017             0.010000              0.010000             1
8         USDE-USDT        USDEUSDT      5.753759e+06    1.000450     98.859627             0.000100              0.000000             1
9          LTC-USDT         LTCUSDT      1.037177e+07    1.801315     98.699220             0.010000              0.001000             1
10        LINK-USDT        LINKUSDT      3.241892e+07    1.096551     98.678271             0.001000              0.010000             1
11         EUR-USDT         EURUSDT      7.127868e+06    0.863371     98.428650             0.000100              0.000000             1
12         TRX-USDT         TRXUSDT      1.082191e+07    3.230496     98.403614             0.000100              1.000000             1
13        XUSD-USDT        XUSDUSDT      2.752354e+06    0.999650     98.345710             0.000100              0.000000             1
14         ADA-USDT         ADAUSDT      1.987415e+07    3.821899     98.324437             0.000100              0.100000             1
15         UNI-USDT         UNIUSDT      6.555532e+06    2.789789     97.920778             0.001000              0.001000             1
16         WLD-USDT         WLDUSDT      5.828356e+06    3.104144     97.879184             0.000100              0.000000             1
17         DAI-USDT         DAIUSDT      1.981967e+06    0.999850     97.446631             0.000100              0.500000             1
18         WXT-USDT         WXTUSDT      2.021879e+06    1.895196     97.311318             0.000001              0.000000             1
19        HYPE-USDT        HYPEUSDT      1.664101e+07    2.624328     97.125455             0.010000              0.000000             1
20       TRUMP-USDT       TRUMPUSDT      3.762101e+06    3.054834     96.807304             0.001000              0.000000             1
21         XLM-USDT         XLMUSDT      5.333997e+06    6.062443     96.698966             0.000100              0.100000             1
22        PUMP-USDT        PUMPUSDT      2.474556e+06    5.585032     96.370311             0.000001              0.000000             1
23         DOT-USDT         DOTUSDT      6.242974e+06    7.044734     96.292978             0.001000              0.001000             1
24       PENGU-USDT       PENGUUSDT      3.856342e+06    1.439367     95.987135             0.000001              0.000000             1

## 3. Run the detailed screener

This step enriches the shortlist with order-book depth, recent trades, and candles, then applies hard gates plus the final PMM-oriented score.

In [4]:
run = screener.screen_from_universe(universe)
final_df = run.final.copy()
selected_df = run.selected.copy()

status_counts = pd.DataFrame([
    {
        "enriched_rows": len(final_df),
        "selected_rows": len(selected_df),
        "pass_rate": float(selected_df.shape[0] / final_df.shape[0]) if len(final_df) else 0.0,
    }
])
display(status_counts)

final_cols = [
    c for c in [
        "trading_pair",
        "screen_score",
        "passed_filters",
        "quote_volume_24h",
        "spread_bps",
        "top_of_book_quote",
        "sym_depth_quote_10bps",
        "recent_trade_count",
        "last_trade_age_sec",
        "n_candles",
        "coverage_ratio",
        "zero_volume_fraction",
        "natr_bps_mean",
        "efficiency_ratio",
        "rejection_reason",
    ]
    if c in final_df.columns
]
display(final_df.loc[:, final_cols].head(min(50, len(final_df))))

   enriched_rows  selected_rows  pass_rate
0            100             27       0.27

,trading_pair,screen_score,passed_filters,quote_volume_24h,spread_bps,top_of_book_quote,sym_depth_quote_10bps,recent_trade_count,last_trade_age_sec,n_candles,coverage_ratio,zero_volume_fraction,natr_bps_mean,efficiency_ratio,rejection_reason
0,SOL-USDT,92.066385,True,1.536872e+08,1.103205,2.177685e+03,6.793480e+05,500,6.920546,288,1.0,0.000000,34.292613,0.099015,
1,DOGE-USDT,91.014450,True,3.997877e+07,1.068662,3.895813e+03,2.749801e+05,500,3.646674,288,1.0,0.000000,31.371570,0.065978,
2,ADA-USDT,85.096000,True,1.987415e+07,3.820439,7.053730e+03,8.049767e+04,500,2.066716,288,1.0,0.000000,34.580912,0.078493,
3,LTC-USDT,84.448000,True,1.037177e+07,1.801315,1.581946e+03,7.650489e+04,500,11.675224,288,1.0,0.000000,23.401964,0.083605,
4,BNB-USDT,84.096329,True,4.900773e+07,0.158072,5.729097e+02,9.182993e+04,500,5.326376,288,1.0,0.000000,20.936207,0.029595,
5,LINK-USDT,84.032458,True,3.241892e+07,1.096551,4.559500e+02,3.186715e+04,500,22.627482,288,1.0,0.000000,32.940267,0.091439,
6,GOLD(PAXG)-USDT,83.210071,True,5.719428e+07,0.022919,1.391359e+03,8.700509e+04,500,13.716707,288,1.0,0.000000,41.653120,0.004631,
7,TRX-USDT,81.637632,True,1.082191e+07,3.230496,1.071396e+04,1.461079e+05,500,16.438863,288,1.0,0.000000,14.336747,0.014409,
8,TAO-USDT,80.978000,True,2.508577e+07,4.450661,2.845514e+03,1.033551e+04,500,5.414564,288,1.0,0.000000,70.375819,0.129422,
9,UNI-USDT,75.224980,True,6.555532e+06,2.788234,8.468907e+02,1.586584e+04,500,26.002542,288,1.0,0.000000,33.734122,0.043925,
10,TRUMP-USDT,73.466542,True,3.762101e+06,3.054834,5.367068e+02,2.706028e+04,500,6.714797,288,1.0,0.000000,33.574480,0.043588,
11,HBAR-USDT,73.244250,True,6.180935e+06,1.075789,3.555337e+02,1.169619e+04,500,30.099616,288,1.0,0.000000,30.304716,0.067847,
12,WLD-USDT,72.720000,True,5.828356e+06,3.102218,1.177276e+03,7.801908e+03,500,27.957449,288,1.0,0.000000,43.023601,0.055118,
13,TON-USDT,68.320000,True,2.908211e+06,7.504690,1.259477e+04,1.259477e+04,500,23.076282,288,1.0,0.000000,25.597421,0.165563,
14,DOT-USDT,67.104911,True,6.242974e+06,7.054674,2.131523e+03,2.131523e+03,500,9.763884,288,1.0,0.000000,39.585422,0.019324,
15,WXT-USDT,65.960000,True,2.021879e+06,1.421094,1.620496e+03,9.531028e+03,500,11.762587,288,1.0,0.000000,23.083297,0.094959,
16,ZRO-USDT,64.468000,True,2.381017e+06,4.687134,5.302777e+02,1.349157e+03,500,2.868280,288,1.0,0.000000,64.655242,0.077679,
17,ASTER-USDT,62.927196,True,2.814065e+06,4.556847,4.084017e+02,3.913374e+03,500,42.633916,288,1.0,0.000000,24.281655,0.046598,
18,SHIB-USDT,62.002000,True,4.928952e+06,8.227067,1.090964e+03,2.179682e+03,500,13.845470,288,1.0,0.000000,36.534796,0.080799,
19,PUMP-USDT,58.755536,True,2.474556e+06,5.585032,1.280273e+03,8.989686e+03,500,8.894121,288,1.0,0.000000,43.917277,0.000823,
20,SAHARA-USDT,57.790000,True,2.391661e+06,3.838035,3.624076e+02,1.841491e+03,500,13.976936,288,1.0,0.000000,45.647757,0.050202,
21,ICP-USDT,56.264237,True,2.867859e+06,4.177982,2.602996e+02,2.201351e+03,500,18.520671,288,1.0,0.000000,33.000038,0.005034,
22,OP-USDT,56.120375,True,2.387150e+06,8.892841,3.168151e+03,3.168151e+03,500,38.446069,288,1.0,0.003472,41.787595,0.051699,
23,ETC-USDT,55.204000,True,2.770990e+06,11.855365,2.599542e+03,2.599542e+03,500,50.325922,288,1.0,0.000000,41.099279,0.059603,
24,RENDER-USDT,54.800000,True,1.338606e+06,5.715919,3.094350e+02,9.340883e+03,500,10.795107,288,1.0,0.000000,45.619329,0.101681,
25,CRV-USDT,52.871151,True,1.112636e+06,4.530011,3.683827e+02,1.612297e+03,500,17.652151,288,1.0,0.000000,38.008681,0.027397,
26,ATOM-USDT,50.887482,True,1.707744e+06,5.622716,5.730693e+02,3.321585e+03,500,25.114570,288,1.0,0.000000,29.508226,0.001242,
27,BTC-USDT,89.494667,False,1.068947e+09,0.001415,1.156640e+02,4.679629e+05,500,5.117151,288,1.0,0.000000,24.977836,0.089945,top_of_book_quote<250
28,XRP-USDT,86.017965,False,1.164552e+08,0.707239,2.188872e+01,3.641493e+05,500,3.205603,288,1.0,0.000000,31.114476,0.054167,top_of_book_quote<250
29,USDC-USDT,84.991254,False,3.251860e+07,0.999750,3.928171e+06,1.219354e+07,500,6.578343,288,1.0,0.000000,1.044891,0.000000,natr_bps_mean<10
30,ETH-USDT,84.100667,False,9.092971e+08,0.046590,1.766479e+01,1.372953e+05,500,3.576302,288,1.0,0.000000,33.907834,0.089730,top_of_book_quote<250
31,USD1-USDT,82.946300,False,1.586873e+07,1.000350,8.488829e+05,8.990969e+06,500,9.482484,288,1.0,0.000000,1.069777,0.006369,natr_bps_mean<10
32,SUI-USDT,82.883244,False,2.342215e+07,1.061740,7.316679e+01,8.769179e+04,500,7.064081,288,1.0,0.000000,34.944851,0.068371,top_of_book_quote<250
33,AVAX-USDT,80.406000,False,1.443714e+07,2.087683,9.964240e+01,8.059761e+02,500,7.045616,288,1.0,0.000000,33.544095,0.096815,top_of_book_quote<250; depth_10bps<1000
34,GOLD(XAUT)-USDT,79.653255,False,1.423242e+08,0.229576,1.067195e+01,1.216791e+05,500,3.968579,288,1.0,0.000000,42.445879,0.007709,top_of_book_quote<250
35,NEAR-USDT,72.494012,False,8.999306e+06,3.832152,1.411469e+01,5.940118e+03,500,11.336485,288,1.0,0.000000,35.695239,0.028040,top_of_book_quote<250
36,FIL-USDT,71.972000,False,7.129101e+06,3.246226,1.141575e+02,3.412903e+03,500,16.175486,288,1.0,0.000000,41.340498,0.106938,top_of_book_quote<250
37,AAVE-USDT,71.939416,False,6.776602e+06,0.906166,1.732652e+01,4.748722e+03,500,9.844563,288,1.0,0.000000,33.949759,0.052291,top_of_book_quote<250
38,EUR-USDT,70.213318,False,7.127868e+06,0.863371,3.855402e+02,1.830504e+05,500,88.529037,288,1.0,0.000000,5.157356,0.035370,natr_bps_mean<10
39,ZEC-USDT,69.812667,False,1.771351e+07,0.438856,1.276016e+01,8.412046e+03,500,13.212054,288,1.0,0.000000,50.062410,0.050300,top_of_book_quote<250
40,ENA-USDT,68.470000,False,7.899750e+06,4.332286,1.654450e+01,1.670488e+04,500,7.733289,288,1.0,0.000000,43.560329,0.063830,top_of_book_quote<250
41,USDE-USDT,68.284395,False,5.753759e+06,1.000450,1.002378e+05,1.971587e+06,500,91.773433,288,1.0,0.000000,1.125544,0.000000,natr_bps_mean<10
42,XRP-USDC,67.882000,False,2.274015e+06,7.073637,1.646694e+02,4.936948e+03,500,12.675746,288,1.0,0.000000,30.085367,0.051680,top_of_book_quote<250
43,HYPE-USDT,66.547195,False,1.664101e+07,2.622951,1.220160e+01,5.668733e+03,500,14.724602,288,1.0,0.000000,44.336840,0.002708,top_of_book_quote<250
44,DAI-USDT,66.536489,False,1.981967e+06,0.999850,6.522052e+02,1.590077e+05,500,18.910901,288,1.0,0.000000,1.590153,0.019868,natr_bps_mean<10
45,ETH-USDC,66.522000,False,4.870344e+06,4.006186,2.282378e+01,3.620321e+04,500,10.275611,288,1.0,0.000000,32.724999,0.091924,top_of_book_quote<250
46,PEPE-USDT,64.980000,False,1.537840e+07,11.665209,6.840512e+01,6.449606e+03,500,9.943881,288,1.0,0.000000,42.899545,0.051675,top_of_book_quote<250
47,BNB-USDC,63.043087,False,2.463713e+06,2.687386,1.265000e+01,6.196049e+02,500,10.715272,288,1.0,0.000000,19.879510,0.030456,top_of_book_quote<250; depth_10bps<1000
48,WLFI-USDT,62.622000,False,5.618126e+06,9.594167,1.989037e+02,2.781385e+03,500,27.608952,288,1.0,0.000000,42.579416,0.067786,top_of_book_quote<250
49,XLM-USDT,62.494375,False,5.333997e+06,6.062443,2.956800e+01,1.175598e+04,500,30.722839,288,1.0,0.003472,35.646984,0.088161,top_of_book_quote<250

## 4. Diagnostics

Inspect which pairs passed, which pairs failed, and why. Rejection counts are often more useful than raw rankings because they show whether you are liquidity-bound, spread-bound, or data-quality-bound.

In [5]:
if final_df.empty:
    print("No enriched rows returned.")
else:
    passed = final_df[final_df["passed_filters"]].copy()
    rejected = final_df[~final_df["passed_filters"]].copy()

    print(f"Passed: {{len(passed)}} | Rejected: {{len(rejected)}}")

    if not passed.empty:
        display(
            passed.loc[:, [
                c for c in [
                    "trading_pair",
                    "screen_score",
                    "quote_volume_24h",
                    "spread_bps",
                    "top_of_book_quote",
                    "sym_depth_quote_10bps",
                    "recent_trade_count",
                    "last_trade_age_sec",
                    "natr_bps_mean",
                    "efficiency_ratio",
                ] if c in passed.columns
            ]].head(cfg.final_top_n)
        )

    if not rejected.empty:
        reject_counts = (
            rejected["rejection_reason"]
            .fillna("")
            .str.split("; ")
            .explode()
            .loc[lambda s: s.ne("")]
            .value_counts()
            .rename_axis("rejection_reason")
            .to_frame("count")
        )
        display(reject_counts.head(20))

Passed: {len(passed)} | Rejected: {len(rejected)}

,trading_pair,screen_score,quote_volume_24h,spread_bps,top_of_book_quote,sym_depth_quote_10bps,recent_trade_count,last_trade_age_sec,natr_bps_mean,efficiency_ratio
0,SOL-USDT,92.066385,1.536872e+08,1.103205,2177.684950,679348.004640,500,6.920546,34.292613,0.099015
1,DOGE-USDT,91.014450,3.997877e+07,1.068662,3895.813150,274980.103197,500,3.646674,31.371570,0.065978
2,ADA-USDT,85.096000,1.987415e+07,3.820439,7053.729760,80497.669859,500,2.066716,34.580912,0.078493
3,LTC-USDT,84.448000,1.037177e+07,1.801315,1581.946184,76504.885688,500,11.675224,23.401964,0.083605
4,BNB-USDT,84.096329,4.900773e+07,0.158072,572.909728,91829.926281,500,5.326376,20.936207,0.029595
5,LINK-USDT,84.032458,3.241892e+07,1.096551,455.950000,31867.148570,500,22.627482,32.940267,0.091439
6,GOLD(PAXG)-USDT,83.210071,5.719428e+07,0.022919,1391.358526,87005.092372,500,13.716707,41.653120,0.004631
7,TRX-USDT,81.637632,1.082191e+07,3.230496,10713.958776,146107.910110,500,16.438863,14.336747,0.014409
8,TAO-USDT,80.978000,2.508577e+07,4.450661,2845.513720,10335.509260,500,5.414564,70.375819,0.129422
9,UNI-USDT,75.224980,6.555532e+06,2.788234,846.890700,15865.843510,500,26.002542,33.734122,0.043925
10,TRUMP-USDT,73.466542,3.762101e+06,3.054834,536.706820,27060.279910,500,6.714797,33.574480,0.043588
11,HBAR-USDT,73.244250,6.180935e+06,1.075789,355.533750,11696.193059,500,30.099616,30.304716,0.067847
12,WLD-USDT,72.720000,5.828356e+06,3.102218,1177.275840,7801.907872,500,27.957449,43.023601,0.055118
13,TON-USDT,68.320000,2.908211e+06,7.504690,12594.770520,12594.770520,500,23.076282,25.597421,0.165563
14,DOT-USDT,67.104911,6.242974e+06,7.054674,2131.523420,2131.523420,500,9.763884,39.585422,0.019324
15,WXT-USDT,65.960000,2.021879e+06,1.421094,1620.495712,9531.027842,500,11.762587,23.083297,0.094959
16,ZRO-USDT,64.468000,2.381017e+06,4.687134,530.277660,1349.156910,500,2.868280,64.655242,0.077679
17,ASTER-USDT,62.927196,2.814065e+06,4.556847,408.401700,3913.374059,500,42.633916,24.281655,0.046598
18,SHIB-USDT,62.002000,4.928952e+06,8.227067,1090.964143,2179.682384,500,13.845470,36.534796,0.080799
19,PUMP-USDT,58.755536,2.474556e+06,5.585032,1280.272548,8989.685511,500,8.894121,43.917277,0.000823
20,SAHARA-USDT,57.790000,2.391661e+06,3.838035,362.407600,1841.491160,500,13.976936,45.647757,0.050202
21,ICP-USDT,56.264237,2.867859e+06,4.177982,260.299620,2201.351320,500,18.520671,33.000038,0.005034
22,OP-USDT,56.120375,2.387150e+06,8.892841,3168.151360,3168.151360,500,38.446069,41.787595,0.051699
23,ETC-USDT,55.204000,2.770990e+06,11.855365,2599.542240,2599.542240,500,50.325922,41.099279,0.059603
24,RENDER-USDT,54.800000,1.338606e+06,5.715919,309.435000,9340.882880,500,10.795107,45.619329,0.101681
25,CRV-USDT,52.871151,1.112636e+06,4.530011,368.382720,1612.297128,500,17.652151,38.008681,0.027397
26,ATOM-USDT,50.887482,1.707744e+06,5.622716,573.069270,3321.585070,500,25.114570,29.508226,0.001242

                           count
rejection_reason
top_of_book_quote<250         56
depth_10bps<1000              36
quote_volume_24h<1e+06        27
natr_bps_mean<10               8
zero_volume_fraction>0.20      2

## 5. Export artifacts

This writes CSV, JSON, a Markdown report, a candle-ingestor manifest, and an exchange-rules patch for the selected pairs.

In [6]:
artifact_paths = export_screening_artifacts(
    run,
    output_dir=str(OUTPUT_ROOT),
    base_url=MEXC_BASE_URL,
    trade_limit=cfg.recent_trade_limit,
)

print("Artifacts written")
display(pd.Series(asdict(artifact_paths)).to_frame("path"))

Artifacts written

                                                                                                                                                  path
root_dir                                                 /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949
universe_csv                                /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/universe.csv
shortlist_csv                              /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/shortlist.csv
final_csv                               /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/final_screen.csv
selected_csv                          /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/selected_pairs.csv
selected_pairs_txt                    /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/selected_pairs.txt
selected_pairs_json                  /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/selected_pairs.json
symbol_metadata_json                /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/symbol_metadata.json
candle_ingestor_manifest_yaml  /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/candle_ingestor_manife...
exchange_rules_patch_yaml      /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/exchange_rules_patch.yaml
screening_report_md                  /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/screening_report.md
run_metadata_json                      /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/mexc/20260324_040949/run_metadata.json

## 6. Merge into candle ingestion

The manifest below follows the same `exchanges -> pairs -> intervals` structure already used by your candle-ingest and candle-gap-repair tooling, with slash-formatted exchange pairs and Hummingbot-normalized selected pair files alongside it.

In [7]:
from pathlib import Path

print("Selected Hummingbot pairs")
print("-" * 80)
print(Path(artifact_paths.selected_pairs_txt).read_text())

print("\nCandle ingestor manifest")
print("-" * 80)
print(Path(artifact_paths.candle_ingestor_manifest_yaml).read_text())

print("\nExchange rules patch (estimates only)")
print("-" * 80)
print(Path(artifact_paths.exchange_rules_patch_yaml).read_text())

Selected Hummingbot pairs
--------------------------------------------------------------------------------
SOL-USDT
DOGE-USDT
ADA-USDT
LTC-USDT
BNB-USDT
LINK-USDT
GOLD(PAXG)-USDT
TRX-USDT
TAO-USDT
UNI-USDT
TRUMP-USDT
HBAR-USDT
WLD-USDT
TON-USDT
DOT-USDT
WXT-USDT
ZRO-USDT
ASTER-USDT
SHIB-USDT
PUMP-USDT
SAHARA-USDT
ICP-USDT
OP-USDT
ETC-USDT
RENDER-USDT
CRV-USDT
ATOM-USDT


Candle ingestor manifest
--------------------------------------------------------------------------------
backfill_days: 180
request_delay: 0.5
overlap_candles: 2
include_open_candle: false
http:
  timeout_seconds: 30.0
  max_retries: 3
  retry_backoff: 1.8
  user_agent: pmm-lab-screener/0.1
exchanges:
  mexc:
    enabled: true
    base_url: https://api.mexc.com
    pairs:
    - SOL/USDT
    - DOGE/USDT
    - ADA/USDT
    - LTC/USDT
    - BNB/USDT
    - LINK/USDT
    - GOLD(PAXG)/USDT
    - TRX/USDT
    - TAO/USDT
    - UNI/USDT
    - TRUMP/USDT
    - HBAR/USDT
    - WLD/USDT
    - TON/USDT
    - DOT/USDT
    - WXT/USDT
    - ZRO/USDT
    - ASTER/USDT
    - SHIB/USDT
    - PUMP/USDT
    - SAHARA/USDT
    - ICP/USDT
    - OP/USDT
    - ETC/USDT
    - RENDER/USDT
    - CRV/USDT
    - ATOM/USDT
    intervals:
    - 5m
    trades:
      enabled: true
      limit: 500
      update_recent_candles: false
      recent_window_minutes: 120


Exchange rules patch (estimates only)
--------------------------------------------------------------------------------
connectors:
  mexc:
    pairs:
      SOL-USDT:
        price_tick: 0.01
        amount_step: 0.01
        min_notional_quote: 1.0
        min_order_size_base: 0.01
      DOGE-USDT:
        price_tick: 1.0e-05
        amount_step: 1.0
        min_notional_quote: 1.0
        min_order_size_base: 1.0
      ADA-USDT:
        price_tick: 0.0001
        amount_step: 0.1
        min_notional_quote: 1.0
        min_order_size_base: 0.1
      LTC-USDT:
        price_tick: 0.01
        amount_step: 0.001
        min_notional_quote: 1.0
        min_order_size_base: 0.001
      BNB-USDT:
        price_tick: 0.01
        amount_step: 0.001
        min_notional_quote: 1.0
        min_order_size_base: 0.001
      LINK-USDT:
        price_tick: 0.001
        amount_step: 0.01
        min_notional_quote: 1.0
        min_order_size_base: 0.01
      GOLD(PAXG)-USDT:
        price_tick: 0.01
        amount_step: 1.0e-06
        min_notional_quote: 1.0
        min_order_size_base: 1.0e-06
      TRX-USDT:
        price_tick: 0.0001
        amount_step: 1.0
        min_notional_quote: 1.0
        min_order_size_base: 1.0
      TAO-USDT:
        price_tick: 0.01
        amount_step: 0.01
        min_notional_quote: 1.0
        min_order_size_base: 0.01
      UNI-USDT:
        price_tick: 0.001
        amount_step: 0.001
        min_notional_quote: 1.0
        min_order_size_base: 0.001
      TRUMP-USDT:
        price_tick: 0.001
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      HBAR-USDT:
        price_tick: 1.0e-05
        amount_step: 0.01
        min_notional_quote: 1.0
        min_order_size_base: 0.01
      WLD-USDT:
        price_tick: 0.0001
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      TON-USDT:
        price_tick: 0.001
        amount_step: 0.001
        min_notional_quote: 1.0
        min_order_size_base: 0.001
      DOT-USDT:
        price_tick: 0.001
        amount_step: 0.001
        min_notional_quote: 1.0
        min_order_size_base: 0.001
      WXT-USDT:
        price_tick: 1.0e-06
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      ZRO-USDT:
        price_tick: 0.001
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      ASTER-USDT:
        price_tick: 0.0001
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      SHIB-USDT:
        price_tick: 1.0e-09
        amount_step: 10000.0
        min_notional_quote: 1.0
        min_order_size_base: 10000.0
      PUMP-USDT:
        price_tick: 1.0e-06
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      SAHARA-USDT:
        price_tick: 1.0e-05
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      ICP-USDT:
        price_tick: 0.001
        amount_step: 0.0001
        min_notional_quote: 1.0
        min_order_size_base: 0.0001
      OP-USDT:
        price_tick: 0.0001
        amount_step: 0.01
        min_notional_quote: 1.0
        min_order_size_base: 0.01
      ETC-USDT:
        price_tick: 0.01
        amount_step: 0.1
        min_notional_quote: 1.0
        min_order_size_base: 0.1
      RENDER-USDT:
        price_tick: 0.001
        amount_step: 0.0
        min_notional_quote: 1.0
        min_order_size_base: 0.0
      CRV-USDT:
        price_tick: 0.0001
        amount_step: 0.01
        min_notional_quote: 1.0
        min_order_size_base: 0.01
      ATOM-USDT:
        price_tick: 0.001
        amount_step: 0.001
        min_notional_quote: 1.0
        min_order_size_base: 0.001