# PMM Dynamic Screener — NonKYC Public REST

This notebook screens **NONKYC** markets for **PMM Dynamic (Predictive Market Making)** using only public market-data endpoints. It is a **pre-ingestion gate**: the output is a ranked shortlist plus a candle-ingestor manifest, selected `BASE-QUOTE` pairs, and rule-estimate metadata.

By default this notebook screens **all quote assets** available on NonKYC (USDT, XMR, BTC, USDC, etc.). To restrict to a single quote, set `QUOTE_ASSET` to e.g. `'USDT'`. To screen a specific set, use comma-separated values like `'USDT,XMR'`. The notebook uses the documented public REST endpoints for markets, tickers, order books, candles, and trades.

Stop-ship stance: a pair passing this notebook is **fit for research and ingestion only** until it survives candle-quality checks, walk-forward validation, and live microstructure review.

In [1]:
import os
import sys
import subprocess
import logging
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from IPython.display import display, Markdown

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 160)
pd.set_option("display.max_colwidth", 120)

CANDIDATE_DIRS = [
    Path("/quants-lab/research_notebooks/market_lab/pmm_dynamic"),
    Path.cwd(),
    Path.cwd().parent,
    Path.cwd().parent.parent,
]
PMM_DIR = next((p.resolve() for p in CANDIDATE_DIRS if (p / "pyproject.toml").exists() and (p / "pmm_lab").exists()), None)
if PMM_DIR is None:
    raise FileNotFoundError("Could not locate the pmm_dynamic project root. Open this notebook from inside the pmm_dynamic repo.")

if str(PMM_DIR) not in sys.path:
    sys.path.insert(0, str(PMM_DIR))
subprocess.check_call(
    [sys.executable, "-m", "pip", "install", "-e", str(PMM_DIR), "--quiet"],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL,
)

logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("pmm_lab").setLevel(logging.WARNING)

print(f"PMM project root: {PMM_DIR}")


from pmm_lab.screener import NonKYCPublicScreener, default_nonkyc_config, export_screening_artifacts
from pmm_lab.screener.common import compute_coarse_scores, select_shortlist
from pmm_lab.screener.nonkyc_public import NONKYC_BASE_URL

PMM project root: /quants-lab/research_notebooks/market_lab/pmm_dynamic

## 1. Configuration

Edit the universe, thresholds, and output path here. Keep the defaults conservative unless you explicitly want a wider exploratory net.

In [2]:
# ============================================================
# USER CONFIG — edit these, then Run All
# ============================================================
QUOTE_ASSET = "*"
INTERVAL = "5m"
UNIVERSE_TOP_K = 3000
FINAL_TOP_N = 15
CANDLE_LIMIT = 288
DEPTH_LIMIT = 200
RECENT_TRADE_LIMIT = 500

# Optional pair overrides.
# Keep INCLUDE_SYMBOLS empty to use the full eligible universe.
INCLUDE_SYMBOLS = []
EXCLUDE_SYMBOLS = []

OUTPUT_ROOT = (
    PMM_DIR / "artifacts" / "screener" / "nonkyc" /
    datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
)

cfg = default_nonkyc_config()
cfg.quote_asset = QUOTE_ASSET
cfg.interval = INTERVAL
cfg.universe_top_k = UNIVERSE_TOP_K
cfg.final_top_n = FINAL_TOP_N
cfg.candle_limit = CANDLE_LIMIT
cfg.depth_limit = DEPTH_LIMIT
cfg.recent_trade_limit = RECENT_TRADE_LIMIT
cfg.include_symbols = tuple(INCLUDE_SYMBOLS)
cfg.exclude_symbols = tuple(EXCLUDE_SYMBOLS)

# Conservative defaults. Loosen only if you explicitly want more exploratory coverage.
cfg.min_quote_volume_24h = 50000.0
cfg.max_spread_bps = 120.0
cfg.min_top_of_book_quote = 5.0
cfg.min_depth_10bps_quote = 0.0
cfg.max_last_trade_age_sec = 3600.0
cfg.min_recent_trade_count = 40
cfg.min_candle_count = 220
cfg.min_candle_coverage_ratio = 0.9
cfg.max_zero_volume_fraction = 0.3
cfg.min_natr_bps = 12.0
cfg.max_natr_bps = 400.0

print("Screener config")
display(pd.Series(cfg.as_dict()).to_frame("value"))
print(f"Output root: {OUTPUT_ROOT}")

Screener config

                                                                                                                                         value
connector                                                                                                                               nonkyc
quote_asset                                                                                                                                  *
interval                                                                                                                                    5m
universe_top_k                                                                                                                            3000
final_top_n                                                                                                                                 15
candle_limit                                                                                                                               288
depth_limit                                                                                                                                200
recent_trade_limit                                                                                                                         500
request_pause_sec                                                                                                                          0.2
timeout_seconds                                                                                                                           30.0
max_retries                                                                                                                                  3
retry_backoff                                                                                                                              1.8
user_agent                                                                                                                pmm-lab-screener/0.1
min_quote_volume_24h                                                                                                                   50000.0
max_spread_bps                                                                                                                           120.0
min_top_of_book_quote                                                                                                                      5.0
min_depth_10bps_quote                                                                                                                      0.0
min_depth_50bps_quote                                                                                                                      0.0
min_depth_1xspread_quote                                                                                                                   0.0
max_last_trade_age_sec                                                                                                                  3600.0
min_recent_trade_count                                                                                                                      40
min_candle_count                                                                                                                           220
min_candle_coverage_ratio                                                                                                                  0.9
max_zero_volume_fraction                                                                                                                   0.3
min_natr_bps                                                                                                                              12.0
max_natr_bps                                                                                                                             400.0
natr_soft_min                                                                                                                              8.0
natr_target_min                                                                                                                           20.0
natr_target_max                                                                                                                          180.0
natr_soft_max                                                                                                                            350.0
efficiency_soft_min                                                                                                                        0.0
efficiency_target_min                                                                                                                     0.05
efficiency_target_max                                                                                                                     0.45
efficiency_soft_max                                                                                                                        0.8
vol_to_spread_soft_min                                                                                                                     1.0
vol_to_spread_target_min                                                                                                                   3.0
vol_to_spread_target_max                                                                                                                  25.0
vol_to_spread_soft_max                                                                                                                    60.0
exclude_regex                                                                             ((?:^|[^A-Z])(3L|3S|5L|5S)$, (?:UP|DOWN|BULL|BEAR)$)
include_symbols                                                                                                                             ()
exclude_symbols                                                                                                                             ()
score_weights              {'volume': 0.24, 'depth': 0.2, 'spread': 0.16, 'top_of_book': 0.08, 'activity': 0.12, 'quality': 0.1, 'alpha': 0.1}
selection_mode                                                                                                                          strict
fallback_if_empty                                                                                                                         True
interval_seconds                                                                                                                           300

Output root: /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635

## 2. Build the cheap universe snapshot

This step uses only batch endpoints to discover the broad market universe and assign a coarse score before any per-pair enrichment calls are made.

In [3]:
screener = NonKYCPublicScreener(cfg)

universe = screener.build_universe()
universe = compute_coarse_scores(universe)
shortlist = select_shortlist(universe, cfg)

summary = pd.DataFrame([
    {
        "connector": cfg.connector,
        "quote_asset": cfg.quote_asset,
        "interval": cfg.interval,
        "universe_rows": len(universe),
        "shortlist_rows": len(shortlist),
    }
])
display(summary)

preview_cols = [
    c for c in [
        "trading_pair",
        "exchange_symbol",
        "quote_volume_24h",
        "spread_bps",
        "coarse_score",
        "price_tick_estimate",
        "amount_step_estimate",
        "status_detail",
    ]
    if c in universe.columns
]

display(universe.loc[:, preview_cols].head(20))
print(f"Shortlist for detailed enrichment: {len(shortlist)}")
display(shortlist.loc[:, preview_cols].head(min(25, len(shortlist))))

  connector quote_asset interval  universe_rows  shortlist_rows
0    nonkyc           *       5m            345             345

   trading_pair exchange_symbol  quote_volume_24h  spread_bps  coarse_score  price_tick_estimate  amount_step_estimate status_detail
0      XMR-USDT        XMR/USDT      1.231704e+06    6.247676     79.069921         1.000000e-02              0.001000        active
1      LTC-USDT        LTC/USDT      5.395154e+05   16.560861     77.309306         1.000000e-02              0.000100        active
2     DOGE-USDT       DOGE/USDT      2.000480e+05   13.949246     76.817824         1.000000e-05              0.010000        active
3     NKYC-USDT       NKYC/USDT      1.592436e+05   13.261867     76.253242         1.000000e-06              0.000100        active
4      BTC-USDC        BTC/USDC      8.422135e+05   32.182250     76.033181         1.000000e-02              0.000001        active
5      BNB-USDT        BNB/USDT      1.165307e+06   34.956792     75.547928         1.000000e-02              0.000100        active
6      ETH-USDT        ETH/USDT      4.780444e+06   44.458961     75.162217         1.000000e-02              0.000010        active
7      SEI-USDT        SEI/USDT      9.096892e+04   18.709074     74.711925         1.000000e-04              0.010000        active
8     USDC-USDT       USDC/USDT      1.095369e+06   44.979759     74.292016         1.000000e-04              0.010000        active
9     SHIB-USDT       SHIB/USDT      1.694595e+05   33.277870     74.146580         1.000000e-09              1.000000        active
10     XRP-USDT        XRP/USDT      1.716454e+06   53.996080     73.687007         1.000000e-04              0.010000        active
11    LINK-USDT       LINK/USDT      6.826244e+05   46.136101     73.521358         1.000000e-02              0.010000        active
12    ALGO-USDT       ALGO/USDT      6.196891e+04   24.183797     72.938088         1.000000e-04              0.010000        active
13     UNI-USDT        UNI/USDT      1.716657e+05   43.060141     72.844012         1.000000e-03              0.010000        active
14    FUSD-USDT       FUSD/USDT      4.918995e+04   20.000000     72.652682         1.000000e-06              0.000100        active
15     POL-USDT        POL/USDT      6.601560e+04   32.137118     72.599034         1.000000e-04              0.010000        active
16    PEPE-USDT       PEPE/USDT      4.592812e+04   29.629630     71.456649         1.000000e-08              1.000000        active
17    MANA-USDT       MANA/USDT      6.868611e+04   38.764385     71.296466         1.000000e-05              0.010000        active
18     BTC-USDT        BTC/USDT      8.205776e+06   74.344495     71.008772         1.000000e-02              0.000001        active
19     SOL-USDT        SOL/USDT      1.464301e+06   70.284115     70.896008         1.000000e-02              0.010000        active

Shortlist for detailed enrichment: 345

   trading_pair exchange_symbol  quote_volume_24h  spread_bps  coarse_score  price_tick_estimate  amount_step_estimate status_detail
0      XMR-USDT        XMR/USDT      1.231704e+06    6.247676     79.069921         1.000000e-02              0.001000        active
1      LTC-USDT        LTC/USDT      5.395154e+05   16.560861     77.309306         1.000000e-02              0.000100        active
2     DOGE-USDT       DOGE/USDT      2.000480e+05   13.949246     76.817824         1.000000e-05              0.010000        active
3     NKYC-USDT       NKYC/USDT      1.592436e+05   13.261867     76.253242         1.000000e-06              0.000100        active
4      BTC-USDC        BTC/USDC      8.422135e+05   32.182250     76.033181         1.000000e-02              0.000001        active
5      BNB-USDT        BNB/USDT      1.165307e+06   34.956792     75.547928         1.000000e-02              0.000100        active
6      ETH-USDT        ETH/USDT      4.780444e+06   44.458961     75.162217         1.000000e-02              0.000010        active
7      SEI-USDT        SEI/USDT      9.096892e+04   18.709074     74.711925         1.000000e-04              0.010000        active
8     USDC-USDT       USDC/USDT      1.095369e+06   44.979759     74.292016         1.000000e-04              0.010000        active
9     SHIB-USDT       SHIB/USDT      1.694595e+05   33.277870     74.146580         1.000000e-09              1.000000        active
10     XRP-USDT        XRP/USDT      1.716454e+06   53.996080     73.687007         1.000000e-04              0.010000        active
11    LINK-USDT       LINK/USDT      6.826244e+05   46.136101     73.521358         1.000000e-02              0.010000        active
12    ALGO-USDT       ALGO/USDT      6.196891e+04   24.183797     72.938088         1.000000e-04              0.010000        active
13     UNI-USDT        UNI/USDT      1.716657e+05   43.060141     72.844012         1.000000e-03              0.010000        active
14    FUSD-USDT       FUSD/USDT      4.918995e+04   20.000000     72.652682         1.000000e-06              0.000100        active
15     POL-USDT        POL/USDT      6.601560e+04   32.137118     72.599034         1.000000e-04              0.010000        active
16    PEPE-USDT       PEPE/USDT      4.592812e+04   29.629630     71.456649         1.000000e-08              1.000000        active
17    MANA-USDT       MANA/USDT      6.868611e+04   38.764385     71.296466         1.000000e-05              0.010000        active
18     BTC-USDT        BTC/USDT      8.205776e+06   74.344495     71.008772         1.000000e-02              0.000001        active
19     SOL-USDT        SOL/USDT      1.464301e+06   70.284115     70.896008         1.000000e-02              0.010000        active
20    ARRR-USDT       ARRR/USDT      2.787100e+05   61.740253     70.836893         1.000000e-06              0.000100        active
21    AVAX-USDT       AVAX/USDT      3.294474e+05   67.873303     70.192220         1.000000e-02              0.010000        active
22     TRX-USDT        TRX/USDT      4.240028e+05   68.238213     70.059242         1.000000e-04              0.010000        active
23     BCH-USDT        BCH/USDT      6.846303e+05   72.503570     69.806509         1.000000e-01              0.000010        active
24    ALGO-USDC       ALGO/USDC      4.367206e+04   36.297641     69.748919         1.000000e-04              0.010000        active

## 3. Run the detailed screener

This step enriches the shortlist with order-book depth, recent trades, and candles, then applies hard gates plus the final PMM-oriented score.

In [4]:
run = screener.screen_from_universe(universe)
final_df = run.final.copy()
selected_df = run.selected.copy()

status_counts = pd.DataFrame([
    {
        "enriched_rows": len(final_df),
        "selected_rows": len(selected_df),
        "pass_rate": float(selected_df.shape[0] / final_df.shape[0]) if len(final_df) else 0.0,
    }
])
display(status_counts)

final_cols = [
    c for c in [
        "trading_pair",
        "screen_score",
        "passed_filters",
        "quote_volume_24h",
        "spread_bps",
        "top_of_book_quote",
        "sym_depth_quote_10bps",
        "recent_trade_count",
        "last_trade_age_sec",
        "n_candles",
        "coverage_ratio",
        "zero_volume_fraction",
        "natr_bps_mean",
        "efficiency_ratio",
        "rejection_reason",
    ]
    if c in final_df.columns
]
display(final_df.loc[:, final_cols].head(min(50, len(final_df))))

/opt/conda/envs/quants-lab/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py:3045: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

   enriched_rows  selected_rows  pass_rate
0            345              7    0.02029

,trading_pair,screen_score,passed_filters,quote_volume_24h,spread_bps,top_of_book_quote,sym_depth_quote_10bps,recent_trade_count,last_trade_age_sec,n_candles,coverage_ratio,zero_volume_fraction,natr_bps_mean,efficiency_ratio,rejection_reason
0,NKYC-USDT,89.810384,True,1.592436e+05,13.261867,97.288628,97.288628,200,8.615142,288,0.996540,0.000000,24.149011,0.033334,
1,TRX-USDT,89.244011,True,4.240028e+05,68.238213,1070.462358,0.000000,200,8.213220,288,0.989691,0.000000,20.809770,0.088571,
2,SOL-USDT,88.788668,True,1.464301e+06,70.284115,98.560800,0.000000,200,1.448521,288,0.996540,0.000000,26.642549,0.038040,
3,BNB-USDT,87.800989,True,1.165307e+06,34.956792,137.764432,0.000000,200,1.524300,288,1.000000,0.006944,20.790782,0.009099,
4,LTC-USDT,87.351500,True,5.395154e+05,16.560861,6.820080,6.820080,200,23.232283,288,0.996540,0.000000,18.663473,0.014512,
5,USDC-USDT,87.010777,True,1.095369e+06,44.979759,75.443148,0.000000,200,10.530616,288,0.979592,0.000000,14.696859,0.002457,
6,AAVE-USDT,82.785319,True,5.631383e+04,64.210365,390.417600,0.000000,200,313.381151,288,0.969697,0.000000,24.629778,0.035280,
7,XMR-USDT,93.519404,False,1.231704e+06,6.247676,1.008690,2.353650,200,7.770344,288,0.993103,0.000000,25.362196,0.070898,top_of_book_quote<5
8,BTC-USDT,88.850475,False,8.205776e+06,74.344495,2.443624,0.000000,200,0.878878,288,0.993103,0.000000,19.099589,0.056616,top_of_book_quote<5
9,BCH2-USDT,86.905446,False,1.108356e+04,11.736141,3.217374,4.573898,200,5.733006,288,0.993103,0.000000,66.993487,0.153997,quote_volume_24h<50000; top_of_book_quote<5
10,UNI-USDT,85.685079,False,1.716657e+05,43.060141,0.139640,0.000000,200,1.099779,288,0.993103,0.000000,26.533938,0.071480,top_of_book_quote<5
11,XRP-USDT,85.579740,False,1.716454e+06,41.395624,0.149116,0.000000,200,15.845647,288,0.993103,0.000000,26.058978,0.058370,top_of_book_quote<5
12,SHIB-USDT,85.475273,False,1.694595e+05,33.277870,0.170866,0.000000,200,17.808381,288,0.996540,0.000000,26.983194,0.092428,top_of_book_quote<5
13,BTC-USDC,84.161576,False,8.422135e+05,32.182250,0.607917,0.000000,200,4.899912,288,0.989691,0.003472,21.042028,0.044256,top_of_book_quote<5
14,DOGE-USDT,82.600400,False,2.000480e+05,13.949246,0.194913,0.194913,200,0.116419,288,0.986301,0.000000,28.492411,0.062383,top_of_book_quote<5
15,ARB-USDT,82.193253,False,5.486449e+04,65.430752,0.158240,0.000000,200,9.743950,288,0.972973,0.000000,23.343862,0.059649,top_of_book_quote<5
16,ETC-USDT,82.184986,False,4.183626e+04,48.661800,0.123600,0.000000,200,2.241557,288,0.996540,0.000000,23.606594,0.070313,quote_volume_24h<50000; top_of_book_quote<5
17,ZEPH-USDT,81.797419,False,1.206527e+04,11.387236,0.666046,0.666046,200,68.083404,288,0.996540,0.000000,40.716294,0.065532,quote_volume_24h<50000; top_of_book_quote<5
18,FF-USDT,81.632761,False,1.201413e+05,75.292805,0.173624,0.000000,200,12.541332,288,0.996540,0.000000,21.868552,0.053307,top_of_book_quote<5
19,BDX-USDT,81.293036,False,2.281516e+04,27.496563,7.491092,0.000000,200,0.310845,288,0.993103,0.000000,15.424799,0.008824,quote_volume_24h<50000
20,RENDER-USDT,80.060856,False,2.646053e+04,75.384169,0.171800,0.000000,200,22.932620,288,0.996540,0.000000,32.793661,0.048499,quote_volume_24h<50000; top_of_book_quote<5
21,LINK-USDT,79.839332,False,6.826244e+05,46.136101,0.434500,0.000000,200,8.773970,288,0.972973,0.000000,17.227943,0.067265,top_of_book_quote<5
22,POL-USDC,79.838293,False,1.601701e+04,42.872454,0.161755,0.000000,200,11.127719,288,0.982935,0.000000,22.054372,0.037594,quote_volume_24h<50000; top_of_book_quote<5
23,FUSD-USDT,78.590726,False,4.918995e+04,20.000000,558.766308,558.766308,200,49.068195,288,0.864865,0.000000,5.488233,0.000000,quote_volume_24h<50000; coverage_ratio<0.90; natr_bps_mean<12
24,AVAX-USDT,78.579436,False,3.294474e+05,67.873303,0.620900,0.000000,200,18.373488,288,0.986301,0.000000,17.660102,0.038961,top_of_book_quote<5
25,ZEC-USDT,78.356370,False,4.012725e+04,56.396025,0.763786,0.000000,200,156.429224,288,0.976271,0.006944,38.114353,0.081124,quote_volume_24h<50000; top_of_book_quote<5
26,ARB-USDC,78.244042,False,1.604737e+04,76.460950,0.158987,0.000000,200,20.979367,288,0.993103,0.000000,27.611171,0.056250,quote_volume_24h<50000; top_of_book_quote<5
27,W-USDT,78.150125,False,1.989364e+05,85.498191,0.170022,0.000000,200,18.873228,288,1.000000,0.000000,31.111903,0.047319,top_of_book_quote<5
28,IMX-USDT,78.041606,False,1.483480e+04,68.119891,0.157611,0.000000,200,18.547271,288,0.996540,0.000000,28.927346,0.037168,quote_volume_24h<50000; top_of_book_quote<5
29,ERG-USDT,77.746536,False,2.691976e+03,7.243752,0.520674,0.520674,200,55.629599,288,0.776280,0.000000,18.674133,0.049821,quote_volume_24h<50000; top_of_book_quote<5; coverage_ratio<0.90
30,XNV-USDT,77.438000,False,1.648807e+04,59.829126,3.283809,0.000000,200,13.534603,288,0.993103,0.000000,69.417633,0.010381,quote_volume_24h<50000; top_of_book_quote<5
31,ZSD-USDT,77.381548,False,6.652532e+03,17.852737,0.843797,0.843797,200,9.044990,288,0.982935,0.000000,31.784745,0.004222,quote_volume_24h<50000; top_of_book_quote<5
32,SOL-USDC,77.119245,False,2.190609e+04,92.695123,2009.227837,0.000000,200,25.756698,288,0.982935,0.000000,31.199615,0.036571,quote_volume_24h<50000
33,ADA-USDT,76.191815,False,6.193688e+03,56.818182,0.158144,0.000000,200,8.907092,288,0.996540,0.000000,24.955519,0.018541,quote_volume_24h<50000; top_of_book_quote<5
34,BNB-USDC,75.996764,False,4.642468e+04,112.539932,179.840600,0.000000,200,6.681145,288,0.956811,0.000000,57.924240,0.022103,quote_volume_24h<50000
35,DYDX-USDT,75.902631,False,2.486339e+04,20.512821,0.185060,0.000000,200,11.924091,288,0.976271,0.000000,30.490213,0.091358,quote_volume_24h<50000; top_of_book_quote<5
36,HACD-USDT,75.723117,False,3.064739e+03,7.549095,0.203882,0.203882,200,0.000000,288,0.993103,0.000000,27.572974,0.331812,quote_volume_24h<50000; top_of_book_quote<5
37,ENA-USDT,75.418082,False,3.229058e+04,120.021822,1563.145892,0.000000,200,4.382916,288,0.993103,0.000000,25.829866,0.026087,quote_volume_24h<50000; spread_bps>120
38,SHIB-USDC,75.408991,False,1.656298e+04,23.333722,0.175936,0.000000,200,0.595232,288,1.000000,0.000000,31.874328,0.086111,quote_volume_24h<50000; top_of_book_quote<5
39,POL-USDT,75.341383,False,6.601560e+04,32.137118,0.159885,0.000000,200,25.603607,288,0.993103,0.000000,19.881962,0.055319,top_of_book_quote<5
40,BELLS-USDT,75.093832,False,5.552516e+04,56.777134,0.556360,0.000000,200,23.155492,288,0.979592,0.000000,69.138086,0.003394,top_of_book_quote<5
41,APE-USDT,74.669229,False,9.912237e+03,70.093458,0.158056,0.000000,200,2.551515,288,0.979592,0.000000,31.375011,0.018568,quote_volume_24h<50000; top_of_book_quote<5
42,ETH-USDC,74.636029,False,9.501302e+03,28.874411,0.225473,0.000000,200,15.563023,288,0.996540,0.107639,29.626768,0.061614,quote_volume_24h<50000; top_of_book_quote<5
43,MANA-USDT,74.408823,False,6.868611e+04,38.764385,0.161284,0.000000,200,9.440337,288,0.996540,0.000000,30.116307,0.037286,top_of_book_quote<5
44,BCH-USDC,74.377137,False,6.551885e+04,131.297743,267.399800,0.000000,200,54.264227,288,0.986301,0.000000,33.366004,0.124218,spread_bps>120
45,ONDO-USDT,74.275791,False,1.198845e+05,58.476265,0.176682,0.000000,200,5.500614,288,0.996540,0.000000,30.662053,0.019403,top_of_book_quote<5
46,SCASH-USDT,74.195736,False,6.427697e+03,34.024106,0.559506,0.000000,200,18.763928,288,0.947368,0.000000,55.024639,0.016391,quote_volume_24h<50000; top_of_book_quote<5
47,ARRR-USDT,74.129063,False,2.787100e+05,61.740253,0.268963,0.000000,200,52.586279,288,0.993103,0.000000,78.745033,0.025074,top_of_book_quote<5
48,SUN-USDT,74.054742,False,5.465339e+04,105.752839,0.168741,0.000000,200,9.892972,288,0.986301,0.000000,26.465316,0.035579,top_of_book_quote<5
49,XLM-USDT,73.875184,False,9.099764e+04,88.783664,0.151033,0.000000,200,17.740552,288,0.963211,0.000000,21.096262,0.011765,top_of_book_quote<5

## 4. Diagnostics

Inspect which pairs passed, which pairs failed, and why. Rejection counts are often more useful than raw rankings because they show whether you are liquidity-bound, spread-bound, or data-quality-bound.

In [5]:
if final_df.empty:
    print("No enriched rows returned.")
else:
    passed = final_df[final_df["passed_filters"]].copy()
    rejected = final_df[~final_df["passed_filters"]].copy()

    print(f"Passed: {{len(passed)}} | Rejected: {{len(rejected)}}")

    if not passed.empty:
        display(
            passed.loc[:, [
                c for c in [
                    "trading_pair",
                    "screen_score",
                    "quote_volume_24h",
                    "spread_bps",
                    "top_of_book_quote",
                    "sym_depth_quote_10bps",
                    "recent_trade_count",
                    "last_trade_age_sec",
                    "natr_bps_mean",
                    "efficiency_ratio",
                ] if c in passed.columns
            ]].head(cfg.final_top_n)
        )

    if not rejected.empty:
        reject_counts = (
            rejected["rejection_reason"]
            .fillna("")
            .str.split("; ")
            .explode()
            .loc[lambda s: s.ne("")]
            .value_counts()
            .rename_axis("rejection_reason")
            .to_frame("count")
        )
        display(reject_counts.head(20))

Passed: {len(passed)} | Rejected: {len(rejected)}

,trading_pair,screen_score,quote_volume_24h,spread_bps,top_of_book_quote,sym_depth_quote_10bps,recent_trade_count,last_trade_age_sec,natr_bps_mean,efficiency_ratio
0,NKYC-USDT,89.810384,1.592436e+05,13.261867,97.288628,97.288628,200,8.615142,24.149011,0.033334
1,TRX-USDT,89.244011,4.240028e+05,68.238213,1070.462358,0.000000,200,8.213220,20.809770,0.088571
2,SOL-USDT,88.788668,1.464301e+06,70.284115,98.560800,0.000000,200,1.448521,26.642549,0.038040
3,BNB-USDT,87.800989,1.165307e+06,34.956792,137.764432,0.000000,200,1.524300,20.790782,0.009099
4,LTC-USDT,87.351500,5.395154e+05,16.560861,6.820080,6.820080,200,23.232283,18.663473,0.014512
5,USDC-USDT,87.010777,1.095369e+06,44.979759,75.443148,0.000000,200,10.530616,14.696859,0.002457
6,AAVE-USDT,82.785319,5.631383e+04,64.210365,390.417600,0.000000,200,313.381151,24.629778,0.035280

                              count
rejection_reason
top_of_book_quote<5             309
quote_volume_24h<50000          309
coverage_ratio<0.90             200
natr_bps_mean<12                 48
spread_bps>120                   40
last_trade_age_sec>3600           7
zero_volume_fraction>0.30         3
missing_spread_bps                3
missing_top_of_book_quote         3
missing_last_trade_age_sec        3
recent_trade_count<40             3
n_candles<220                     3
missing_coverage_ratio            3
missing_zero_volume_fraction      3
missing_natr_bps_mean             3
natr_bps_mean>400                 2

## 5. Export artifacts

This writes CSV, JSON, a Markdown report, a candle-ingestor manifest, and an exchange-rules patch for the selected pairs.

In [6]:
artifact_paths = export_screening_artifacts(
    run,
    output_dir=str(OUTPUT_ROOT),
    base_url=NONKYC_BASE_URL,
    trade_limit=cfg.recent_trade_limit,
)

print("Artifacts written")
display(pd.Series(asdict(artifact_paths)).to_frame("path"))

Artifacts written

                                                                                                                                                  path
root_dir                                               /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635
universe_csv                              /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/universe.csv
shortlist_csv                            /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/shortlist.csv
final_csv                             /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/final_screen.csv
selected_csv                        /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/selected_pairs.csv
selected_pairs_txt                  /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/selected_pairs.txt
selected_pairs_json                /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/selected_pairs.json
symbol_metadata_json              /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/symbol_metadata.json
candle_ingestor_manifest_yaml  /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/candle_ingestor_mani...
exchange_rules_patch_yaml      /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/exchange_rules_patch...
screening_report_md                /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/screening_report.md
run_metadata_json                    /quants-lab/research_notebooks/market_lab/pmm_dynamic/artifacts/screener/nonkyc/20260330_053635/run_metadata.json

## 6. Merge into candle ingestion

The manifest below follows the same `exchanges -> pairs -> intervals` structure already used by your candle-ingest and candle-gap-repair tooling, with slash-formatted exchange pairs and Hummingbot-normalized selected pair files alongside it.

In [7]:
from pathlib import Path

print("Selected Hummingbot pairs")
print("-" * 80)
print(Path(artifact_paths.selected_pairs_txt).read_text())

print("\nCandle ingestor manifest")
print("-" * 80)
print(Path(artifact_paths.candle_ingestor_manifest_yaml).read_text())

print("\nExchange rules patch (estimates only)")
print("-" * 80)
print(Path(artifact_paths.exchange_rules_patch_yaml).read_text())

Selected Hummingbot pairs
--------------------------------------------------------------------------------
NKYC-USDT
TRX-USDT
SOL-USDT
BNB-USDT
LTC-USDT
USDC-USDT
AAVE-USDT


Candle ingestor manifest
--------------------------------------------------------------------------------
backfill_days: 180
request_delay: 0.5
overlap_candles: 2
include_open_candle: false
http:
  timeout_seconds: 30.0
  max_retries: 3
  retry_backoff: 1.8
  user_agent: pmm-lab-screener/0.1
exchanges:
  nonkyc:
    enabled: true
    base_url: https://api.nonkyc.io/api/v2
    pairs:
    - NKYC/USDT
    - TRX/USDT
    - SOL/USDT
    - BNB/USDT
    - LTC/USDT
    - USDC/USDT
    - AAVE/USDT
    intervals:
    - 5m
    trades:
      enabled: true
      limit: 500
      update_recent_candles: false
      recent_window_minutes: 120


Exchange rules patch (estimates only)
--------------------------------------------------------------------------------
connectors:
  nonkyc:
    pairs:
      NKYC-USDT:
        price_tick: 1.0e-06
        amount_step: 0.0001
      TRX-USDT:
        price_tick: 0.0001
        amount_step: 0.01
      SOL-USDT:
        price_tick: 0.01
        amount_step: 0.01
      BNB-USDT:
        price_tick: 0.01
        amount_step: 0.0001
      LTC-USDT:
        price_tick: 0.01
        amount_step: 0.0001
      USDC-USDT:
        price_tick: 0.0001
        amount_step: 0.01
      AAVE-USDT:
        price_tick: 0.01
        amount_step: 0.001