# Crypto oscillator finder — KRAKEN v9 (`recycle_v11` engine)

**v11.1** adds: a dust filter (`min_vol_usd`), quote-unit conversion for crypto-quoted
pairs (fund / min-order / volume-cap all in the pair's quote currency; exports carry both
`max_fund_value_quote` in quote units and `max_fund_value_usd`), finalize reusing the same
order-book snapshot the engine already sampled (no spurious spread gates), the
`rc_gate_two_sided_mode` holdout waiver, and a book-verification cell (Cell 10).

**What changed vs v10** (full details in `LadderLab_v11_notes_claude_code.md`):

1. **True holdout** — the deploy ladder is fitted *without* the last 15 days; the fitted,
   train-anchored ladder is scored once on that unseen tail. `holdout_edge_pct` is the only
   fully out-of-sample number for the geometry you deploy, and it gates deployment.
2. **Clean-block gating** — the 180d frozen report tags blocks that overlap the fit window
   (`in_fit`); the band-aware v10 gates must now pass on the *clean* blocks too.
3. **Fill realism** — fills require price to trade *through* the rung
   (`rc_fill_penetration_pct` + 1 tick), and per-bar filled notional is capped at
   `rc_volume_cap_frac` × the bar's quote volume, with partial fills (bars now carry volume).
4. **Slip symmetry** — the measured live order-book half-spread joins Roll + floor in the
   *search and WF*, not just as a finalize gate.
5. **Grid-harvest screen** — a model-free zig-zag swing count (net of round-trip cost) ranks
   the review set; it cannot overfit because nothing is fitted.
6. **Deep history** — MEXC-first Nx6 (with volume) history; Kraken USD pairs get months of hourly/5m depth via the price-guarded MEXC USDT-alias proxy (Kraken-native OHLC caps at 720 candles ≈ 30d of 1h, kept only as a fallback).

Nothing was removed from the v10 reports — v11 only adds columns/files. The
`*_copy_paste_ladders.md` is rendered by v10's renderer, byte-identical format.

In [1]:
# ── Cell 1: bootstrap ────────────────────────────────────────────────
# numba makes the engine ~50-100x faster; strongly recommended.
import sys, subprocess
for _mod, _pkg in (('numba', 'numba'), ('tabulate', 'tabulate')):
    try:
        __import__(_mod)
    except ImportError:
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', _pkg], check=False)

import importlib, os, time, json
from pathlib import Path
import numpy as np
import pandas as pd

import ladder_lab as ll
import ladder_lab_recycle as lr10          # v10 stays installed; v11 reuses it
import ladder_lab_recycle_v11 as lr
importlib.reload(ll); importlib.reload(lr10); importlib.reload(lr)

EXCHANGE = 'kraken'

print(f'ladder_lab {ll.__version__} | v10 {lr10.__version__} | v11 {lr.__version__} | numba={ll.HAVE_NUMBA}')
assert ll.parity_check(), 'base kernel parity FAILED'
assert lr10.recycle_parity_check(), 'v10 kernel parity FAILED'
assert lr.recycle_v11_parity_check(verbose=True), 'v11 kernel parity / v10-equivalence FAILED'
print('kernel parity OK (v11 reproduces v10 exactly with realism features off)')

CFG = lr.recycle_default_config(EXCHANGE)
# ---- knobs you will most likely touch ----
CFG['always_review_markets'] = ('XMR/USD', 'XMR/USDT', 'DASH/USD')
CFG['focus_markets']         = ()
CFG['rc_top_n_from_screen']  = 40      # markets from the screener that get the full engine
CFG['rc_n_candidates']       = 240     # per fit; drop to ~80 if running without numba
CFG['rc_target_trades_per_15d'] = 40   # recalibrate with the diagnostic-JSONL cell at the bottom
CFG['rc_report_interval']    = '5m'    # frozen reports / YAML eval / holdout on 5m bars
# ---- v11 realism knobs (defaults are the recommended settings) ----
CFG['rc_holdout_days']         = 15    # fit never sees the last N days (0 disables; don't)
CFG['rc_fill_penetration_pct'] = 0.0005  # price must trade 5bps+1tick THROUGH a rung to fill
CFG['rc_volume_cap_frac']      = 0.25  # max share of a bar's quote volume we may fill
CFG['rc_book_spread_in_slip']  = True  # live half-spread joins Roll+floor in search/WF too
# ---- v11.1 knobs ----
CFG['min_vol_usd']             = 10_000  # DUST FILTER: drop markets under this 24h USD volume
                                         # (the first run spent ~90% of engine time on books
                                         #  that could not absorb even the $200 fund floor)
CFG['rc_gate_two_sided_mode']  = 'either'  # 'blocks'=v10 | 'holdout' | 'either' (waive the
                                         # block two-sided gate when the HOLDOUT was two-sided;
                                         # re-anchored ladders are structurally one-sided vs a
                                         # trending past -- the holdout has no such bias)
# CFG['rc_v11_fill_model'] = False     # A/B: byte-identical v10 fills (leave True to deploy)

# Where your live controller YAMLs live (searched recursively):
YAML_ROOTS = ['.', 'controllers', str(Path.home())]
YAML_ROOTS = ['./controllers/kraken']

# artifacts/{exchange}/{timestamp}/files
RUN_TS = time.strftime('%Y%m%d-%H%M%S')
ART = Path('artifacts') / EXCHANGE / RUN_TS / 'files'
ART.mkdir(parents=True, exist_ok=True)
PREFIX = str(ART / f'KRAKEN_recycle_v9')
print('artifacts →', ART)

ladder_lab 1.0.0 | v10 10.2.0-recycle-rollspread-bandgates | v11 11.3.1-resilient-universe | numba=True
  series 0: v10-equiv=OK trades=20
  series 1: v10-equiv=OK trades=27
  series 2: v10-equiv=OK trades=18
  series 3: v10-equiv=OK trades=17
kernel parity OK (v11 reproduces v10 exactly with realism features off)
artifacts → artifacts/kraken/20260713-040411/files

In [2]:
# ── Cell 2: universe ─────────────────────────────────────────────────
# v11.1.3: build the universe WITHOUT the volume floor so live-YAML and
# always-review markets can never be starved of history (a live ZANO ladder
# was silently dropped when its 24h volume dipped under the floor). The dust
# filter is applied in Cell 4 to the SCREENED candidates only -- engine time
# is still protected, your own markets always get evaluated.
# v11.3.1: patient retries (15/30/45/60s -- outlasts a rate-limit window)
# and a loud fallback to the last good universe cached on disk (<=48h old),
# so a flaky /market/getlist costs freshness, not the whole run.
uni = lr.build_universe(EXCHANGE, CFG)
VOL_USD = dict(zip(uni['df'].pairkey, uni['df'].vol_usd))
cache = ll.CandleCache(CFG['cache_dir'], CFG['cache_ttl_hours'])

1513 kraken markets across 23 quote(s) >= $0 24h vol (USD-equiv).
  by quote: USD:691, EUR:584, USDT:49, USDC:47, XBT:32, GBP:27, ETH:19, AUD:14, CAD:11, JPY:10, CHF:6, USD1:3, EURC:3, SOL:3, FIDD:2, DAI:2, AUSD:2, PYUSD:2, EUROP:2, RLUSD:1, USDQ:1, USDD:1, USDR:1

In [3]:
# ── Cell 3: daily history + screener (breadth pass, unchanged from base) ──
hist_d = ll.prefetch_history(uni, CFG, cache)
screen_df = ll.screen(uni, hist_d, CFG)
screen_df = lr.drop_stable_stable(screen_df, CFG)
screen_df.head(25)

  ...MEXC pass 50/1513
  ...MEXC pass 100/1513
  ...MEXC pass 150/1513
  ...MEXC pass 200/1513
  ...MEXC pass 250/1513
  ...MEXC pass 300/1513
  ...MEXC pass 350/1513
  ...MEXC pass 400/1513
  ...MEXC pass 450/1513
  ...MEXC pass 500/1513
  ...MEXC pass 550/1513
  ...MEXC pass 600/1513
  ...MEXC pass 650/1513
  ...MEXC pass 700/1513
  ...MEXC pass 750/1513
  ...MEXC pass 800/1513
  ...MEXC pass 850/1513
  ...MEXC pass 900/1513
  ...MEXC pass 950/1513
  ...MEXC pass 1000/1513
  ...MEXC pass 1050/1513
  ...MEXC pass 1100/1513
  ...MEXC pass 1150/1513
  ...MEXC pass 1200/1513
  ...MEXC pass 1250/1513
  ...MEXC pass 1300/1513
  ...MEXC pass 1350/1513
  ...MEXC pass 1400/1513
  ...MEXC pass 1450/1513
  ...MEXC pass 1500/1513
  native fallback for 1412 markets (serial ~1/s) ...
  ...native 25/1412
  ...native 50/1412
  ...native 75/1412
  ...native 100/1412
  ...native 125/1412
  ...native 150/1412
  ...native 175/1412
  ...native 200/1412
  ...native 225/1412
  ...native 250/1412
  ...native 275/1412
  ...native 300/1412
  ...native 325/1412
  ...native 350/1412
  ...native 375/1412
  ...native 400/1412
  ...native 425/1412
  ...native 450/1412
  ...native 475/1412
  ...native 500/1412
  ...native 525/1412
  ...native 550/1412
  ...native 575/1412
  ...native 600/1412
  ...native 625/1412
  ...native 650/1412
  ...native 675/1412
  ...native 700/1412
  ...native 725/1412
  ...native 750/1412
  ...native 775/1412
  ...native 800/1412
  ...native 825/1412
  ...native 850/1412
  ...native 875/1412
  ...native 900/1412
  ...native 925/1412
  ...native 950/1412
  ...native 975/1412
  ...native 1000/1412
  ...native 1025/1412
  ...native 1050/1412
  ...native 1075/1412
  ...native 1100/1412
  ...native 1125/1412
  ...native 1150/1412
  ...native 1175/1412
  ...native 1200/1412
  ...native 1225/1412
  ...native 1250/1412
  ...native 1275/1412
  ...native 1300/1412
  ...native 1325/1412
  ...native 1350/1412
  ...native 1375/1412
  ...native 1400/1412
history: 1456/1513 markets in 876s (MEXC 101, native 1355, missing 57)
  dropped 17 stable/stable pairs from consideration

,days,price,low,high,ann_vol,er,cross_per_yr,in_band,net_return,cur_vs_high,...,coin,quote,src,vol_usd,min_qty,stale,tier,range_x,qualifies,composite
0,202,2.735000e-04,2.510750e-04,2.779000e-04,1.960575,0.002576,77.698020,0.648515,0.020522,0.526063,...,COPM,USD,Kraken,5.200648,1.800000e+04,False,full,1.11,True,0.995
1,220,6.340000e-01,6.445000e-01,9.256000e-01,1.527115,0.042687,77.977273,0.618182,-0.366000,0.604385,...,REP,EUR,Kraken,4.187925,5.000000e+00,False,full,1.44,True,0.979
2,220,7.890000e-01,7.355000e-01,1.137050e+00,1.569286,0.034396,97.886364,0.609091,-0.327366,0.665261,...,REP,USD,Kraken,21.667626,5.000000e+00,False,full,1.55,True,0.978
3,187,9.985000e-01,9.985000e-01,9.998000e-01,2.594340,0.000268,46.844920,0.973262,-0.001500,0.269866,...,FRNT,USD,Kraken,4.992500,5.000000e+00,False,full,1.00,True,0.977
4,158,2.709000e-03,2.506500e-03,7.299800e-03,3.535260,0.089982,62.373418,0.594937,-0.735527,0.209561,...,SUP,USD,Kraken,39287.474016,1.700000e+03,False,full,2.91,True,0.976
5,125,3.338000e-01,3.351200e-01,4.805600e-01,1.829569,0.056710,52.560000,0.608000,-0.309475,0.667600,...,WFB,USD,Kraken,47.239530,1.200000e+01,False,young,1.43,True,0.969
6,172,4.384000e-02,4.384000e-02,8.135750e-02,2.479959,0.196344,106.104651,0.593023,-0.489877,0.509294,...,BDX,USD,Kraken,0.000000,6.000000e+01,False,full,1.86,True,0.967
7,116,6.240000e-04,5.082500e-04,9.025000e-04,2.211438,0.155854,59.784483,0.603448,-0.572603,0.427397,...,SHAPE,USD,Kraken,5826.648369,7.800000e+03,False,young,1.78,True,0.965
8,220,6.720000e-07,5.956000e-07,9.330500e-07,1.833024,0.005343,89.590909,0.600000,-0.088195,0.622222,...,KIN,USD,Kraken,321.119767,7.000000e+06,False,full,1.57,True,0.964
9,164,6.329000e-03,6.310300e-03,1.191445e-02,1.736829,0.126340,75.670732,0.597561,-0.646088,0.353912,...,INX,EUR,Kraken,2424.538657,6.000000e+02,False,full,1.89,True,0.960
10,220,8.970000e-02,6.020000e-02,1.199200e-01,2.625022,0.029099,59.727273,0.600000,-0.365629,0.223357,...,LIT,EUR,Kraken,271.383727,7.000000e+01,False,full,1.99,True,0.959
11,145,5.622000e-02,5.622600e-02,1.367880e-01,1.884157,0.100025,73.000000,0.600000,-0.627435,0.355620,...,PEPECOIN,USD,Kraken,1325.913000,9.000000e+01,False,young,2.43,True,0.958
12,164,7.183000e-03,7.180450e-03,1.412100e-02,1.745144,0.129148,71.219512,0.597561,-0.660843,0.339157,...,INX,USD,Kraken,7218.018444,6.000000e+02,False,full,1.97,True,0.958
13,220,4.350000e-06,4.219000e-06,1.326550e-05,3.282616,0.064296,58.068182,0.604545,-0.674645,0.163166,...,WEN,USD,Kraken,1.618573,1.000000e+06,False,full,3.14,True,0.958
14,220,1.949600e+03,1.696765e+03,3.554725e+03,2.073170,0.038853,81.295455,0.600000,-0.394985,0.511223,...,LSETH,USD,Kraken,80.010122,2.500000e-03,False,full,2.10,True,0.956
15,220,2.457000e-02,1.505700e-02,2.886250e-02,1.610001,0.036031,114.477273,0.600000,0.727848,0.780000,...,MNGO,EUR,Kraken,5.259012,1.700000e+02,False,full,1.92,True,0.955
16,220,5.770000e-03,3.845500e-03,8.853000e-03,3.144779,0.047798,48.113636,0.600000,-0.480180,0.496985,...,SRM,EUR,Kraken,176.450784,6.000000e+02,False,full,2.30,True,0.954
17,220,1.300000e+00,1.202300e+00,1.377400e+00,3.250851,0.006607,36.500000,0.618182,0.041500,0.541667,...,JITOSOL,SOL,Kraken,3.720565,5.000000e-02,False,full,1.15,True,0.952
18,220,7.490000e-03,4.980000e-03,1.071200e-02,1.949617,0.029072,54.750000,0.600000,-0.294062,0.643471,...,AVAAI,USD,Kraken,376.444404,1.000000e+03,False,full,2.15,True,0.951
19,220,3.420000e-02,3.139500e-02,8.200000e-02,2.269198,0.043245,59.727273,0.600000,-0.497059,0.322642,...,ALTHEA,EUR,Kraken,63.417436,1.300000e+02,False,full,2.61,True,0.949
20,220,1.888600e-01,7.518000e-02,1.926020e-01,4.471945,0.045574,41.477273,0.604545,0.696855,0.637481,...,APR,EUR,Kraken,1206.472599,2.500000e+01,False,full,2.56,True,0.949
21,220,2.701000e-02,1.780600e-02,3.391500e-02,1.526151,0.036045,114.477273,0.600000,0.532917,0.738988,...,MNGO,USD,Kraken,456.156162,1.700000e+02,False,full,1.90,True,0.949
22,220,2.401000e-02,2.332000e-02,7.156150e-02,3.089881,0.109080,49.772727,0.600000,-0.713484,0.281279,...,CORN,USD,Kraken,0.000000,1.400000e+02,False,full,3.07,True,0.948
23,220,1.079000e+00,1.055195e+00,1.154900e+00,0.610385,0.000898,117.795455,0.600000,0.003628,0.902929,...,LSETH,ETH,Kraken,9.773784,2.500000e-03,False,full,1.09,True,0.948
24,220,5.390000e-07,5.079000e-07,7.776000e-07,1.711373,0.011901,61.386364,0.609091,-0.170769,0.544995,...,KIN,EUR,Kraken,58.251273,7.000000e+06,False,full,1.53,True,0.946

In [4]:
# ── Cell 4: pick the markets that get the full engine ────────────────
# v11: the model-free grid-harvest rank (zig-zag swings net of round-trip cost)
# is blended with the base composite. harvest_* columns are on DAILY bars here
# (breadth); the engine recomputes them on intraday bars for the finalists.
yamls = lr.discover_controller_yamls(YAML_ROOTS, exchange=EXCHANGE)
yamls = lr.discover_controller_yamls(YAML_ROOTS,
                                     pattern='*range_inventory_ladder*.y*ml',
                                     exchange=EXCHANGE)
yaml_markets = [lr._pair_key(p['trading_pair']) for p in yamls]
print(f'controller YAMLs found: {len(yamls)} → {yaml_markets}')

ranked = lr.rank_review_markets(screen_df, hist_d, CFG)
display(ranked.head(25))

col = 'base' if 'base' in ranked.columns else 'pairkey'
# dust filter applies HERE (screened candidates only); YAML/always/focus bypass
eligible = [pk for pk in ranked[col] if VOL_USD.get(pk, 0) >= CFG['min_vol_usd']]
dropped = len(ranked) - len(eligible)
if dropped:
    print(f'dust filter: {dropped} screened markets under ${CFG["min_vol_usd"]:,.0f} 24h volume')
top_screen = eligible[:CFG['rc_top_n_from_screen']]
wanted = lr.merge_unique_markets(top_screen, CFG['always_review_markets'],
                                 CFG['focus_markets'], yaml_markets)
review, missing = lr.resolve_present(uni, wanted)
if missing:
    print('not on this exchange / below volume floor:', missing)
print(f'{len(review)} markets selected for the v11 engine')

controller YAMLs found: 2 → ['DASH/EUR', 'XMR/USD']

,base,days,price,low,high,ann_vol,er,cross_per_yr,in_band,net_return,...,range_x,qualifies,composite,harvest_rt_cost_pct,harvest_1.5x_pct_mo,harvest_2x_pct_mo,harvest_3x_pct_mo,harvest_best_pct_mo,harvest_best_gap_pct,review_rank
0,SUP/USD,158,2.709000e-03,2.506500e-03,7.299800e-03,3.535260,0.089982,62.373418,0.594937,-0.735527,...,2.91,True,0.976,12.500,15.127,24.204,19.363,24.204,25.000,0.995
1,CORN/USD,220,2.401000e-02,2.332000e-02,7.156150e-02,3.089881,0.109080,49.772727,0.600000,-0.713484,...,3.07,True,0.948,11.774,7.577,14.433,18.763,18.763,35.323,0.980
2,SUP/EUR,158,2.719000e-03,2.719000e-03,6.030000e-03,3.929752,0.080275,36.962025,0.715190,-0.682582,...,2.22,True,0.919,12.500,7.261,14.522,19.363,19.363,37.500,0.974
3,ELX/EUR,220,1.313000e-03,8.599500e-04,3.624800e-03,3.363477,0.121512,49.772727,0.609091,-0.815070,...,4.22,True,0.932,12.500,8.427,14.556,18.387,18.387,37.500,0.974
4,UNFI/EUR,220,3.140000e-02,2.149500e-02,9.430000e-02,3.259070,0.046290,36.500000,0.600000,-0.600000,...,4.39,True,0.903,12.500,8.427,12.258,21.452,21.452,37.500,0.973
5,TEER/USD,220,8.110000e-03,8.110000e-03,1.961000e-02,2.472238,0.102744,36.500000,0.772727,-0.654894,...,2.42,True,0.915,11.060,9.830,16.947,18.981,18.981,33.181,0.972
6,SRM/EUR,220,5.770000e-03,3.845500e-03,8.853000e-03,3.144779,0.047798,48.113636,0.600000,-0.480180,...,2.30,True,0.954,12.500,9.577,16.089,13.790,16.089,25.000,0.969
7,BILLY/EUR,220,1.414000e-03,1.314000e-03,2.962600e-03,1.913963,0.052594,66.363636,0.600000,-0.533795,...,2.25,True,0.925,12.105,13.355,15.581,17.806,17.806,36.316,0.969
8,GHIBLI/EUR,220,2.550000e-04,2.498500e-04,7.700500e-04,2.049281,0.038210,77.977273,0.600000,-0.543828,...,3.08,True,0.913,12.500,10.726,14.556,18.387,18.387,37.500,0.969
9,RAILS/EUR,159,5.262000e-02,4.511400e-02,2.468400e-01,3.081792,0.166257,41.320755,0.597484,-0.850977,...,5.47,True,0.887,12.500,13.829,18.038,21.646,21.646,37.500,0.968
10,ARC/EUR,220,6.957000e-02,3.019700e-02,7.385250e-02,2.180865,0.043932,53.090909,0.600000,1.076716,...,2.45,True,0.921,6.155,9.054,15.845,17.354,17.354,18.466,0.966
11,FOREST/USD,220,2.239000e-02,1.735000e-02,8.380950e-02,3.801294,0.026127,58.068182,0.600000,-0.506284,...,4.83,True,0.882,10.044,8.003,13.544,22.162,22.162,30.133,0.966
12,SPACE/USD,171,6.153000e-03,5.182000e-03,1.092500e-02,2.057499,0.129577,51.228070,0.602339,-0.656909,...,2.11,True,0.911,7.188,8.355,12.854,17.996,17.996,21.565,0.966
13,ELX/USD,220,1.527000e-03,1.021500e-03,4.313800e-03,3.194616,0.135014,39.818182,0.600000,-0.816024,...,4.22,True,0.898,12.500,8.044,11.492,18.387,18.387,37.500,0.963
14,AVAAI/USD,220,7.490000e-03,4.980000e-03,1.071200e-02,1.949617,0.029072,54.750000,0.600000,-0.294062,...,2.15,True,0.951,9.652,9.761,14.790,15.381,15.381,28.957,0.963
15,SPACE/EUR,171,5.452000e-03,4.373500e-03,9.181000e-03,2.040884,0.126099,46.959064,0.602339,-0.640701,...,2.10,True,0.903,7.134,8.930,14.033,17.861,17.861,21.403,0.962
16,PEPECOIN/USD,145,5.622000e-02,5.622600e-02,1.367880e-01,1.884157,0.100025,73.000000,0.600000,-0.627435,...,2.43,True,0.958,11.934,10.078,15.117,12.597,15.117,23.869,0.961
17,CHEEMS/EUR,220,4.020000e-07,3.871400e-07,9.246850e-07,1.910777,0.073229,59.727273,0.600000,-0.602610,...,2.39,True,0.923,7.697,11.794,16.040,15.097,16.040,15.395,0.959
18,REPPO/USD,81,2.886300e-02,1.400000e-02,2.886300e-02,2.465942,0.065978,54.074074,0.604938,0.670893,...,2.06,True,0.850,6.464,13.511,19.652,39.304,39.304,19.393,0.959
19,ANLOG/EUR,220,1.310000e-04,1.310000e-04,6.655000e-04,5.108383,0.080140,26.545455,0.790909,-0.813390,...,5.08,True,0.853,12.500,13.184,20.163,24.816,24.816,37.500,0.958
20,UAI/EUR,220,3.001900e-01,1.199670e-01,3.201790e-01,2.019865,0.052424,43.136364,0.600000,1.539679,...,2.67,True,0.876,10.782,8.921,13.217,18.504,18.504,32.346,0.956
21,REP/EUR,220,6.340000e-01,6.445000e-01,9.256000e-01,1.527115,0.042687,77.977273,0.618182,-0.366000,...,1.44,True,0.979,9.097,9.757,13.939,7.806,13.939,18.194,0.956
22,ARC/USD,220,7.804000e-02,3.471900e-02,8.365550e-02,2.088341,0.044314,43.136364,0.600000,0.937438,...,2.41,True,0.891,6.387,9.200,13.311,17.225,17.225,19.162,0.954
23,L3/USD,220,5.432000e-03,5.726800e-03,1.461200e-02,2.151859,0.041329,43.136364,0.604545,-0.554754,...,2.55,True,0.900,12.500,11.109,16.089,13.790,16.089,25.000,0.952
24,SHAPE/USD,116,6.240000e-04,5.082500e-04,9.025000e-04,2.211438,0.155854,59.784483,0.603448,-0.572603,...,1.78,True,0.965,8.721,6.340,12.679,13.832,13.832,26.163,0.952

dust filter: 940 screened markets under $10,000 24h volume
44 markets selected for the v11 engine

In [5]:
# ── Cell 5: history — hourly Nx6 for search/WF/holdout, 5m Nx6 for reports ─
# v11 bars carry QUOTE VOLUME (column 6) so the sim can cap fills against what
# actually traded. Kraken pairs ride the MEXC proxy (USD→USDT alias, guarded by
# the last-price check); Kraken-native OHLC is a 30d fallback (720-candle cap).
hist_h = lr.prefetch_bars6(uni, CFG, cache, pairs=review, interval='60m',
                           min_days_key='rc_min_hourly_days')
hist_h = lr.with_daily_fallback(hist_h, hist_d, CFG, review)   # daily fallback is flagged
print(pd.Series({pk: v['granularity'] for pk, v in hist_h.items()}).value_counts().to_string())
vol_missing = [pk for pk, v in hist_h.items() if not v.get('vol_known', False)]
if vol_missing:
    print('volume unknown (volume cap disabled) for:', vol_missing)

if CFG['rc_report_interval'] not in ('60m', '1h'):
    hist_report = lr.prefetch_bars6(uni, CFG, cache, pairs=review,
                                    interval=CFG['rc_report_interval'],
                                    min_days_key='rc_min_intraday_days')
    print(pd.Series({pk: v['granularity'] for pk, v in hist_report.items()}).value_counts().to_string())
else:
    hist_report = hist_h
missing_5m = [pk for pk in review if pk in hist_h and pk not in hist_report]
if missing_5m:
    print('report falls back to search-granularity bars for:', missing_5m)

  ...bars6[60m] 10/44
  ...bars6[60m] 20/44
  ...bars6[60m] 30/44
  ...bars6[60m] 40/44
bars6(60m): 25/44 markets in 35s
1h    25
1d    19
volume unknown (volume cap disabled) for: ['SUP/USD', 'REPPO/USD', 'UAI/EUR', 'AI/USD', 'UNFI/USD', 'UAI/USD', 'BMB/USD', 'BASED/USD', 'REPPO/EUR', 'ZAMA/USD', 'VELVET/USD', 'LIT/USD', 'NIL/EUR', 'XPL/EUR', 'BLUAI/EUR', 'HMSTR/EUR', 'PUMP/EUR', 'PACT/USD', 'DASH/EUR']
  ...bars6[5m] 10/44
  ...bars6[5m] 20/44
  ...bars6[5m] 30/44
  ...bars6[5m] 40/44
bars6(5m): 21/44 markets in 34s
5m    21
report falls back to search-granularity bars for: ['SUP/USD', 'SPACE/USD', 'REPPO/USD', 'UAI/EUR', 'AI/USD', 'UNFI/USD', 'UAI/USD', 'BMB/USD', 'BASED/USD', 'REPPO/EUR', 'GWEI/USD', 'ZAMA/USD', 'VELVET/USD', 'LIT/USD', 'NIL/EUR', 'XPL/EUR', 'BLUAI/EUR', 'HMSTR/EUR', 'ACU/USD', 'PUMP/EUR', 'SENT/USD', 'PACT/USD', 'DASH/EUR']

In [6]:
# ── Cell 6: YOUR live controller YAMLs, first-class, on the same engine ──
# Genuinely out-of-sample for any ladder you wrote before this window ends.
# v11 engine: penetration + volume caps + book-spread slip apply here too, so
# these numbers are the closest thing to a live replay in the whole pipeline.
yaml_hist = {pk: hist_report.get(pk, hist_h.get(pk)) for pk in set(list(hist_h) + list(hist_report))}
yaml_hist = {pk: v for pk, v in yaml_hist.items() if v is not None}
# Mark which YAMLs are LIVE (ground truth) vs untraded DRAFTS (hypotheses).
# Leave empty to treat them all as live; otherwise list deployed controller_ids.
DEPLOYED_CONTROLLERS = set()      # e.g. {'range_inventory_ladder_xmr_V1'}
yaml_df, yaml_reports = lr.evaluate_controller_yamls(yamls, yaml_hist, uni, CFG)
if not yaml_df.empty and 'controller' in yaml_df.columns and DEPLOYED_CONTROLLERS:
    yaml_df.insert(1, 'status', yaml_df.controller.map(
        lambda c: 'LIVE' if c in DEPLOYED_CONTROLLERS else 'DRAFT'))
    print('LIVE = deployed (ground truth) | DRAFT = never traded (a backtest of a proposal)')
if not yaml_df.empty:
    display(yaml_df)
    # ---- v11.3: LIVE-STRATEGY HEALTH -- recent form, judged on two axes ----
    # A 180-day headline can hide a strategy that died a month ago. This is
    # the table that makes "no longer profitable" impossible to miss.
    health = lr.live_strategy_health(yaml_df, yaml_reports, CFG)
    print()
    lr.print_health_banners(health)
    display(health)
    health.to_csv(f'{PREFIX}_live_health.csv', index=False)
    for cid, rep in yaml_reports.items():
        print(f"\n=== {cid} — passed={rep['passed']}"
              f"  {('; '.join(rep['failed_gates']) if rep['failed_gates'] else '')} ===")
        display(rep['blocks'])
else:
    print('no controller YAMLs matched this exchange — set YAML_ROOTS in Cell 1')

,controller,pair,src,days,blocks,pnl_pct,hold_pct,edge_pct,edge_pos_rate,abs_pos_rate,worst_block_edge,trades,trades_per_month,med_trades_per_block,maxdd,endinv,stress_edge_pct,vol_capped_fills,passed,failed_gates
0,k_range_inventory_ladder_dash_eur_V1,DASH/EUR,Kraken,180.0,12,69.474,0.000,69.474,0.778,0.636,-2.418,80,13.5,7.0,15.795,45.5,39.331,0,False,median 7 trades/ACTIVE block < 8; clean: media...
1,k_range_inventory_ladder_xmr_usd_V1,XMR/USD,MEXC(XMRUSDT),180.0,12,-8.182,-40.869,32.687,0.727,0.778,-7.079,498,84.1,63.0,53.158,97.9,25.041,0,True,

,controller,pair,status,recent_blocks,recent_days,recent_pnl_pct,recent_hold_pct,recent_edge_pct,recent_trades,recent_two_sided_blocks,last_block_pnl_pct,full_pnl_pct,full_edge_pct
0,k_range_inventory_ladder_dash_eur_V1,DASH/EUR,HEALTHY,3,45.0,15.50,0.0,15.50,23,3,1.799,69.474,69.474
1,k_range_inventory_ladder_xmr_usd_V1,XMR/USD,HEALTHY,3,45.0,16.43,-5.7,22.13,177,3,7.928,-8.182,32.687

=== k_range_inventory_ladder_dash_eur_V1 — passed=False  median 7 trades/ACTIVE block < 8; clean: median 7 trades/ACTIVE block < 8 ===

,block,start,end,days,pnl_pct,hold_pct,edge_pct,buy_fills,sell_fills,trades,two_sided,in_band_pct,in_fit,partial
0,1,2026-01-13,2026-01-27,15.0,0.000,0.0,0.000,0,0,0,False,0.000,False,False
1,2,2026-01-28,2026-02-11,15.0,5.429,0.0,5.429,8,3,11,True,0.800,False,False
2,3,2026-02-12,2026-02-26,15.0,7.202,0.0,7.202,7,4,11,True,1.000,False,False
3,4,2026-02-27,2026-03-13,15.0,-2.079,0.0,-2.079,5,1,6,True,0.933,False,False
4,5,2026-03-14,2026-03-28,15.0,-0.220,0.0,-0.220,8,2,10,True,1.000,False,False
5,6,2026-03-29,2026-04-12,15.0,29.359,0.0,29.359,1,6,7,True,0.667,False,False
6,7,2026-04-13,2026-04-27,15.0,-2.418,0.0,-2.418,1,3,4,True,1.000,False,False
7,8,2026-04-28,2026-05-12,15.0,4.958,0.0,4.958,0,7,7,False,0.667,False,False
8,9,2026-05-13,2026-05-27,15.0,-0.129,0.0,-0.129,0,0,0,False,0.867,False,False
9,10,2026-05-28,2026-06-11,15.0,12.926,0.0,12.926,5,4,9,True,1.000,False,False
10,11,2026-06-12,2026-06-26,15.0,0.471,0.0,0.471,1,6,7,True,1.000,False,False
11,12,2026-06-27,2026-07-11,15.0,1.799,0.0,1.799,4,3,7,True,1.000,False,False
12,13,2026-07-12,2026-07-12,1.0,0.421,0.0,0.421,0,1,1,False,1.000,False,True

=== k_range_inventory_ladder_xmr_usd_V1 — passed=True   ===

,block,start,end,days,pnl_pct,hold_pct,edge_pct,buy_fills,sell_fills,trades,two_sided,in_band_pct,in_fit,partial
0,1,2026-01-13,2026-01-28,15.0,-24.055,-24.055,0.000,0,0,0,False,0.000,False,False
1,2,2026-01-28,2026-02-12,15.0,-12.309,-22.378,10.069,60,47,107,True,0.540,False,False
2,3,2026-02-12,2026-02-27,15.0,10.242,2.433,7.809,42,54,96,True,0.999,False,False
3,4,2026-02-27,2026-03-14,15.0,0.340,3.467,-3.126,2,20,22,True,1.000,False,False
4,5,2026-03-14,2026-03-29,15.0,0.605,-6.171,6.776,17,5,22,True,1.000,False,False
5,6,2026-03-29,2026-04-13,15.0,6.358,3.921,2.438,26,42,68,True,1.000,False,False
6,7,2026-04-13,2026-04-28,15.0,0.139,7.219,-7.079,0,6,6,False,0.818,False,False
7,8,2026-04-28,2026-05-13,15.0,0.079,4.015,-3.936,0,0,0,False,0.134,False,False
8,9,2026-05-13,2026-05-28,15.0,-0.156,-7.644,7.488,0,0,0,False,0.121,False,False
9,10,2026-05-28,2026-06-12,15.0,10.634,-0.242,10.876,26,45,71,True,0.825,False,False
10,11,2026-06-12,2026-06-27,15.0,-2.492,-8.633,6.141,45,18,63,True,0.990,False,False
11,12,2026-06-27,2026-07-12,15.0,7.928,3.456,4.472,28,15,43,True,0.978,False,False

In [7]:
# ── Cell 7: full engine per market (WF + HOLDOUT fit + frozen block report) ──
evals = {}
t0 = time.time()
for i, pk in enumerate(review, 1):
    if pk not in hist_h:
        print(f'[{i}/{len(review)}] {pk}: no usable history'); continue
    try:
        ev = lr.evaluate_market(pk, hist_h, uni, CFG, hist_report=hist_report)
    except Exception as e:
        print(f'[{i}/{len(review)}] {pk}: ERROR {e}'); continue
    evals[pk] = ev
    s, wf, ho = ev['report']['summary'], ev['wf'], ev.get('holdout') or {}
    print(f"[{i}/{len(review)}] {pk:14s} rep={ev['granularity']}/fit={ev['search_granularity']} "
          f"edge={s['edge_pct']:+7.2f}% epr={s.get('edge_pos_rate')} "
          f"clean_epr={s.get('clean_edge_pos_rate')} "
          f"HOLDOUT={ho.get('edge_pct', float('nan')):+.2f}% "
          f"blocks_pass={ev['report']['passed']} wf_pass={wf.get('wf_pass')}")
print(f'engine done in {time.time()-t0:.0f}s')

[1/44] SUP/USD        rep=1d/fit=1d edge= +77.28% epr=0.5 clean_epr=0.0 HOLDOUT=+29.16% blocks_pass=False wf_pass=False
[2/44] SPACE/USD      rep=1h/fit=1h edge=+108.63% epr=0.909 clean_epr=1.0 HOLDOUT=+0.82% blocks_pass=True wf_pass=False
[3/44] REPPO/USD      rep=1d/fit=1d edge=+166.84% epr=0.8 clean_epr=None HOLDOUT=-11.71% blocks_pass=False wf_pass=False
[4/44] UAI/EUR        rep=1d/fit=1d edge=+232.05% epr=0.9 clean_epr=1.0 HOLDOUT=-5.44% blocks_pass=False wf_pass=False
[5/44] AI/USD         rep=1d/fit=1d edge= +32.96% epr=0.75 clean_epr=None HOLDOUT=+12.49% blocks_pass=False wf_pass=False
[6/44] APR/USD        rep=5m/fit=1h edge=+162.03% epr=0.75 clean_epr=0.667 HOLDOUT=+6.18% blocks_pass=False wf_pass=False
[7/44] UNFI/USD       rep=1d/fit=1d edge= +48.94% epr=0.667 clean_epr=0.0 HOLDOUT=+15.37% blocks_pass=False wf_pass=False
[8/44] UAI/USD        rep=1d/fit=1d edge=  -6.17% epr=0.417 clean_epr=0.333 HOLDOUT=-7.19% blocks_pass=False wf_pass=False
[9/44] BMB/USD        rep=1d/fit=1d edge= +68.81% epr=0.571 clean_epr=1.0 HOLDOUT=+17.93% blocks_pass=False wf_pass=False
[10/44] BASED/USD      rep=1d/fit=1d edge= +64.05% epr=0.714 clean_epr=None HOLDOUT=-14.10% blocks_pass=False wf_pass=False
[11/44] XNY/USD        rep=5m/fit=1h edge=+340.31% epr=0.636 clean_epr=0.667 HOLDOUT=-3.95% blocks_pass=False wf_pass=False
[12/44] REPPO/EUR      rep=1d/fit=1d edge=+232.84% epr=1.0 clean_epr=None HOLDOUT=-11.45% blocks_pass=False wf_pass=False
[13/44] BLESS/USD      rep=5m/fit=1h edge=+218.56% epr=0.583 clean_epr=0.571 HOLDOUT=+23.89% blocks_pass=False wf_pass=False
[14/44] AKE/USD        rep=5m/fit=1h edge=  +8.22% epr=0.455 clean_epr=0.5 HOLDOUT=-12.35% blocks_pass=False wf_pass=False
[15/44] GWEI/USD       rep=1h/fit=1h edge=+126.92% epr=0.333 clean_epr=0.25 HOLDOUT=-1.78% blocks_pass=False wf_pass=False
[16/44] ZAMA/USD       rep=1d/fit=1d edge= +79.34% epr=0.545 clean_epr=0.667 HOLDOUT=+9.78% blocks_pass=False wf_pass=False
[17/44] VELVET/USD     rep=1d/fit=1d edge= -63.82% epr=0.667 clean_epr=0.0 HOLDOUT=+0.00% blocks_pass=False wf_pass=False
[18/44] ICNT/USD       rep=5m/fit=1h edge=  +3.61% epr=0.333 clean_epr=1.0 HOLDOUT=-2.67% blocks_pass=False wf_pass=False
[19/44] Q/USD          rep=5m/fit=1h edge=+139.31% epr=0.667 clean_epr=0.429 HOLDOUT=+7.97% blocks_pass=False wf_pass=False
[20/44] PTB/USD        rep=5m/fit=1h edge= +13.86% epr=1.0 clean_epr=1.0 HOLDOUT=+9.38% blocks_pass=False wf_pass=False
[21/44] LIT/USD        rep=1d/fit=1d edge=+118.66% epr=0.545 clean_epr=0.4 HOLDOUT=+0.00% blocks_pass=False wf_pass=False
[22/44] NIL/EUR        rep=1d/fit=1d edge= +16.00% epr=0.667 clean_epr=0.0 HOLDOUT=+0.00% blocks_pass=False wf_pass=False
[23/44] PLAY/USD       rep=5m/fit=1h edge=+281.52% epr=0.6 clean_epr=0.6 HOLDOUT=+19.99% blocks_pass=False wf_pass=False
[24/44] B2/USD         rep=5m/fit=1h edge= +50.00% epr=0.7 clean_epr=0.6 HOLDOUT=+2.44% blocks_pass=False wf_pass=True
[25/44] KTA/USD        rep=5m/fit=1h edge= +14.84% epr=0.5 clean_epr=0.667 HOLDOUT=+0.85% blocks_pass=False wf_pass=False
[26/44] XPL/EUR        rep=1d/fit=1d edge= +77.52% epr=0.636 clean_epr=0.4 HOLDOUT=+6.42% blocks_pass=False wf_pass=False
[27/44] BLUAI/EUR      rep=1d/fit=1d edge=+165.96% epr=0.667 clean_epr=0.667 HOLDOUT=-9.04% blocks_pass=False wf_pass=False
[28/44] XPL/USD        rep=5m/fit=1h edge=+105.06% epr=0.818 clean_epr=0.667 HOLDOUT=+16.27% blocks_pass=True wf_pass=False
[29/44] NIL/USD        rep=5m/fit=1h edge= +51.56% epr=0.636 clean_epr=0.667 HOLDOUT=+7.89% blocks_pass=False wf_pass=False
[30/44] STABLE/USD     rep=5m/fit=1h edge=+276.61% epr=0.818 clean_epr=0.667 HOLDOUT=+6.91% blocks_pass=True wf_pass=False
[31/44] HMSTR/USD      rep=5m/fit=1h edge=+111.91% epr=0.75 clean_epr=0.714 HOLDOUT=-7.04% blocks_pass=False wf_pass=False
[32/44] DAG/USD        rep=5m/fit=1h edge= +50.00% epr=0.667 clean_epr=0.714 HOLDOUT=-34.56% blocks_pass=False wf_pass=False
[33/44] BLUAI/USD      rep=5m/fit=1h edge=+108.29% epr=0.6 clean_epr=1.0 HOLDOUT=-2.72% blocks_pass=False wf_pass=False
[34/44] HMSTR/EUR      rep=1d/fit=1d edge=+118.22% epr=0.7 clean_epr=0.5 HOLDOUT=-6.84% blocks_pass=False wf_pass=False
[35/44] ENSO/USD       rep=5m/fit=1h edge= +26.58% epr=0.667 clean_epr=0.714 HOLDOUT=-4.78% blocks_pass=False wf_pass=False
[36/44] ACU/USD        rep=1h/fit=1h edge= +55.63% epr=0.545 clean_epr=0.667 HOLDOUT=-3.71% blocks_pass=False wf_pass=False
[37/44] PUMP/EUR       rep=1d/fit=1d edge=  +2.50% epr=0.5 clean_epr=0.0 HOLDOUT=+1.87% blocks_pass=False wf_pass=True
[38/44] SENT/USD       rep=1h/fit=1h edge= +84.14% epr=0.727 clean_epr=0.5 HOLDOUT=+5.26% blocks_pass=False wf_pass=False
[39/44] PACT/USD       rep=1d/fit=1d edge= +95.95% epr=0.778 clean_epr=0.5 HOLDOUT=-37.35% blocks_pass=False wf_pass=False
[40/44] PUMP/USD       rep=5m/fit=1h edge= +34.92% epr=0.667 clean_epr=0.5 HOLDOUT=-0.28% blocks_pass=False wf_pass=False
[41/44] XMR/USD        rep=5m/fit=1h edge= +46.82% epr=0.727 clean_epr=0.833 HOLDOUT=+3.79% blocks_pass=True wf_pass=True
[42/44] XMR/USDT       rep=5m/fit=1h edge= +44.72% epr=0.7 clean_epr=0.8 HOLDOUT=+3.50% blocks_pass=True wf_pass=True
[43/44] DASH/USD       rep=5m/fit=1h edge= +76.01% epr=0.8 clean_epr=0.8 HOLDOUT=+3.54% blocks_pass=True wf_pass=False
[44/44] DASH/EUR       rep=1d/fit=1d edge= +86.89% epr=0.727 clean_epr=0.5 HOLDOUT=+0.87% blocks_pass=False wf_pass=False
engine done in 274s

In [8]:
# ── Cell 8: rolling walk-forward summary (secondary, leakage-safe) ────
wf_rows = pd.DataFrame([dict(market=pk, **{k: v for k, v in ev['wf'].items() if k != 'folds'})
                        for pk, ev in evals.items() if ev])
if not wf_rows.empty:
    wf_rows = wf_rows.sort_values(['wf_pass', 'edge_pos_rate', 'median_edge_pct'],
                                  ascending=[False, False, False]).reset_index(drop=True)
display(wf_rows)

,market,n_folds,edge_pos_rate,two_sided_rate,median_edge_pct,median_test_pct,median_stress_edge,worst_edge_pct,median_trades,total_trades,wf_pass,note
0,XMR/USDT,8,0.625,0.625,1.494,1.160,0.948,-4.852,20.0,214.0,True,NaN
1,B2/USD,8,0.625,0.875,1.067,2.022,0.755,-4.022,21.5,210.0,True,NaN
2,XMR/USD,8,0.625,0.500,0.376,1.247,-0.114,-4.962,21.0,199.0,True,NaN
3,PUMP/EUR,8,0.625,0.500,0.292,-0.554,-0.095,-7.267,10.5,89.0,True,NaN
4,REPPO/EUR,1,1.000,1.000,21.083,22.119,-1.940,21.083,14.0,14.0,False,NaN
5,Q/USD,8,0.750,0.750,6.991,10.341,2.205,-57.655,42.0,355.0,False,NaN
6,XPL/USD,8,0.750,0.750,3.957,9.425,2.543,-10.361,38.0,317.0,False,NaN
7,APR/USD,8,0.750,0.875,1.900,6.257,0.472,-10.121,43.5,411.0,False,NaN
8,AKE/USD,8,0.625,0.875,4.532,3.837,1.937,-74.472,33.0,313.0,False,NaN
9,STABLE/USD,8,0.625,0.875,4.202,6.376,2.350,-8.188,41.5,305.0,False,NaN
10,BLUAI/USD,8,0.625,0.750,3.982,9.858,0.842,-12.244,23.0,270.0,False,NaN
11,ACU/USD,7,0.571,1.000,2.804,4.080,1.761,-9.381,40.0,291.0,False,NaN
12,SENT/USD,7,0.571,0.429,2.786,2.364,2.332,-8.724,23.0,176.0,False,NaN
13,SPACE/USD,7,0.571,0.571,1.437,6.681,0.656,-10.576,24.0,198.0,False,NaN
14,BASED/USD,2,0.500,0.500,14.596,20.145,4.026,0.000,12.5,25.0,False,NaN
15,PLAY/USD,8,0.500,0.625,4.277,15.910,-8.919,-17.162,68.0,656.0,False,NaN
16,SUP/USD,6,0.500,0.500,2.775,10.991,-3.667,-13.354,19.5,127.0,False,NaN
17,BLESS/USD,8,0.500,0.625,2.691,9.875,1.426,-105.662,33.5,326.0,False,NaN
18,PTB/USD,8,0.500,0.750,1.616,-5.323,1.528,-9.504,35.5,291.0,False,NaN
19,PUMP/USD,8,0.500,0.625,0.675,1.865,0.745,-3.393,28.0,305.0,False,NaN
20,LIT/USD,8,0.500,0.625,0.609,4.486,0.000,-13.787,11.5,87.0,False,NaN
21,HMSTR/USD,8,0.500,0.375,0.215,1.846,-0.155,-9.011,24.5,228.0,False,NaN
22,DASH/USD,8,0.500,0.625,0.082,3.583,0.758,-4.939,21.0,221.0,False,NaN
23,NIL/USD,8,0.500,0.875,-0.020,6.499,1.788,-19.515,25.5,232.0,False,NaN
24,KTA/USD,8,0.500,0.500,-0.958,-0.911,-1.202,-15.089,30.0,277.0,False,NaN
25,GWEI/USD,7,0.429,0.571,-0.280,4.253,0.362,-47.264,32.0,305.0,False,NaN
26,PACT/USD,5,0.400,0.600,0.000,23.749,0.000,-49.918,5.0,119.0,False,NaN
27,UNFI/USD,8,0.375,0.375,0.000,-4.111,0.000,-32.335,10.0,104.0,False,NaN
28,UAI/USD,8,0.375,0.625,-0.050,4.229,-0.059,-14.774,10.5,119.0,False,NaN
29,XPL/EUR,8,0.375,0.500,-0.251,-0.714,-0.338,-6.130,10.5,101.0,False,NaN
30,BMB/USD,8,0.375,0.750,-0.306,-2.211,-9.192,-39.051,20.0,141.0,False,NaN
31,XNY/USD,8,0.375,0.625,-1.419,7.167,-0.326,-15.031,23.0,235.0,False,NaN
32,HMSTR/EUR,8,0.375,0.375,-1.483,3.078,-0.530,-11.186,9.5,81.0,False,NaN
33,ENSO/USD,8,0.375,0.250,-2.280,-2.555,-1.356,-8.494,32.5,244.0,False,NaN
34,ICNT/USD,8,0.375,0.500,-4.590,-6.894,-6.638,-18.013,34.5,303.0,False,NaN
35,UAI/EUR,8,0.250,0.500,0.000,5.308,0.000,-14.292,6.5,59.0,False,NaN
36,DASH/EUR,8,0.250,0.125,-0.083,-1.325,-0.086,-12.567,7.0,66.0,False,NaN
37,ZAMA/USD,6,0.167,0.167,-0.523,0.320,-0.539,-10.821,4.5,32.0,False,NaN
38,BLUAI/EUR,8,0.125,0.250,0.000,3.211,-0.980,-13.249,3.5,50.0,False,NaN
39,NIL/EUR,8,0.125,0.250,-0.209,0.341,-0.199,-15.169,2.0,24.0,False,NaN
40,DAG/USD,8,0.125,0.375,-12.906,-7.950,-9.869,-73.865,15.0,118.0,False,NaN
41,REPPO/USD,1,0.000,0.000,0.000,-1.568,0.000,0.000,0.0,0.0,False,NaN
42,VELVET/USD,8,0.000,0.000,0.000,-13.518,0.000,-16.291,0.0,2.0,False,NaN
43,AI/USD,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,insufficient history for rolling validation

In [9]:
# ── Cell 9: finalize (v10 gates + holdout/clean gates + sizing), write artifacts ─
final_df, configs = lr.finalize_v11(evals, uni, CFG, yaml_reports)
display(final_df)

print('\n— HOLDOUT (the deciding out-of-sample evidence) —')
ho_view = final_df[['base', 'validation', 'holdout_edge_pct', 'holdout_trades',
                    'holdout_two_sided', 'holdout_active', 'edge_pct',
                    'clean_edge_pos_rate', 'harvest_best_pct_mo',
                    'max_fund', 'max_fund_quote', 'depth_2pct', 'gates']]
display(ho_view)

block_tables = {pk: ev['report']['blocks'] for pk, ev in evals.items() if ev}
written = lr.save_v11_outputs(PREFIX, final_df, configs, wf_rows, yaml_df, block_tables,
                              metadata=dict(exchange=EXCHANGE, run=RUN_TS,
                                            cfg={k: str(v) for k, v in CFG.items() if str(k).startswith('rc_')},
                                            yaml_paths=[p['path'] for p in yamls]))
# ---- v11.3: FULLY DEPLOYABLE YAMLs ----------------------------------------
# One ready-to-run controller config per market that is CONFIRMED, a strong
# CANDIDATE (GATED on the WF process check only, with a two-sided holdout and
# clean blocks), or ALREADY LIVE (a REFRESH re-fit at today's anchor -- never
# drop one over a running config without comparing rungs; bump the id and
# start a clean state file if you adopt it).
deployed_pairs = [lr._pair_key(p['trading_pair']) for p in yamls
                  if not DEPLOYED_CONTROLLERS
                  or p.get('controller_id', p.get('id')) in DEPLOYED_CONTROLLERS]
yaml_paths = lr.save_deploy_yamls(ART / 'deploy_yamls', configs, final_df, CFG,
                                  deployed_pairs=deployed_pairs, run_id=RUN_TS[:8])
print(f'\n{len(yaml_paths)-1} deployable YAMLs -> {ART}/deploy_yamls (see INDEX.md)')
print('Read:', f'{PREFIX}_copy_paste_ladders.md')

,base,trading_pair,src,granularity,validation,rungs,family,spacing,weights,pnl_pct,...,quote_usd_rate,max_fund_quote,max_fund,spread_pct,depth_2pct,depth_used,depth_basis,depth_ladder_band,book_total_usd,gates
0,XMR/USD,XMR-USD,MEXC(XMRUSDT),5m,CONFIRMED,10+7,quantile,back_loaded,slight_deep,21.576,...,1.00000,10000.000,10000,0.0247,1066574.0,2749939.0,ladder_band,2749939.0,3.613548e+06,
1,XMR/USDT,XMR-USDT,MEXC,5m,CONFIRMED,8+8,quantile,back_loaded,slight_deep,19.475,...,1.00000,10000.000,10000,0.0586,1086526.0,2379701.0,ladder_band,2379701.0,1.304605e+09,
2,SPACE/USD,SPACE-USD,MEXC(SPACEUSDT),1h,GATED,8+7,quantile,back_loaded,slight_deep,89.220,...,1.00000,400.000,400,0.0991,16858.0,22113.0,ladder_band,22113.0,2.926000e+05,rolling WF (process check) failed
3,STABLE/USD,STABLE-USD,MEXC(STABLEUSDT),5m,GATED,10+8,quantile,back_loaded,slight_deep,350.651,...,1.00000,300.000,300,0.0275,42991.0,72828.0,ladder_band,72828.0,1.612890e+05,rolling WF (process check) failed
4,XPL/USD,XPL-USD,MEXC(XPLUSDT),5m,GATED,10+9,quantile,linear,slight_deep,84.038,...,1.00000,3500.000,3500,0.1134,192446.0,275023.0,ladder_band,275023.0,2.096382e+06,rolling WF (process check) failed
5,DASH/USD,DASH-USD,MEXC(DASHUSDT),5m,GATED,9+8,quantile,back_loaded,slight_deep,57.831,...,1.00000,2750.000,2750,0.0725,197834.0,669286.0,ladder_band,669286.0,1.787337e+06,rolling WF (process check) failed
6,REPPO/EUR,REPPO-EUR,Kraken,1d,SUSPECT,9+10,quantile,back_loaded,slight_deep,288.111,...,1.13935,175.539,200,4.1724,0.0,3990.0,ladder_band,3990.0,1.430900e+04,only 5 full blocks (< 6); clean: only 1 out-of...
7,PTB/USD,PTB-USD,MEXC(PTBUSDT),5m,SUSPECT,7+5,quantile,back_loaded,slight_deep,-27.190,...,1.00000,400.000,400,0.6205,3945.0,10644.0,ladder_band,10644.0,2.014557e+06,only 3 ACTIVE blocks (< 4) -- band rarely visi...
8,REPPO/USD,REPPO-USD,Kraken,1d,SUSPECT,9+10,volatility,back_loaded,slight_deep,220.661,...,1.00000,1250.000,1250,2.2414,1711.0,6253.0,ladder_band,6253.0,4.105370e+05,only 5 full blocks (< 6); clean: only 1 out-of...
9,PACT/USD,PACT-USD,Kraken,1d,SUSPECT,8+4,volatility,back_loaded,slight_deep,59.237,...,1.00000,500.000,500,4.2760,0.0,1141.0,min_band_5pct,334.0,5.291380e+05,worst block edge -13.91% < -12.5%; median 6 tr...
10,APR/USD,APR-USD,MEXC(APRUSDT),5m,SUSPECT,10+9,pct,geometric,mild_near,207.086,...,1.00000,200.000,200,0.3861,13795.0,17641.0,min_band_5pct,13138.0,5.366700e+04,clean: only 3 ACTIVE blocks (< 4) -- band rare...
11,HMSTR/USD,HMSTR-USD,MEXC(HMSTRUSDT),5m,SUSPECT,8+10,quantile,back_loaded,slight_deep,105.293,...,1.00000,600.000,600,0.2427,28575.0,35539.0,ladder_band,35539.0,8.968200e+04,abs_pos_rate 0.43 < 0.5 (active blocks); two_s...
12,AI/USD,AI-USD,Kraken,1d,SUSPECT,5+10,quantile,back_loaded,slight_deep,-0.389,...,1.00000,1750.000,1750,0.0792,52238.0,89506.0,ladder_band,89506.0,2.231330e+05,only 5 full blocks (< 6); worst block edge -13...
13,DASH/EUR,DASH-EUR,Kraken,1d,SUSPECT,8+7,quantile,back_loaded,slight_deep,82.062,...,1.13935,263.308,300,0.0925,34412.0,126369.0,ladder_band,126369.0,8.069660e+05,median 7 trades/ACTIVE block < 8; two_sided_ra...
14,SENT/USD,SENT-USD,MEXC(SENTUSDT),1h,SUSPECT,10+9,quantile,back_loaded,slight_deep,102.692,...,1.00000,500.000,500,0.0074,94640.0,106680.0,ladder_band,106680.0,1.232830e+05,abs_pos_rate 0.25 < 0.5 (active blocks); worst...
15,BASED/USD,BASED-USD,Kraken,1d,SUSPECT,9+7,pct,back_loaded,slight_deep,58.420,...,1.00000,2750.000,2750,0.1405,21983.0,34629.0,min_band_5pct,5206.0,3.585830e+05,clean: only 2 out-of-fit blocks (< 4); holdout...
16,HMSTR/EUR,HMSTR-EUR,Kraken,1d,SUSPECT,4+7,quantile,back_loaded,slight_deep,115.651,...,1.13935,175.539,200,2.7275,965.0,21498.0,ladder_band,21498.0,2.900900e+04,median 6 trades/ACTIVE block < 8; two_sided_ra...
17,B2/USD,B2-USD,MEXC(B2USDT),5m,SUSPECT,5+6,volatility,back_loaded,slight_deep,37.788,...,1.00000,300.000,300,0.3165,5720.0,22548.0,ladder_band,22548.0,6.385900e+04,clean: edge_pos_rate 0.60 < 0.65 (over 5 engag...
18,BLUAI/EUR,BLUAI-EUR,Kraken,1d,SUSPECT,10+9,quantile,back_loaded,slight_deep,296.701,...,1.13935,263.308,300,0.5202,8714.0,14338.0,min_band_5pct,8170.0,4.248200e+04,worst block edge -12.82% < -12.5%; clean: only...
19,Q/USD,Q-USD,MEXC(QUSDT),5m,SUSPECT,6+10,pct,linear,slight_deep,144.925,...,1.00000,300.000,300,0.8071,2694.0,13863.0,ladder_band,13863.0,3.364800e+04,clean: edge_pos_rate 0.43 < 0.65 (over 7 engag...
20,DAG/USD,DAG-USD,MEXC(DAGUSDT),5m,SUSPECT,10+6,quantile,back_loaded,slight_deep,33.137,...,1.00000,700.000,700,2.9581,2045.0,36540.0,ladder_band,36540.0,6.938586e+06,abs_pos_rate 0.22 < 0.5 (active blocks); worst...
21,UNFI/USD,UNFI-USD,Kraken,1d,SUSPECT,7+8,quantile,back_loaded,slight_deep,17.327,...,1.00000,500.000,500,1.4025,386.0,11943.0,ladder_band,11943.0,8.622313e+06,clean: only 1 ACTIVE blocks (< 4) -- band rare...
22,PUMP/USD,PUMP-USD,MEXC(PUMPUSDT),5m,SUSPECT,10+7,volatility,geometric,near,12.667,...,1.00000,4500.000,4500,0.0670,499349.0,950387.0,ladder_band,950387.0,2.375018e+06,abs_pos_rate 0.44 < 0.5 (active blocks); two_s...
23,ENSO/USD,ENSO-USD,MEXC(ENSOUSDT),5m,SUSPECT,6+6,quantile,linear,slight_deep,28.740,...,1.00000,300.000,300,0.2833,20210.0,25627.0,ladder_band,25627.0,5.612200e+04,abs_pos_rate 0.33 < 0.5 (active blocks); worst...
24,NIL/EUR,NIL-EUR,Kraken,1d,SUSPECT,8+10,quantile,back_loaded,slight_deep,-9.044,...,1.13935,438.847,500,0.3263,8091.0,22458.0,min_band_5pct,7736.0,3.288898e+06,abs_pos_rate 0.30 < 0.5 (active blocks); media...
25,VELVET/USD,VELVET-USD,Kraken,1d,SUSPECT,4+4,quantile,back_loaded,near,52.553,...,1.00000,3500.000,3500,0.7230,13045.0,22294.0,min_band_5pct,366.0,1.549740e+05,only 1 ACTIVE blocks (< 4) -- band rarely visi...
26,XNY/USD,XNY-USD,MEXC(XNYUSDT),5m,SUSPECT,10+6,quantile,back_loaded,slight_deep,372.374,...,1.00000,600.000,600,0.3578,5502.0,30669.0,ladder_band,30669.0,2.032140e+05,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
27,XPL/EUR,XPL-EUR,Kraken,1d,SUSPECT,4+9,volatility,back_loaded,slight_deep,57.682,...,1.13935,614.385,700,0.1293,81860.0,90100.0,ladder_band,90100.0,5.281120e+05,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
28,NIL/USD,NIL-USD,MEXC(NILUSDT),5m,SUSPECT,6+8,quantile,back_loaded,slight_deep,26.524,...,1.00000,700.000,700,0.2861,56341.0,81604.0,ladder_band,81604.0,5.766250e+05,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
29,PLAY/USD,PLAY-USD,MEXC(PLAYUSDT),5m,SUSPECT,10+7,pct,back_loaded,slight_deep,257.056,...,1.00000,2000.000,2000,0.1527,12824.0,45439.0,ladder_band,45439.0,8.746880e+05,edge_pos_rate 0.60 < 0.65 (over 10 engaged blo...
30,BLESS/USD,BLESS-USD,MEXC(BLESSUSDT),5m,SUSPECT,4+10,quantile,back_loaded,near,200.722,...,1.00000,600.000,600,0.2074,7615.0,22933.0,ladder_band,22933.0,1.055810e+05,edge_pos_rate 0.58 < 0.65 (over 12 engaged blo...
31,BMB/USD,BMB-USD,Kraken,1d,SUSPECT,8+7,quantile,back_loaded,slight_deep,38.452,...,1.00000,800.000,800,3.7912,94.0,7257.0,ladder_band,7257.0,5.623700e+04,edge_pos_rate 0.57 < 0.65 (over 7 engaged bloc...
32,LIT/USD,LIT-USD,Kraken,1d,SUSPECT,6+4,quantile,back_loaded,mild_near,109.781,...,1.00000,200.000,200,1.5474,2235.0,16855.0,ladder_band,16855.0,6.813314e+06,edge_pos_rate 0.55 < 0.65 (over 11 engaged blo...
33,ZAMA/USD,ZAMA-USD,Kraken,1d,SUSPECT,4+10,quantile,back_loaded,slight_deep,63.983,...,1.00000,400.000,400,0.1437,74244.0,93107.0,ladder_band,93107.0,3.867050e+05,edge_pos_rate 0.55 < 0.65 (over 11 engaged blo...
34,SUP/USD,SUP-USD,Kraken,1d,SUSPECT,8+9,volatility,back_loaded,slight_deep,45.214,...,1.00000,800.000,800,11.2897,0.0,2752.0,ladder_band,2752.0,3.188900e+04,edge_pos_rate 0.50 < 0.65 (over 4 engaged bloc...
35,KTA/USD,KTA-USD,MEXC(KTAUSDT),5m,SUSPECT,4+10,quantile,back_loaded,slight_deep,-11.822,...,1.00000,1000.000,1000,0.4914,11291.0,26177.0,ladder_band,26177.0,3.868492e+07,edge_pos_rate 0.50 < 0.65 (over 8 engaged bloc...
36,PUMP/EUR,PUMP-EUR,Kraken,1d,SUSPECT,10+10,volatility,back_loaded,slight_deep,-17.322,...,1.13935,1097.120,1250,0.0765,125820.0,266843.0,ladder_band,266843.0,5.366990e+05,edge_pos_rate 0.50 < 0.65 (over 2 engaged bloc...
37,AKE/USD,AKE-USD,MEXC(AKEUSDT),5m,SUSPECT,7+10,quantile,geometric,equal,-22.843,...,1.00000,300.000,300,0.5406,2604.0,7770.0,ladder_band,7770.0,1.463354e+07,edge_pos_rate 0.45 < 0.65 (over 11 engaged blo...
38,UAI/USD,UAI-USD,Kraken,1d,SUSPECT,8+4,quantile,back_loaded,slight_deep,55.616,...,1.00000,2250.000,2250,0.2310,14608.0,32813.0,ladder_band,32813.0,1.855410e+05,edge_pos_rate 0.42 < 0.65 (over 12 engaged blo...
39,GWEI/USD,GWEI-USD,MEXC(GWEIUSDT),1h,SUSPECT,10+10,quantile,back_loaded,slight_deep,430.925,...,1.00000,4500.000,4500,0.2511,11996.0,88881.0,ladder_band,88881.0,2.006580e+05,edge_pos_rate 0.33 < 0.65 (over 9 engaged bloc...
40,ICNT/USD,ICNT-USD,MEXC(ICNTUSDT),5m,SUSPECT,7+6,quantile,back_loaded,slight_deep,-27.665,...,1.00000,800.000,800,0.1268,19738.0,38288.0,ladder_band,38288.0,5.494800e+04,only 3 ACTIVE blocks (< 4) -- band rarely visi...
41,UAI/EUR,UAI-EUR,Kraken,1d,SUSPECT,9+6,quantile,back_loaded,slight_deep,292.126,...,1.13935,175.539,200,0.0911,7970.0,8097.0,ladder_band,8097.0,1.614100e+04,worst block edge -24.06% < -12.5%; median 6 tr...
42,BLUAI/USD,BLUAI-USD,MEXC(BLUAIUSDT),5m,SUSPECT,7+4,quantile,back_loaded,slight_deep,221.740,...,1.00000,3500.000,3500,0.1967,21556.0,32493.0,ladder_band,32493.0,5.446500e+04,edge_pos_rate 0.60 < 0.65 (over 5 engaged bloc...
43,ACU/USD,ACU-USD,MEXC(ACUUSDT),1h,SUSPECT,5+6,pct,linear,slight_deep,128.360,...,1.00000,300.000,300,0.1354,26608.0,38973.0,ladder_band,38973.0,1.546890e+05,edge_pos_rate 0.55 < 0.65 (over 11 engaged blo...

— HOLDOUT (the deciding out-of-sample evidence) —

,base,validation,holdout_edge_pct,holdout_trades,holdout_two_sided,holdout_active,edge_pct,clean_edge_pos_rate,harvest_best_pct_mo,max_fund,max_fund_quote,depth_2pct,gates
0,XMR/USD,CONFIRMED,3.791,43,True,True,46.822,0.833,32.627,10000,10000.000,1066574.0,
1,XMR/USDT,CONFIRMED,3.498,24,True,True,44.721,0.800,32.627,10000,10000.000,1086526.0,
2,SPACE/USD,GATED,0.817,24,False,True,108.630,1.000,70.789,400,400.000,16858.0,rolling WF (process check) failed
3,STABLE/USD,GATED,6.907,38,True,True,276.609,0.667,54.224,300,300.000,42991.0,rolling WF (process check) failed
4,XPL/USD,GATED,16.274,61,True,True,105.057,0.667,51.664,3500,3500.000,192446.0,rolling WF (process check) failed
5,DASH/USD,GATED,3.542,19,True,True,76.012,0.800,44.138,2750,2750.000,197834.0,rolling WF (process check) failed
6,REPPO/EUR,SUSPECT,-11.454,15,False,True,232.837,NaN,20.813,200,175.539,0.0,only 5 full blocks (< 6); clean: only 1 out-of...
7,PTB/USD,SUSPECT,9.385,27,True,True,13.861,1.000,70.579,400,400.000,3945.0,only 3 ACTIVE blocks (< 4) -- band rarely visi...
8,REPPO/USD,SUSPECT,-11.712,17,False,True,166.838,NaN,39.304,1250,1250.000,1711.0,only 5 full blocks (< 6); clean: only 1 out-of...
9,PACT/USD,SUSPECT,-37.351,3,False,True,95.950,0.500,13.582,500,500.000,0.0,worst block edge -13.91% < -12.5%; median 6 tr...
10,APR/USD,SUSPECT,6.185,123,True,True,162.029,0.667,58.814,200,200.000,13795.0,clean: only 3 ACTIVE blocks (< 4) -- band rare...
11,HMSTR/USD,SUSPECT,-7.045,37,False,True,111.910,0.714,44.215,600,600.000,28575.0,abs_pos_rate 0.43 < 0.5 (active blocks); two_s...
12,AI/USD,SUSPECT,12.495,23,True,True,32.961,NaN,24.377,1750,1750.000,52238.0,only 5 full blocks (< 6); worst block edge -13...
13,DASH/EUR,SUSPECT,0.873,5,False,True,86.887,0.500,6.857,300,263.308,34412.0,median 7 trades/ACTIVE block < 8; two_sided_ra...
14,SENT/USD,SUSPECT,5.256,29,True,True,84.142,0.500,45.287,500,500.000,94640.0,abs_pos_rate 0.25 < 0.5 (active blocks); worst...
15,BASED/USD,SUSPECT,-14.100,9,True,True,64.050,NaN,21.365,2750,2750.000,21983.0,clean: only 2 out-of-fit blocks (< 4); holdout...
16,HMSTR/EUR,SUSPECT,-6.836,10,False,True,118.215,0.500,10.783,200,175.539,965.0,median 6 trades/ACTIVE block < 8; two_sided_ra...
17,B2/USD,SUSPECT,2.435,16,True,True,50.000,0.600,31.798,300,300.000,5720.0,clean: edge_pos_rate 0.60 < 0.65 (over 5 engag...
18,BLUAI/EUR,SUSPECT,-9.035,8,False,True,165.955,0.667,16.597,300,263.308,8714.0,worst block edge -12.82% < -12.5%; clean: only...
19,Q/USD,SUSPECT,7.973,72,True,True,139.312,0.429,53.487,300,300.000,2694.0,clean: edge_pos_rate 0.43 < 0.65 (over 7 engag...
20,DAG/USD,SUSPECT,-34.562,14,False,True,49.999,0.714,21.519,700,700.000,2045.0,abs_pos_rate 0.22 < 0.5 (active blocks); worst...
21,UNFI/USD,SUSPECT,15.368,31,True,True,48.943,0.000,12.667,500,500.000,386.0,clean: only 1 ACTIVE blocks (< 4) -- band rare...
22,PUMP/USD,SUSPECT,-0.276,22,False,True,34.923,0.500,45.614,4500,4500.000,499349.0,abs_pos_rate 0.44 < 0.5 (active blocks); two_s...
23,ENSO/USD,SUSPECT,-4.780,27,False,True,26.576,0.714,48.839,300,300.000,20210.0,abs_pos_rate 0.33 < 0.5 (active blocks); worst...
24,NIL/EUR,SUSPECT,0.000,0,False,True,15.996,0.000,14.666,500,438.847,8091.0,abs_pos_rate 0.30 < 0.5 (active blocks); media...
25,VELVET/USD,SUSPECT,0.000,0,False,False,-63.821,0.000,21.210,3500,3500.000,13045.0,only 1 ACTIVE blocks (< 4) -- band rarely visi...
26,XNY/USD,SUSPECT,-3.952,26,False,True,340.314,0.667,84.214,600,600.000,5502.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
27,XPL/EUR,SUSPECT,6.422,19,False,True,77.515,0.400,13.810,700,614.385,81860.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
28,NIL/USD,SUSPECT,7.894,17,True,True,51.559,0.667,56.486,700,700.000,56341.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
29,PLAY/USD,SUSPECT,19.987,149,True,True,281.517,0.600,95.169,2000,2000.000,12824.0,edge_pos_rate 0.60 < 0.65 (over 10 engaged blo...
30,BLESS/USD,SUSPECT,23.893,31,True,True,218.561,0.571,73.298,600,600.000,7615.0,edge_pos_rate 0.58 < 0.65 (over 12 engaged blo...
31,BMB/USD,SUSPECT,17.925,23,True,True,68.812,1.000,20.056,800,800.000,94.0,edge_pos_rate 0.57 < 0.65 (over 7 engaged bloc...
32,LIT/USD,SUSPECT,0.000,0,False,False,118.660,0.400,11.570,200,200.000,2235.0,edge_pos_rate 0.55 < 0.65 (over 11 engaged blo...
33,ZAMA/USD,SUSPECT,9.780,14,True,True,79.343,0.667,11.855,400,400.000,74244.0,edge_pos_rate 0.55 < 0.65 (over 11 engaged blo...
34,SUP/USD,SUSPECT,29.155,16,True,True,77.285,0.000,24.204,800,800.000,0.0,edge_pos_rate 0.50 < 0.65 (over 4 engaged bloc...
35,KTA/USD,SUSPECT,0.852,38,True,True,14.837,0.667,50.601,1000,1000.000,11291.0,edge_pos_rate 0.50 < 0.65 (over 8 engaged bloc...
36,PUMP/EUR,SUSPECT,1.868,10,False,True,2.496,0.000,10.509,1250,1097.120,125820.0,edge_pos_rate 0.50 < 0.65 (over 2 engaged bloc...
37,AKE/USD,SUSPECT,-12.352,42,True,True,8.219,0.500,64.802,300,300.000,2604.0,edge_pos_rate 0.45 < 0.65 (over 11 engaged blo...
38,UAI/USD,SUSPECT,-7.192,9,False,True,-6.175,0.333,9.458,2250,2250.000,14608.0,edge_pos_rate 0.42 < 0.65 (over 12 engaged blo...
39,GWEI/USD,SUSPECT,-1.778,74,True,True,126.925,0.250,86.402,4500,4500.000,11996.0,edge_pos_rate 0.33 < 0.65 (over 9 engaged bloc...
40,ICNT/USD,SUSPECT,-2.670,32,True,True,3.607,1.000,52.569,800,800.000,19738.0,only 3 ACTIVE blocks (< 4) -- band rarely visi...
41,UAI/EUR,SUSPECT,-5.441,16,False,True,232.054,1.000,9.221,200,175.539,7970.0,worst block edge -24.06% < -12.5%; median 6 tr...
42,BLUAI/USD,SUSPECT,-2.719,20,True,True,108.289,1.000,63.629,3500,3500.000,21556.0,edge_pos_rate 0.60 < 0.65 (over 5 engaged bloc...
43,ACU/USD,SUSPECT,-3.705,21,False,True,55.626,0.667,63.058,300,300.000,26608.0,edge_pos_rate 0.55 < 0.65 (over 11 engaged blo...

  wrote artifacts/kraken/20260713-040411/files/KRAKEN_recycle_v9_final_summary.csv
  wrote artifacts/kraken/20260713-040411/files/KRAKEN_recycle_v9_walkforward_summary.csv
  wrote artifacts/kraken/20260713-040411/files/KRAKEN_recycle_v9_live_yaml_summary.csv
  wrote artifacts/kraken/20260713-040411/files/KRAKEN_recycle_v9_block_details.csv
  wrote artifacts/kraken/20260713-040411/files/KRAKEN_recycle_v9_holdout_summary.csv
  wrote artifacts/kraken/20260713-040411/files/KRAKEN_recycle_v9_deploy_config.json
  wrote artifacts/kraken/20260713-040411/files/KRAKEN_recycle_v9_copy_paste_ladders.md
  wrote deployable YAML artifacts/kraken/20260713-040411/files/deploy_yamls/k_range_inventory_ladder_dash_eur_auto_20260713.yml
  wrote deployable YAML artifacts/kraken/20260713-040411/files/deploy_yamls/k_range_inventory_ladder_dash_usd_auto_20260713.yml
  wrote deployable YAML artifacts/kraken/20260713-040411/files/deploy_yamls/k_range_inventory_ladder_stable_usd_auto_20260713.yml
  wrote deployable YAML artifacts/kraken/20260713-040411/files/deploy_yamls/k_range_inventory_ladder_xmr_usd_auto_20260713.yml
  wrote deployable YAML artifacts/kraken/20260713-040411/files/deploy_yamls/k_range_inventory_ladder_xmr_usdt_auto_20260713.yml
  wrote deployable YAML artifacts/kraken/20260713-040411/files/deploy_yamls/k_range_inventory_ladder_xpl_usd_auto_20260713.yml

6 deployable YAMLs -> artifacts/kraken/20260713-040411/files/deploy_yamls (see INDEX.md)
Read: artifacts/kraken/20260713-040411/files/KRAKEN_recycle_v9_copy_paste_ladders.md

In [10]:
# ── Cell 10: VERIFY THE BOOKS for the shortlist ───────────────────────
# v11.2: reports the full DEPTH PROFILE (+-2/5/10/25% + whole book) and the
# depth inside each market's OWN deployed ladder span. A fixed +-2% reading
# misjudges ladder-shaped books: NonKYC DASH/USDT quotes dust at the touch
# and parks real size ~2.6% out (+-2% = $2, +-5% = $29,820, book = $33,509).
short = final_df[((final_df.holdout_edge_pct > 1) &
                  (final_df.clean_edge_pos_rate >= 0.6)) |
                 (final_df.validation != 'SUSPECT')]
short_pairs = list(short.base.head(12))
print('verifying books for:', short_pairs)
lads = {pk: evals[pk]['deployed'] for pk in short_pairs if pk in evals}
book_df = lr.verify_books(uni, short_pairs, CFG, samples=5, pause=4.0, ladders=lads)
display(book_df)
book_df.to_csv(f'{PREFIX}_book_verification.csv', index=False)
print('READ THE PROFILE, not one band:')
print('  depth_2pct tiny but depth_5pct large -> dust quoted at the touch, real size')
print('     parked further out. NOT a thin market -- depth_ladder_band is the truth.')
print('  depth_ladder_band = liquidity inside YOUR rungs (what can actually fill them).')
print('  flaky=True -> book swinging >5x across samples; trust no single reading.')
print('  thin_med=True with steady samples -> genuinely thin: size down or skip.')

verifying books for: ['XMR/USD', 'XMR/USDT', 'SPACE/USD', 'STABLE/USD', 'XPL/USD', 'DASH/USD', 'PTB/USD', 'APR/USD', 'B2/USD', 'NIL/USD', 'PLAY/USD', 'BMB/USD']
  book check XMR/USD: {'market': 'XMR/USD', 'samples_ok': 5, 'spread_pct': 0.0308, 'book_total_usd': 3614883.0, 'n_bids': 500.0, 'n_asks': 500.0, 'depth_2pct': 1069385.0, 'depth_5pct': 2288222.0, 'depth_10pct': 2501917.0, 'depth_25pct': 3097487.0, 'flaky': False, 'depth_ladder_band': 2751082.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check XMR/USDT: {'market': 'XMR/USDT', 'samples_ok': 5, 'spread_pct': 0.0801, 'book_total_usd': 1304606727.0, 'n_bids': 170.0, 'n_asks': 408.0, 'depth_2pct': 1088572.0, 'depth_5pct': 2129727.0, 'depth_10pct': 2259582.0, 'depth_25pct': 2462155.0, 'flaky': False, 'depth_ladder_band': 2373658.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check SPACE/USD: {'market': 'SPACE/USD', 'samples_ok': 5, 'spread_pct': 0.0661, 'book_total_usd': 292775.0, 'n_bids': 74.0, 'n_asks': 87.0, 'depth_2pct': 16876.0, 'depth_5pct': 19828.0, 'depth_10pct': 24602.0, 'depth_25pct': 27278.0, 'flaky': False, 'depth_ladder_band': 22083.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check STABLE/USD: {'market': 'STABLE/USD', 'samples_ok': 5, 'spread_pct': 0.0275, 'book_total_usd': 160480.0, 'n_bids': 67.0, 'n_asks': 46.0, 'depth_2pct': 42242.0, 'depth_5pct': 56990.0, 'depth_10pct': 59811.0, 'depth_25pct': 114478.0, 'flaky': False, 'depth_ladder_band': 72019.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check XPL/USD: {'market': 'XPL/USD', 'samples_ok': 5, 'spread_pct': 0.1137, 'book_total_usd': 2097971.0, 'n_bids': 98.0, 'n_asks': 311.0, 'depth_2pct': 194249.0, 'depth_5pct': 228215.0, 'depth_10pct': 245310.0, 'depth_25pct': 288289.0, 'flaky': False, 'depth_ladder_band': 276915.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check DASH/USD: {'market': 'DASH/USD', 'samples_ok': 5, 'spread_pct': 0.0811, 'book_total_usd': 2041993.0, 'n_bids': 428.0, 'n_asks': 500.0, 'depth_2pct': 255364.0, 'depth_5pct': 377708.0, 'depth_10pct': 442730.0, 'depth_25pct': 671865.0, 'flaky': False, 'depth_ladder_band': 663726.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check PTB/USD: {'market': 'PTB/USD', 'samples_ok': 5, 'spread_pct': 0.4167, 'book_total_usd': 2015493.0, 'n_bids': 44.0, 'n_asks': 177.0, 'depth_2pct': 4415.0, 'depth_5pct': 9660.0, 'depth_10pct': 13223.0, 'depth_25pct': 15168.0, 'flaky': False, 'depth_ladder_band': 9227.0, 'thin_med': False, 'size_suggestion': 4614.0}
  book check APR/USD: {'market': 'APR/USD', 'samples_ok': 5, 'spread_pct': 0.3901, 'book_total_usd': 56719.0, 'n_bids': 43.0, 'n_asks': 33.0, 'depth_2pct': 14783.0, 'depth_5pct': 18669.0, 'depth_10pct': 29833.0, 'depth_25pct': 33502.0, 'flaky': False, 'depth_ladder_band': 6087.0, 'thin_med': False, 'size_suggestion': 3044.0}
  book check B2/USD: {'market': 'B2/USD', 'samples_ok': 5, 'spread_pct': 0.2603, 'book_total_usd': 63774.0, 'n_bids': 28.0, 'n_asks': 37.0, 'depth_2pct': 5720.0, 'depth_5pct': 6298.0, 'depth_10pct': 23390.0, 'depth_25pct': 24052.0, 'flaky': False, 'depth_ladder_band': 24052.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check NIL/USD: {'market': 'NIL/USD', 'samples_ok': 5, 'spread_pct': 0.2861, 'book_total_usd': 575243.0, 'n_bids': 30.0, 'n_asks': 68.0, 'depth_2pct': 55976.0, 'depth_5pct': 73017.0, 'depth_10pct': 74353.0, 'depth_25pct': 83371.0, 'flaky': False, 'depth_ladder_band': 81239.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check PLAY/USD: {'market': 'PLAY/USD', 'samples_ok': 5, 'spread_pct': 0.1551, 'book_total_usd': 872687.0, 'n_bids': 144.0, 'n_asks': 316.0, 'depth_2pct': 8714.0, 'depth_5pct': 40418.0, 'depth_10pct': 44891.0, 'depth_25pct': 77490.0, 'flaky': False, 'depth_ladder_band': 45737.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check BMB/USD: {'market': 'BMB/USD', 'samples_ok': 5, 'spread_pct': 4.9841, 'book_total_usd': 56600.0, 'n_bids': 78.0, 'n_asks': 102.0, 'depth_2pct': 0.0, 'depth_5pct': 1627.0, 'depth_10pct': 3842.0, 'depth_25pct': 8929.0, 'flaky': False, 'depth_ladder_band': 7945.0, 'thin_med': False, 'size_suggestion': 3973.0}

,market,samples_ok,spread_pct,book_total_usd,n_bids,n_asks,depth_2pct,depth_5pct,depth_10pct,depth_25pct,flaky,depth_ladder_band,thin_med,size_suggestion
0,XMR/USD,5,0.0308,3.614883e+06,500.0,500.0,1069385.0,2288222.0,2501917.0,3097487.0,False,2751082.0,False,10000.0
1,XMR/USDT,5,0.0801,1.304607e+09,170.0,408.0,1088572.0,2129727.0,2259582.0,2462155.0,False,2373658.0,False,10000.0
2,SPACE/USD,5,0.0661,2.927750e+05,74.0,87.0,16876.0,19828.0,24602.0,27278.0,False,22083.0,False,10000.0
3,STABLE/USD,5,0.0275,1.604800e+05,67.0,46.0,42242.0,56990.0,59811.0,114478.0,False,72019.0,False,10000.0
4,XPL/USD,5,0.1137,2.097971e+06,98.0,311.0,194249.0,228215.0,245310.0,288289.0,False,276915.0,False,10000.0
5,DASH/USD,5,0.0811,2.041993e+06,428.0,500.0,255364.0,377708.0,442730.0,671865.0,False,663726.0,False,10000.0
6,PTB/USD,5,0.4167,2.015493e+06,44.0,177.0,4415.0,9660.0,13223.0,15168.0,False,9227.0,False,4614.0
7,APR/USD,5,0.3901,5.671900e+04,43.0,33.0,14783.0,18669.0,29833.0,33502.0,False,6087.0,False,3044.0
8,B2/USD,5,0.2603,6.377400e+04,28.0,37.0,5720.0,6298.0,23390.0,24052.0,False,24052.0,False,10000.0
9,NIL/USD,5,0.2861,5.752430e+05,30.0,68.0,55976.0,73017.0,74353.0,83371.0,False,81239.0,False,10000.0
10,PLAY/USD,5,0.1551,8.726870e+05,144.0,316.0,8714.0,40418.0,44891.0,77490.0,False,45737.0,False,10000.0
11,BMB/USD,5,4.9841,5.660000e+04,78.0,102.0,0.0,1627.0,3842.0,8929.0,False,7945.0,False,3973.0

READ THE PROFILE, not one band:
  depth_2pct tiny but depth_5pct large -> dust quoted at the touch, real size
     parked further out. NOT a thin market -- depth_ladder_band is the truth.
  depth_ladder_band = liquidity inside YOUR rungs (what can actually fill them).
  flaky=True -> book swinging >5x across samples; trust no single reading.
  thin_med=True with steady samples -> genuinely thin: size down or skip.

In [11]:
# ── Cell 11 (optional): calibrate the fill model against LIVE fills ───
# Point each pair at ONE OR MANY controller diagnostic JSONL files -- a single
# path, a list, and/or glob patterns. Rotated/overlapping logs are safe: fills
# are merged chronologically and deduplicated on (ts, side, price, amount).
#
# How much data is meaningful (rule of thumb: count error ~ 1/sqrt(N fills)):
#   < 15 fills / <10d  -> directional hint only, do NOT tune knobs
#   30+ fills, 15d+    -> first honest sim/live ratio (one full block)
#   60+ fills, 30d+    -> tune rc_volume_cap_frac / rc_fill_penetration_pct
#                         until sim_over_live_fill_ratio ~= 0.8-1.2
# If your controllers have been logging since deployment, you may already
# have months of data -- point globs at the whole log directory.
DIAG_FILES = {
    # 'XMR/USDT': '/path/to/xmr_diag.jsonl',                       # single file
    # 'XMR/USDT': ['/logs/xmr_*.jsonl', '/old_logs/xmr_2026*.jsonl'],  # globs+lists
}
DIAG_FILES = {
    'XMR/USD': ['./diagnostics/kraken/range_inventory_ladder_xmr_usd_diagnostic*.jsonl'],  # globs+lists
}

for pk, paths in DIAG_FILES.items():
    print(f'=== {pk} ===')
    fills = lr.collect_jsonl_fills(paths)
    print(lr.fills_sufficiency(fills))
    if fills.empty:
        first = lr.first_existing(paths)          # glob-safe (v11.1.2 fix)
        if first is None:
            print(f'no files matched: {paths} -- check the path/glob')
        else:
            print(f'no fills extracted from {first} -- schema sniff:')
            display(lr.summarize_diagnostic_jsonl(first))
        continue
    print(fills.groupby('source_file').size().to_string())
    ladder = next((lr.controller_to_ladder(p, CFG) for p in yamls
                   if lr._pair_key(p['trading_pair']) == pk), None)
    h = hist_report.get(pk, hist_h.get(pk))
    if ladder is not None and h is not None:
        pdec = uni.get('pdec', {}).get(pk)
        book_half = lr.market_book_half_spread_pct(uni, pk, CFG)
        cfg_m, _ = lr.quote_scaled_cfg(uni, pk, CFG)
        cmp_ = lr.compare_live_vs_sim_v11(fills, h['bars'], ladder, cfg_m,
                                          pdec=pdec, book_half=book_half)
        for k, v in cmp_.items():
            print(f'  {k:28s} {v}')
    else:
        print('  (no matching controller YAML or history for the sim side)')

# refresh the health table with live-fill recency, now that fills are loaded
if DIAG_FILES and yaml_reports:
    fills_map = {pk: lr.collect_jsonl_fills(paths) for pk, paths in DIAG_FILES.items()}
    health = lr.live_strategy_health(yaml_df, yaml_reports, CFG, fills_by_pair=fills_map)
    lr.print_health_banners(health)
    display(health)
    health.to_csv(f'{PREFIX}_live_health.csv', index=False)

=== XMR/USD ===
1 fill(s), window ~0.0h -> TOO THIN: a rate needs at least a few fills spread over time; keep logging
source_file
./diagnostics/kraken/range_inventory_ladder_xmr_usd_diagnostic_20260709-1747-20260709-174713.jsonl    1
  note                         only 1 fill(s) over 0.0h -- no meaningful rate; keep logging
  fills_sufficiency            1 fill(s), window ~0.0h -> TOO THIN: a rate needs at least a few fills spread over time; keep logging

,controller,pair,status,recent_blocks,recent_days,recent_pnl_pct,recent_hold_pct,recent_edge_pct,recent_trades,recent_two_sided_blocks,last_block_pnl_pct,full_pnl_pct,full_edge_pct,days_since_live_fill
0,k_range_inventory_ladder_dash_eur_V1,DASH/EUR,HEALTHY,3,45.0,15.50,0.0,15.50,23,3,1.799,69.474,69.474,NaN
1,k_range_inventory_ladder_xmr_usd_V1,XMR/USD,HEALTHY,3,45.0,16.43,-5.7,22.13,177,3,7.928,-8.182,32.687,0.6

## Reading the results (v11 evidence hierarchy)

Work down this list; each level is weaker evidence than the one above it.

1. **`holdout_edge_pct`** (Cell 9 holdout view / `*_holdout_summary.csv`) — the fitted,
   train-anchored ladder on 15 days it never saw. This is the only fully out-of-sample
   number for the geometry you deploy. Positive and two-sided ⇒ real signal; dormant
   (`holdout_active=False`) ⇒ no evidence either way, and the gate says so.
2. **Clean blocks** (`clean_edge_pos_rate`, `clean_worst_block_edge`) — the frozen report's
   blocks that do *not* overlap the fit window. The headline `edge_pct`/`edge_pos_rate`
   still include the fit window (kept for v10 comparability) — prefer the clean ones.
3. **Your live YAMLs** (Cell 6) — ground truth for the fill model itself. If the sim's
   trades/block is far from your JSONL fills, recalibrate in Cell 11 before trusting anything.
4. **Rolling WF** — validates the *fitting process*, not the deployed ladder. A wf_pass with
   a bad holdout means the process is fine but this particular fit is a bad draw: refit later.
5. **`harvest_best_pct_mo`** — model-free ceiling on what any grid can extract at cost.
   If it's near zero, no amount of ladder tuning will make the pair work.

`vol_capped_fills` > 0 tells you the book, not the price path, limited the sim — size DOWN
(`max_fund_value_quote`) rather than dismissing the pair. `fit_score_gap` large (≫ typical)
suggests the winner is a lucky draw among 240 candidates — prefer pairs where holdout,
clean blocks *and* WF agree.

**Kraken note:** most USD pairs are evaluated on MEXC USDT-proxy candles (src `MEXC(XXXUSDT)`) — the last-price guard rejects the proxy when it diverges >5% from Kraken's own ticker. Pairs stuck on `Kraken(720cap)` hourly have only ~30d of history: their reports are short and the holdout may be skipped — treat those as screening-only results.

**Deployment discipline:** deploy only `CONFIRMED`, at the suggested `max_fund_value_quote`
or less, and treat the FIRST live 15-day block as the final gate — if it underperforms the
holdout badly, stop and recalibrate (Cell 11) instead of re-fitting harder.