# Crypto oscillator finder — NONKYC v11 (`recycle_v11` engine)

**v11.1** adds: a dust filter (`min_vol_usd`), quote-unit conversion for crypto-quoted
pairs (fund / min-order / volume-cap all in the pair's quote currency; exports carry both
`max_fund_value_quote` in quote units and `max_fund_value_usd`), finalize reusing the same
order-book snapshot the engine already sampled (no spurious spread gates), the
`rc_gate_two_sided_mode` holdout waiver, and a book-verification cell (Cell 10).

**What changed vs v10** (full details in `LadderLab_v11_notes_claude_code.md`):

1. **True holdout** — the deploy ladder is fitted *without* the last 15 days; the fitted,
   train-anchored ladder is scored once on that unseen tail. `holdout_edge_pct` is the only
   fully out-of-sample number for the geometry you deploy, and it gates deployment.
2. **Clean-block gating** — the 180d frozen report tags blocks that overlap the fit window
   (`in_fit`); the band-aware v10 gates must now pass on the *clean* blocks too.
3. **Fill realism** — fills require price to trade *through* the rung
   (`rc_fill_penetration_pct` + 1 tick), and per-bar filled notional is capped at
   `rc_volume_cap_frac` × the bar's quote volume, with partial fills (bars now carry volume).
4. **Slip symmetry** — the measured live order-book half-spread joins Roll + floor in the
   *search and WF*, not just as a finalize gate.
5. **Grid-harvest screen** — a model-free zig-zag swing count (net of round-trip cost) ranks
   the review set; it cannot overfit because nothing is fitted.
6. **Deep history** — MEXC-first Nx6 (with volume) history (NonKYC-native 5m first for report bars).

Nothing was removed from the v10 reports — v11 only adds columns/files. The
`*_copy_paste_ladders.md` is rendered by v10's renderer, byte-identical format.

In [1]:
# ── Cell 1: bootstrap ────────────────────────────────────────────────
# numba makes the engine ~50-100x faster; strongly recommended.
import sys, subprocess
for _mod, _pkg in (('numba', 'numba'), ('tabulate', 'tabulate')):
    try:
        __import__(_mod)
    except ImportError:
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', _pkg], check=False)

import importlib, os, time, json
from pathlib import Path
import numpy as np
import pandas as pd

import ladder_lab as ll
import ladder_lab_recycle as lr10          # v10 stays installed; v11 reuses it
import ladder_lab_recycle_v11 as lr
importlib.reload(ll); importlib.reload(lr10); importlib.reload(lr)

EXCHANGE = 'nonkyc'

print(f'ladder_lab {ll.__version__} | v10 {lr10.__version__} | v11 {lr.__version__} | numba={ll.HAVE_NUMBA}')
assert ll.parity_check(), 'base kernel parity FAILED'
assert lr10.recycle_parity_check(), 'v10 kernel parity FAILED'
assert lr.recycle_v11_parity_check(verbose=True), 'v11 kernel parity / v10-equivalence FAILED'
print('kernel parity OK (v11 reproduces v10 exactly with realism features off)')

CFG = lr.recycle_default_config(EXCHANGE)
# ---- knobs you will most likely touch ----
CFG['always_review_markets'] = ('XMR/USDT', 'XMR/USD', 'SAL/USDT')
CFG['focus_markets']         = ('ZANO/USDT', 'DASH/USDT', 'SUN/USDT')
CFG['rc_top_n_from_screen']  = 40      # markets from the screener that get the full engine
CFG['rc_n_candidates']       = 240     # per fit; drop to ~80 if running without numba
CFG['rc_target_trades_per_15d'] = 40   # recalibrate with the diagnostic-JSONL cell at the bottom
CFG['rc_report_interval']    = '5m'    # frozen reports / YAML eval / holdout on 5m bars
# ---- v11 realism knobs (defaults are the recommended settings) ----
CFG['rc_holdout_days']         = 15    # fit never sees the last N days (0 disables; don't)
CFG['rc_fill_penetration_pct'] = 0.0005  # price must trade 5bps+1tick THROUGH a rung to fill
CFG['rc_volume_cap_frac']      = 0.25  # max share of a bar's quote volume we may fill
CFG['rc_book_spread_in_slip']  = True  # live half-spread joins Roll+floor in search/WF too
# ---- v11.1 knobs ----
CFG['min_vol_usd']             = 10_000  # DUST FILTER: drop markets under this 24h USD volume
                                         # (the first run spent ~90% of engine time on books
                                         #  that could not absorb even the $200 fund floor)
CFG['rc_gate_two_sided_mode']  = 'either'  # 'blocks'=v10 | 'holdout' | 'either' (waive the
                                         # block two-sided gate when the HOLDOUT was two-sided;
                                         # re-anchored ladders are structurally one-sided vs a
                                         # trending past -- the holdout has no such bias)
# CFG['rc_v11_fill_model'] = False     # A/B: byte-identical v10 fills (leave True to deploy)

# Where your live controller YAMLs live (searched recursively):
YAML_ROOTS = ['.', 'controllers', str(Path.home())]
YAML_ROOTS = ['./controllers/nonkyc']

# artifacts/{exchange}/{timestamp}/files
RUN_TS = time.strftime('%Y%m%d-%H%M%S')
ART = Path('artifacts') / EXCHANGE / RUN_TS / 'files'
ART.mkdir(parents=True, exist_ok=True)
PREFIX = str(ART / f'NONKYC_recycle_v11')
print('artifacts →', ART)

ladder_lab 1.0.0 | v10 10.2.0-recycle-rollspread-bandgates | v11 11.3.1-resilient-universe | numba=True
  series 0: v10-equiv=OK trades=20
  series 1: v10-equiv=OK trades=27
  series 2: v10-equiv=OK trades=18
  series 3: v10-equiv=OK trades=17
kernel parity OK (v11 reproduces v10 exactly with realism features off)
artifacts → artifacts/nonkyc/20260713-040416/files

In [2]:
# ── Cell 2: universe ─────────────────────────────────────────────────
# v11.1.3: build the universe WITHOUT the volume floor so live-YAML and
# always-review markets can never be starved of history (a live ZANO ladder
# was silently dropped when its 24h volume dipped under the floor). The dust
# filter is applied in Cell 4 to the SCREENED candidates only -- engine time
# is still protected, your own markets always get evaluated.
# v11.3.1: patient retries (15/30/45/60s -- outlasts a rate-limit window)
# and a loud fallback to the last good universe cached on disk (<=48h old),
# so a flaky /market/getlist costs freshness, not the whole run.
uni = lr.build_universe(EXCHANGE, CFG)
VOL_USD = dict(zip(uni['df'].pairkey, uni['df'].vol_usd))
cache = ll.CandleCache(CFG['cache_dir'], CFG['cache_ttl_hours'])

338 nonkyc markets across 13 quote(s) >= $0 24h vol (USD-equiv).
  by quote: USDT:231, USDC:35, BTC:32, XMR:11, ETH:10, DOGE:7, ZSD:3, BNB:3, ERG:2, FUSD:1, LTC:1, SOL:1, EGAZ:1

In [3]:
# ── Cell 3: daily history + screener (breadth pass, unchanged from base) ──
hist_d = ll.prefetch_history(uni, CFG, cache)
screen_df = ll.screen(uni, hist_d, CFG)
screen_df = lr.drop_stable_stable(screen_df, CFG)
screen_df.head(25)

  ...MEXC pass 50/338
  ...MEXC pass 100/338
  ...MEXC pass 150/338
  ...MEXC pass 200/338
  ...MEXC pass 250/338
  ...MEXC pass 300/338
  native fallback for 212 markets (small pool) ...
history: 326/338 markets in 124s (MEXC 126, native 200, missing 12)
  dropped 4 stable/stable pairs from consideration

,days,price,low,high,ann_vol,er,cross_per_yr,in_band,net_return,cur_vs_high,...,coin,quote,src,vol_usd,min_qty,stale,tier,range_x,qualifies,composite
0,184,7.000000e-06,5.814500e-06,1.183550e-05,3.494227,0.015285,91.250000,0.597826,-0.263933,0.549882,...,SATOX,USDT,NonKYC,5.38,0.0,False,full,2.04,True,0.979
1,217,9.129100e-04,6.799600e-04,9.129100e-04,3.083984,0.060747,77.373272,0.599078,0.292634,0.906501,...,SLDX,USDT,NonKYC,8.05,0.0,False,full,1.34,True,0.977
2,217,1.686000e-07,1.625600e-07,2.642000e-07,3.231886,0.040795,67.281106,0.603687,-0.361847,0.140512,...,PDOGE,USDT,NonKYC,47.59,0.0,False,full,1.63,True,0.969
3,220,1.675000e-01,1.600950e-01,3.901750e-01,2.973905,0.055147,69.681818,0.604545,-0.630813,0.260863,...,ZCL,USDT,NonKYC,152.26,0.0,False,full,2.44,True,0.957
4,220,1.288000e-03,1.085090e-03,1.553760e-03,1.594886,0.022852,81.295455,0.600000,-0.222739,0.697989,...,DIVI,USDT,NonKYC,31713.52,0.0,False,full,1.43,True,0.945
5,220,9.771640e-04,1.051907e-03,2.379889e-03,4.160283,0.051000,49.772727,0.600000,-0.513351,0.299164,...,PEP,DOGE,NonKYC,3024.61,0.0,False,full,2.26,True,0.939
6,218,6.156900e-02,6.470555e-02,1.040195e-01,12.508760,0.126623,41.857798,0.605505,-0.403534,0.591168,...,CHESS,USDC,NonKYC,679.94,0.0,False,full,1.61,True,0.935
7,217,7.810000e-09,6.316000e-09,1.055800e-08,3.282188,0.002490,45.414747,0.603687,0.044118,0.282051,...,DOGS,USDT,NonKYC,4.14,0.0,False,full,1.67,True,0.922
8,217,2.908600e-10,2.837460e-10,3.633000e-10,6.511288,0.000090,33.640553,0.594470,-0.000550,0.739612,...,PDOGE,BNB,NonKYC,4.38,0.0,False,full,1.28,True,0.919
9,219,5.021900e-06,5.006040e-06,1.153501e-05,2.564428,0.041049,55.000000,0.598174,-0.517097,0.379507,...,XLA,USDT,NonKYC,28.56,0.0,False,full,2.30,True,0.913
10,219,1.284000e-05,8.089000e-06,2.009800e-05,2.505741,0.018495,51.666667,0.607306,-0.256944,0.408917,...,IXI,USDT,NonKYC,88.08,0.0,False,full,2.48,True,0.910
11,220,8.069120e-01,5.137013e-01,1.299995e+00,4.273979,0.025232,48.113636,0.600000,0.724226,0.487084,...,TDC,DOGE,NonKYC,17.08,0.0,False,full,2.53,True,0.909
12,220,3.612900e-02,3.060485e-02,6.463095e-02,2.350918,0.018994,49.772727,0.613636,-0.298316,0.391049,...,BCA,USDT,NonKYC,57.61,0.0,False,full,2.11,True,0.904
13,220,6.990400e+00,4.481785e+00,1.069181e+01,1.919321,0.036667,71.340909,0.600000,-0.319722,0.609090,...,HACD,USDT,NonKYC,3263.13,0.0,False,full,2.39,True,0.902
14,220,1.826590e-01,1.071454e-01,2.192464e-01,1.778506,0.009324,63.045455,0.600000,0.108206,0.761082,...,QORT,USDT,NonKYC,396.03,0.0,False,full,2.05,True,0.897
15,217,8.646000e-05,1.052480e-04,2.447700e-04,2.600875,0.075297,47.096774,0.603687,-0.603649,0.283857,...,DOGGGO,USDT,NonKYC,45.07,0.0,False,full,2.33,True,0.893
16,217,2.198770e-03,2.700182e-03,3.738518e-03,1.494251,0.038474,50.460829,0.594470,-0.269873,0.364539,...,BSOV,USDT,NonKYC,7.89,0.0,False,full,1.38,True,0.890
17,220,6.232000e-03,6.294350e-03,1.575680e-02,1.773079,0.078510,69.681818,0.600000,-0.633649,0.344309,...,CCX,USDT,NonKYC,43.63,0.0,False,full,2.50,True,0.886
18,220,2.850000e-06,1.470000e-06,2.660500e-06,1.710219,0.041467,49.772727,0.618182,0.574586,0.937500,...,QORT,BTC,NonKYC,44.61,0.0,False,full,1.81,True,0.877
19,220,8.280000e-09,6.174000e-09,1.489500e-08,2.606933,0.037758,41.477273,0.600000,-0.442049,0.450000,...,DOSU,DOGE,NonKYC,3.25,0.0,False,full,2.41,True,0.875
20,220,3.345230e+02,3.202397e+02,5.225957e+02,2.114709,0.017065,36.500000,0.600000,-0.160001,0.346656,...,XMR,ZSD,NonKYC,58.64,0.0,False,full,1.63,True,0.869
21,217,3.287500e-02,3.187200e-02,4.133700e-02,3.728944,0.017893,31.958525,0.603687,-0.227089,0.131501,...,BTCP,USDT,NonKYC,0.63,0.0,False,full,1.30,True,0.867
22,220,9.800000e-08,8.690000e-08,1.901000e-07,1.819000,0.047778,53.090909,0.604545,-0.467391,0.478049,...,CCX,BTC,NonKYC,0.00,0.0,False,full,2.19,True,0.865
23,220,2.548970e-07,1.766926e-07,6.350266e-07,3.230323,0.017606,51.431818,0.600000,-0.382572,0.252895,...,SHA,BTC,NonKYC,6.37,0.0,False,full,3.59,True,0.865
24,220,2.049000e-03,1.775800e-03,3.659200e-03,1.674918,0.065300,59.727273,0.600000,-0.494074,0.406871,...,FREED,USDT,NonKYC,2052.98,0.0,False,full,2.06,True,0.863

In [4]:
# ── Cell 4: pick the markets that get the full engine ────────────────
# v11: the model-free grid-harvest rank (zig-zag swings net of round-trip cost)
# is blended with the base composite. harvest_* columns are on DAILY bars here
# (breadth); the engine recomputes them on intraday bars for the finalists.
yamls = lr.discover_controller_yamls(YAML_ROOTS, exchange=EXCHANGE)
yaml_markets = [lr._pair_key(p['trading_pair']) for p in yamls]
print(f'controller YAMLs found: {len(yamls)} → {yaml_markets}')

ranked = lr.rank_review_markets(screen_df, hist_d, CFG)
display(ranked.head(25))

col = 'base' if 'base' in ranked.columns else 'pairkey'
# dust filter applies HERE (screened candidates only); YAML/always/focus bypass
eligible = [pk for pk in ranked[col] if VOL_USD.get(pk, 0) >= CFG['min_vol_usd']]
dropped = len(ranked) - len(eligible)
if dropped:
    print(f'dust filter: {dropped} screened markets under ${CFG["min_vol_usd"]:,.0f} 24h volume')
top_screen = eligible[:CFG['rc_top_n_from_screen']]
wanted = lr.merge_unique_markets(top_screen, CFG['always_review_markets'],
                                 CFG['focus_markets'], yaml_markets)
review, missing = lr.resolve_present(uni, wanted)
if missing:
    print('not on this exchange / below volume floor:', missing)
print(f'{len(review)} markets selected for the v11 engine')

controller YAMLs found: 4 → ['DASH/USDT', 'SUN/USDT', 'XMR/USDT', 'ZANO/USDT']

,base,days,price,low,high,ann_vol,er,cross_per_yr,in_band,net_return,...,range_x,qualifies,composite,harvest_rt_cost_pct,harvest_1.5x_pct_mo,harvest_2x_pct_mo,harvest_3x_pct_mo,harvest_best_pct_mo,harvest_best_gap_pct,review_rank
0,SATOX/USDT,184,7.000000e-06,5.814500e-06,1.183550e-05,3.494227,0.015285,91.250000,0.597826,-0.263933,...,2.04,True,0.979,12.400,15.960,21.280,13.680,21.280,24.800,0.970
1,BCA/USDT,220,3.612900e-02,3.060485e-02,6.463095e-02,2.350918,0.018994,49.772727,0.613636,-0.298316,...,2.11,True,0.904,8.670,12.487,21.786,22.318,22.318,26.009,0.960
2,ZCL/USDT,220,1.675000e-01,1.600950e-01,3.901750e-01,2.973905,0.055147,69.681818,0.604545,-0.630813,...,2.44,True,0.957,12.400,13.680,17.480,19.760,19.760,37.200,0.954
3,SHA/BTC,220,2.548970e-07,1.766926e-07,6.350266e-07,3.230323,0.017606,51.431818,0.600000,-0.382572,...,3.59,True,0.865,11.599,13.863,22.039,24.171,24.171,34.798,0.948
4,CCX/BTC,220,9.800000e-08,8.690000e-08,1.901000e-07,1.819000,0.047778,53.090909,0.604545,-0.467391,...,2.19,True,0.865,5.787,7.981,13.834,20.573,20.573,17.362,0.928
5,DOSU/DOGE,220,8.280000e-09,6.174000e-09,1.489500e-08,2.606933,0.037758,41.477273,0.600000,-0.442049,...,2.41,True,0.875,11.428,9.806,14.009,19.613,19.613,34.285,0.927
6,BCH2/USDT,113,1.586542e-02,1.588814e-02,9.898972e-02,3.234294,0.187775,51.681416,0.592920,-0.880189,...,6.23,False,0.787,10.876,16.975,30.998,32.474,32.474,32.629,0.925
7,CCX/USDT,220,6.232000e-03,6.294350e-03,1.575680e-02,1.773079,0.078510,69.681818,0.600000,-0.633649,...,2.50,True,0.886,7.329,9.208,14.823,18.865,18.865,21.986,0.925
8,IXI/USDT,219,1.284000e-05,8.089000e-06,2.009800e-05,2.505741,0.018495,51.666667,0.607306,-0.256944,...,2.48,True,0.910,11.420,9.799,16.799,16.799,16.799,22.840,0.925
9,FLOP/USDT,220,3.518000e-07,2.087950e-07,9.836150e-07,3.217507,0.019196,33.181818,0.600000,-0.360945,...,4.71,True,0.784,12.400,14.440,22.800,31.920,31.920,37.200,0.922
10,XNV/XMR,164,3.750000e-04,1.379110e-04,5.244345e-04,3.392525,0.084983,35.609756,0.597561,5.991051,...,3.80,True,0.838,12.400,10.985,17.345,20.814,20.814,37.200,0.918
11,PRCY/USDT,220,1.059000e-03,7.605500e-04,1.766050e-03,2.550729,0.007420,33.181818,0.600000,-0.126958,...,2.32,True,0.831,12.400,9.880,16.720,21.280,21.280,37.200,0.918
12,HACD/USDT,220,6.990400e+00,4.481785e+00,1.069181e+01,1.919321,0.036667,71.340909,0.600000,-0.319722,...,2.39,True,0.902,9.626,11.800,15.340,11.800,15.340,19.253,0.915
13,DOSU/USDT,220,6.150000e-10,5.790000e-10,1.955450e-09,2.717391,0.085517,33.181818,0.600000,-0.704327,...,3.38,True,0.804,11.042,9.475,14.889,21.656,21.656,33.125,0.913
14,QORT/BTC,220,2.850000e-06,1.470000e-06,2.660500e-06,1.710219,0.041467,49.772727,0.618182,0.574586,...,1.81,True,0.877,6.517,9.865,15.620,16.442,16.442,19.552,0.910
15,FNNC/DOGE,220,1.433837e-02,1.434902e-02,7.820335e-02,3.468949,0.048761,36.500000,0.600000,-0.726842,...,5.45,True,0.760,12.400,10.260,15.960,28.880,28.880,37.200,0.909
16,QORT/USDT,220,1.826590e-01,1.071454e-01,2.192464e-01,1.778506,0.009324,63.045455,0.600000,0.108206,...,2.05,True,0.897,7.839,8.652,14.338,12.855,14.338,15.678,0.901
17,DOGGGO/USDT,217,8.646000e-05,1.052480e-04,2.447700e-04,2.600875,0.075297,47.096774,0.603687,-0.603649,...,2.33,True,0.893,12.400,5.700,11.400,13.680,13.680,37.200,0.894
18,BTCE/DOGE,219,2.797630e-01,5.737600e-02,4.069220e-01,3.666014,0.007914,45.000000,0.602740,-0.134440,...,7.09,True,0.794,12.400,8.360,15.200,19.760,19.760,37.200,0.892
19,SHA/USDT,220,1.627500e-02,1.372905e-02,5.484825e-02,2.738240,0.033435,48.113636,0.600000,-0.567442,...,4.00,True,0.788,2.656,6.267,11.557,19.859,19.859,7.968,0.890
20,NOOK/USDT,220,4.564000e-12,3.123180e-12,5.152205e-12,1.248453,0.021969,61.386364,0.600000,-0.113339,...,1.65,True,0.850,6.198,6.268,8.738,14.436,14.436,18.595,0.882
21,DOGS/USDT,217,7.810000e-09,6.316000e-09,1.055800e-08,3.282188,0.002490,45.414747,0.603687,0.044118,...,1.67,True,0.922,12.400,6.460,11.400,12.160,12.160,37.200,0.882
22,ETI/EGAZ,218,1.421860e+01,8.493350e+00,1.574240e+01,2.338839,0.024579,83.715596,0.596330,0.577265,...,1.85,True,0.863,12.400,8.360,13.680,12.160,13.680,24.800,0.880
23,DIVI/USDT,220,1.288000e-03,1.085090e-03,1.553760e-03,1.594886,0.022852,81.295455,0.600000,-0.222739,...,1.43,True,0.945,9.447,9.264,11.580,6.948,11.580,18.893,0.879
24,MEWC/USDT,220,2.046000e-05,1.716000e-05,5.346050e-05,2.491520,0.060614,36.500000,0.600000,-0.654917,...,3.12,True,0.739,9.559,12.889,22.263,22.263,22.263,28.676,0.878

dust filter: 264 screened markets under $10,000 24h volume
not on this exchange / below volume floor: ['XMR/USD']
42 markets selected for the v11 engine

In [5]:
# ── Cell 5: history — hourly Nx6 for search/WF/holdout, 5m Nx6 for reports ─
# v11 bars carry QUOTE VOLUME (column 6) so the sim can cap fills against what
# actually traded. Kraken pairs ride the MEXC proxy (USD→USDT alias, guarded by
# the last-price check); Kraken-native OHLC is a 30d fallback (720-candle cap).
hist_h = lr.prefetch_bars6(uni, CFG, cache, pairs=review, interval='60m',
                           min_days_key='rc_min_hourly_days')
hist_h = lr.with_daily_fallback(hist_h, hist_d, CFG, review)   # daily fallback is flagged
print(pd.Series({pk: v['granularity'] for pk, v in hist_h.items()}).value_counts().to_string())
vol_missing = [pk for pk, v in hist_h.items() if not v.get('vol_known', False)]
if vol_missing:
    print('volume unknown (volume cap disabled) for:', vol_missing)

if CFG['rc_report_interval'] not in ('60m', '1h'):
    hist_report = lr.prefetch_bars6(uni, CFG, cache, pairs=review,
                                    interval=CFG['rc_report_interval'],
                                    min_days_key='rc_min_intraday_days')
    print(pd.Series({pk: v['granularity'] for pk, v in hist_report.items()}).value_counts().to_string())
else:
    hist_report = hist_h
missing_5m = [pk for pk in review if pk in hist_h and pk not in hist_report]
if missing_5m:
    print('report falls back to search-granularity bars for:', missing_5m)

  ...bars6[60m] 10/42
  ...bars6[60m] 20/42
  ...bars6[60m] 30/42
  ...bars6[60m] 40/42
bars6(60m): 42/42 markets in 1s
1h    42
  ...bars6[5m] 10/42
  ...bars6[5m] 20/42
  ...bars6[5m] 30/42
  ...bars6[5m] 40/42
bars6(5m): 42/42 markets in 1s
5m    42

In [6]:
# ── Cell 6: YOUR live controller YAMLs, first-class, on the same engine ──
# Genuinely out-of-sample for any ladder you wrote before this window ends.
# v11 engine: penetration + volume caps + book-spread slip apply here too, so
# these numbers are the closest thing to a live replay in the whole pipeline.
yaml_hist = {pk: hist_report.get(pk, hist_h.get(pk)) for pk in set(list(hist_h) + list(hist_report))}
yaml_hist = {pk: v for pk, v in yaml_hist.items() if v is not None}
# Mark which YAMLs are LIVE (ground truth) vs untraded DRAFTS (hypotheses).
# Leave empty to treat them all as live; otherwise list deployed controller_ids.
DEPLOYED_CONTROLLERS = set()      # e.g. {'range_inventory_ladder_xmr_V1'}
yaml_df, yaml_reports = lr.evaluate_controller_yamls(yamls, yaml_hist, uni, CFG)
if not yaml_df.empty and 'controller' in yaml_df.columns and DEPLOYED_CONTROLLERS:
    yaml_df.insert(1, 'status', yaml_df.controller.map(
        lambda c: 'LIVE' if c in DEPLOYED_CONTROLLERS else 'DRAFT'))
    print('LIVE = deployed (ground truth) | DRAFT = never traded (a backtest of a proposal)')
if not yaml_df.empty:
    display(yaml_df)
    # ---- v11.3: LIVE-STRATEGY HEALTH -- recent form, judged on two axes ----
    # A 180-day headline can hide a strategy that died a month ago. This is
    # the table that makes "no longer profitable" impossible to miss.
    health = lr.live_strategy_health(yaml_df, yaml_reports, CFG)
    print()
    lr.print_health_banners(health)
    display(health)
    health.to_csv(f'{PREFIX}_live_health.csv', index=False)
    for cid, rep in yaml_reports.items():
        print(f"\n=== {cid} — passed={rep['passed']}"
              f"  {('; '.join(rep['failed_gates']) if rep['failed_gates'] else '')} ===")
        display(rep['blocks'])
else:
    print('no controller YAMLs matched this exchange — set YAML_ROOTS in Cell 1')

,controller,pair,src,days,blocks,pnl_pct,hold_pct,edge_pct,edge_pos_rate,abs_pos_rate,worst_block_edge,trades,trades_per_month,med_trades_per_block,maxdd,endinv,stress_edge_pct,vol_capped_fills,passed,failed_gates
0,range_inventory_ladder_dash_V1,DASH/USDT,NonKYC,180.0,12,11.262,-12.139,23.402,0.909,0.727,-5.400,219,37.0,17.0,29.814,3.0,20.904,65,True,
1,range_inventory_ladder_sun_V1,SUN/USDT,NonKYC,170.4,11,5.561,-10.066,15.627,0.700,0.636,-6.435,129,23.0,13.0,18.053,10.5,12.250,33,False,two_sided_rate 0.36 < 0.5 (active blocks); cle...
2,range_inventory_ladder_xmr_V1,XMR/USDT,NonKYC,180.0,12,-9.067,-43.524,34.457,0.727,0.778,-7.395,743,125.5,81.0,54.944,85.1,25.793,1,True,
3,range_inventory_ladder_zano_V1,ZANO/USDT,NonKYC,180.0,12,40.167,-9.256,49.423,0.778,0.455,-4.759,153,25.8,12.0,47.296,61.7,35.218,26,False,abs_pos_rate 0.45 < 0.5 (active blocks); clean...

,controller,pair,status,recent_blocks,recent_days,recent_pnl_pct,recent_hold_pct,recent_edge_pct,recent_trades,recent_two_sided_blocks,last_block_pnl_pct,full_pnl_pct,full_edge_pct
0,range_inventory_ladder_dash_V1,DASH/USDT,HEALTHY,3,45.0,6.25,-2.95,9.20,65,3,1.410,11.262,23.402
1,range_inventory_ladder_sun_V1,SUN/USDT,HEALTHY,3,45.0,7.47,-8.59,16.05,32,1,7.332,5.561,15.627
2,range_inventory_ladder_zano_V1,ZANO/USDT,HEALTHY,3,45.0,16.44,-1.57,18.00,38,3,6.872,40.167,49.423
3,range_inventory_ladder_xmr_V1,XMR/USDT,HEALTHY,3,45.0,18.92,-6.67,25.59,240,3,6.887,-9.067,34.457

=== range_inventory_ladder_dash_V1 — passed=True   ===

,block,start,end,days,pnl_pct,hold_pct,edge_pct,buy_fills,sell_fills,trades,two_sided,in_band_pct,in_fit,partial
0,1,2026-01-13,2026-01-28,15.0,1.874,1.874,0.000,0,0,0,False,0.000,False,False
1,2,2026-01-28,2026-02-12,15.0,-13.983,-14.625,0.642,3,7,10,True,0.810,False,False
2,3,2026-02-12,2026-02-27,15.0,0.625,0.072,0.552,8,15,23,True,1.000,False,False
3,4,2026-02-27,2026-03-14,15.0,3.633,-0.184,3.817,21,23,44,True,1.000,False,False
4,5,2026-03-14,2026-03-29,15.0,0.558,-0.927,1.485,18,7,25,True,1.000,False,False
5,6,2026-03-29,2026-04-13,15.0,17.390,6.159,11.231,25,12,37,True,0.963,False,False
6,7,2026-04-13,2026-04-28,15.0,-3.376,-3.958,0.581,0,14,14,False,1.000,False,False
7,8,2026-04-28,2026-05-13,15.0,0.491,5.891,-5.400,0,1,1,False,0.527,False,False
8,9,2026-05-13,2026-05-28,15.0,-0.250,-2.809,2.560,0,0,0,False,0.871,False,False
9,10,2026-05-28,2026-06-12,15.0,4.539,-2.568,7.107,6,3,9,True,1.000,False,False
10,11,2026-06-12,2026-06-27,15.0,0.223,-1.026,1.249,2,15,17,True,1.000,False,False
11,12,2026-06-27,2026-07-12,15.0,1.410,0.643,0.768,12,27,39,True,1.000,False,False

=== range_inventory_ladder_sun_V1 — passed=False  two_sided_rate 0.36 < 0.5 (active blocks); clean: two_sided_rate 0.36 < 0.5 (active blocks) ===

,block,start,end,days,pnl_pct,hold_pct,edge_pct,buy_fills,sell_fills,trades,two_sided,in_band_pct,in_fit,partial
0,1,2026-01-23,2026-02-07,15.0,-12.874,-19.067,6.193,5,11,16,True,1.000,False,False
1,2,2026-02-07,2026-02-22,15.0,5.080,3.852,1.228,6,8,14,True,1.000,False,False
2,3,2026-02-22,2026-03-09,15.0,-3.213,-3.714,0.500,13,0,13,False,0.938,False,False
3,4,2026-03-09,2026-03-24,15.0,12.167,13.581,-1.414,4,10,14,True,1.000,False,False
4,5,2026-03-24,2026-04-08,15.0,-2.949,-6.353,3.404,0,13,13,False,1.000,False,False
5,6,2026-04-08,2026-04-23,15.0,0.258,6.693,-6.435,0,3,3,False,1.000,False,False
6,7,2026-04-23,2026-05-08,15.0,0.154,5.614,-5.460,0,0,0,False,1.000,False,False
7,8,2026-05-08,2026-05-23,15.0,0.001,-0.034,0.035,0,1,1,False,1.000,False,False
8,9,2026-05-23,2026-06-07,15.0,-0.243,-10.439,10.196,0,0,0,False,1.000,False,False
9,10,2026-06-07,2026-06-22,15.0,0.369,-1.788,2.157,3,0,3,False,1.000,False,False
10,11,2026-06-22,2026-07-07,15.0,7.332,3.925,3.406,18,11,29,True,1.000,False,False
11,12,2026-07-07,2026-07-12,5.4,1.400,1.450,-0.049,0,23,23,False,1.000,False,True

=== range_inventory_ladder_xmr_V1 — passed=True   ===

,block,start,end,days,pnl_pct,hold_pct,edge_pct,buy_fills,sell_fills,trades,two_sided,in_band_pct,in_fit,partial
0,1,2026-01-13,2026-01-28,15.0,-24.221,-24.221,0.000,0,0,0,False,0.000,False,False
1,2,2026-01-28,2026-02-12,15.0,-14.184,-24.696,10.512,71,88,159,True,0.550,False,False
2,3,2026-02-12,2026-02-27,15.0,8.823,1.884,6.939,44,86,130,True,1.000,False,False
3,4,2026-02-27,2026-03-14,15.0,0.680,3.716,-3.036,3,25,28,True,1.000,False,False
4,5,2026-03-14,2026-03-29,15.0,1.534,-6.303,7.837,20,24,44,True,1.000,False,False
5,6,2026-03-29,2026-04-13,15.0,5.840,4.263,1.577,55,82,137,True,1.000,False,False
6,7,2026-04-13,2026-04-28,15.0,0.173,7.568,-7.395,0,5,5,False,0.834,False,False
7,8,2026-04-28,2026-05-13,15.0,0.110,5.262,-5.151,0,0,0,False,0.164,False,False
8,9,2026-05-13,2026-05-28,15.0,-0.200,-9.083,8.883,0,0,0,False,0.109,False,False
9,10,2026-05-28,2026-06-12,15.0,12.641,-0.469,13.110,40,45,85,True,0.835,False,False
10,11,2026-06-12,2026-06-27,15.0,-1.231,-8.740,7.508,44,37,81,True,0.991,False,False
11,12,2026-06-27,2026-07-12,15.0,6.887,2.747,4.140,31,43,74,True,0.991,False,False

=== range_inventory_ladder_zano_V1 — passed=False  abs_pos_rate 0.45 < 0.5 (active blocks); clean: abs_pos_rate 0.45 < 0.5 (active blocks) ===

,block,start,end,days,pnl_pct,hold_pct,edge_pct,buy_fills,sell_fills,trades,two_sided,in_band_pct,in_fit,partial
0,1,2026-01-13,2026-01-28,15.0,-3.338,-15.795,12.457,26,15,41,True,0.976,False,False
1,2,2026-01-28,2026-02-12,15.0,-10.796,-10.995,0.199,5,0,5,False,0.943,False,False
2,3,2026-02-12,2026-02-27,15.0,-5.256,-5.284,0.028,0,0,0,False,0.837,False,False
3,4,2026-02-27,2026-03-14,15.0,-24.305,-24.441,0.137,0,0,0,False,0.000,False,False
4,5,2026-03-14,2026-03-29,15.0,66.158,66.650,-0.492,0,0,0,False,0.679,False,False
5,6,2026-03-29,2026-04-13,15.0,-2.138,-6.241,4.103,18,4,22,True,1.000,False,False
6,7,2026-04-13,2026-04-28,15.0,6.256,3.452,2.803,13,4,17,True,1.000,False,False
7,8,2026-04-28,2026-05-13,15.0,13.511,18.270,-4.759,12,10,22,True,0.814,False,False
8,9,2026-05-13,2026-05-28,15.0,-0.627,-9.990,9.363,0,8,8,False,0.690,False,False
9,10,2026-05-28,2026-06-12,15.0,-1.326,-10.677,9.352,8,4,12,True,1.000,False,False
10,11,2026-06-12,2026-06-27,15.0,10.415,5.341,5.074,12,7,19,True,1.000,False,False
11,12,2026-06-27,2026-07-12,15.0,6.872,4.612,2.261,5,2,7,True,1.000,False,False

In [7]:
# ── Cell 7: full engine per market (WF + HOLDOUT fit + frozen block report) ──
evals = {}
t0 = time.time()
for i, pk in enumerate(review, 1):
    if pk not in hist_h:
        print(f'[{i}/{len(review)}] {pk}: no usable history'); continue
    try:
        ev = lr.evaluate_market(pk, hist_h, uni, CFG, hist_report=hist_report)
    except Exception as e:
        print(f'[{i}/{len(review)}] {pk}: ERROR {e}'); continue
    evals[pk] = ev
    s, wf, ho = ev['report']['summary'], ev['wf'], ev.get('holdout') or {}
    print(f"[{i}/{len(review)}] {pk:14s} rep={ev['granularity']}/fit={ev['search_granularity']} "
          f"edge={s['edge_pct']:+7.2f}% epr={s.get('edge_pos_rate')} "
          f"clean_epr={s.get('clean_edge_pos_rate')} "
          f"HOLDOUT={ho.get('edge_pct', float('nan')):+.2f}% "
          f"blocks_pass={ev['report']['passed']} wf_pass={wf.get('wf_pass')}")
print(f'engine done in {time.time()-t0:.0f}s')

[1/42] BCH2/USDT      rep=5m/fit=1h edge= +24.90% epr=0.8 clean_epr=None HOLDOUT=+8.85% blocks_pass=False wf_pass=False
[2/42] DIVI/USDT      rep=5m/fit=1h edge= +68.41% epr=0.667 clean_epr=0.571 HOLDOUT=-1.40% blocks_pass=False wf_pass=False
[3/42] SAL/USDT       rep=5m/fit=1h edge=  +3.81% epr=0.5 clean_epr=1.0 HOLDOUT=-13.77% blocks_pass=False wf_pass=False
[4/42] BELLS/BTC      rep=5m/fit=1h edge= +47.68% epr=0.8 clean_epr=0.714 HOLDOUT=-1.72% blocks_pass=True wf_pass=True
[5/42] ARRR/USDT      rep=5m/fit=1h edge= +30.70% epr=0.7 clean_epr=0.6 HOLDOUT=-0.93% blocks_pass=False wf_pass=False
[6/42] BELLS/USDT     rep=5m/fit=1h edge= +43.58% epr=0.7 clean_epr=0.8 HOLDOUT=+17.43% blocks_pass=True wf_pass=True
[7/42] PEP/USDC       rep=5m/fit=1h edge=  +5.11% epr=1.0 clean_epr=1.0 HOLDOUT=-4.00% blocks_pass=False wf_pass=False
[8/42] PYTH/USDT      rep=5m/fit=1h edge= +60.22% epr=0.75 clean_epr=0.857 HOLDOUT=-13.05% blocks_pass=False wf_pass=False
[9/42] XMR/USDC       rep=5m/fit=1h edge= +40.71% epr=0.636 clean_epr=0.667 HOLDOUT=+2.76% blocks_pass=False wf_pass=True
[10/42] XMR/USDT       rep=5m/fit=1h edge= +42.68% epr=0.636 clean_epr=0.667 HOLDOUT=+3.50% blocks_pass=False wf_pass=True
[11/42] ARRR/BTC       rep=5m/fit=1h edge= +14.72% epr=0.556 clean_epr=0.4 HOLDOUT=-7.52% blocks_pass=False wf_pass=False
[12/42] ONDO/USDT      rep=5m/fit=1h edge= +36.64% epr=0.818 clean_epr=0.667 HOLDOUT=+0.85% blocks_pass=False wf_pass=False
[13/42] ARRR/XMR       rep=5m/fit=1h edge= +35.42% epr=0.583 clean_epr=0.714 HOLDOUT=-5.61% blocks_pass=False wf_pass=False
[14/42] DASH/USDT      rep=5m/fit=1h edge= +56.37% epr=0.8 clean_epr=0.8 HOLDOUT=+1.43% blocks_pass=True wf_pass=True
[15/42] ZEPH/USDT      rep=5m/fit=1h edge= +16.07% epr=0.444 clean_epr=0.75 HOLDOUT=+7.30% blocks_pass=False wf_pass=False
[16/42] ZEC/USDT       rep=5m/fit=1h edge= +79.40% epr=0.5 clean_epr=0.429 HOLDOUT=-6.25% blocks_pass=False wf_pass=False
[17/42] INJ/USDT       rep=5m/fit=1h edge= +41.81% epr=0.75 clean_epr=0.571 HOLDOUT=-0.69% blocks_pass=False wf_pass=False
[18/42] EPIC/USDT      rep=5m/fit=1h edge= +20.58% epr=1.0 clean_epr=1.0 HOLDOUT=-2.91% blocks_pass=False wf_pass=False
[19/42] BC2/BTC        rep=5m/fit=1h edge= +17.84% epr=0.5 clean_epr=1.0 HOLDOUT=+6.28% blocks_pass=False wf_pass=False
[20/42] LKY/USDT       rep=5m/fit=1h edge=  +2.85% epr=1.0 clean_epr=1.0 HOLDOUT=-15.90% blocks_pass=False wf_pass=False
[21/42] FET/USDT       rep=5m/fit=1h edge= +35.72% epr=0.7 clean_epr=0.8 HOLDOUT=+2.67% blocks_pass=True wf_pass=False
[22/42] EPIC/XMR       rep=5m/fit=1h edge= +35.18% epr=0.727 clean_epr=0.667 HOLDOUT=+0.06% blocks_pass=False wf_pass=False
[23/42] EIGEN/USDT     rep=5m/fit=1h edge= +45.19% epr=0.636 clean_epr=0.5 HOLDOUT=+5.57% blocks_pass=False wf_pass=False
[24/42] PEP/USDT       rep=5m/fit=1h edge=  +4.43% epr=1.0 clean_epr=1.0 HOLDOUT=-5.86% blocks_pass=False wf_pass=False
[25/42] XLM/USDT       rep=5m/fit=1h edge= +45.79% epr=0.75 clean_epr=0.714 HOLDOUT=+2.28% blocks_pass=False wf_pass=False
[26/42] BDX/BTC        rep=5m/fit=1h edge= +18.67% epr=0.636 clean_epr=0.667 HOLDOUT=+3.68% blocks_pass=False wf_pass=False
[27/42] DYDX/USDT      rep=5m/fit=1h edge= +46.21% epr=0.7 clean_epr=0.6 HOLDOUT=+12.30% blocks_pass=False wf_pass=False
[28/42] W/USDT         rep=5m/fit=1h edge= +29.88% epr=0.667 clean_epr=0.0 HOLDOUT=+2.42% blocks_pass=False wf_pass=True
[29/42] BC2/USDT       rep=5m/fit=1h edge= +24.49% epr=1.0 clean_epr=1.0 HOLDOUT=+20.32% blocks_pass=False wf_pass=False
[30/42] BDX/USDT       rep=5m/fit=1h edge= +11.57% epr=0.5 clean_epr=0.4 HOLDOUT=+0.33% blocks_pass=False wf_pass=True
[31/42] AAVE/USDC      rep=5m/fit=1h edge= +21.18% epr=0.727 clean_epr=0.833 HOLDOUT=-2.74% blocks_pass=False wf_pass=False
[32/42] DOGE/USDT      rep=5m/fit=1h edge=  +8.72% epr=0.5 clean_epr=0.4 HOLDOUT=+2.15% blocks_pass=False wf_pass=False
[33/42] UNI/USDT       rep=5m/fit=1h edge= +53.76% epr=0.636 clean_epr=0.667 HOLDOUT=-4.93% blocks_pass=False wf_pass=False
[34/42] NKYC/USDT      rep=5m/fit=1h edge= +61.14% epr=0.8 clean_epr=0.75 HOLDOUT=+1.33% blocks_pass=False wf_pass=True
[35/42] LINK/USDT      rep=5m/fit=1h edge= +19.90% epr=0.545 clean_epr=0.667 HOLDOUT=+0.69% blocks_pass=False wf_pass=True
[36/42] AVAX/USDT      rep=5m/fit=1h edge=  +2.52% epr=0.444 clean_epr=0.25 HOLDOUT=+2.89% blocks_pass=False wf_pass=False
[37/42] XVG/USDT       rep=5m/fit=1h edge=  +1.49% epr=1.0 clean_epr=1.0 HOLDOUT=-1.57% blocks_pass=False wf_pass=False
[38/42] MANA/USDT      rep=5m/fit=1h edge= +13.05% epr=0.625 clean_epr=0.333 HOLDOUT=+8.03% blocks_pass=False wf_pass=False
[39/42] RENDER/USDT    rep=5m/fit=1h edge= +30.12% epr=0.7 clean_epr=0.8 HOLDOUT=+0.33% blocks_pass=False wf_pass=True
[40/42] SHIB/USDT      rep=5m/fit=1h edge=  +7.68% epr=0.625 clean_epr=0.5 HOLDOUT=+1.02% blocks_pass=False wf_pass=False
[41/42] ZANO/USDT      rep=5m/fit=1h edge= +61.38% epr=0.667 clean_epr=0.429 HOLDOUT=+5.95% blocks_pass=False wf_pass=False
[42/42] SUN/USDT       rep=5m/fit=1h edge=  +9.75% epr=0.545 clean_epr=0.5 HOLDOUT=+2.53% blocks_pass=False wf_pass=False
engine done in 280s

In [8]:
# ── Cell 8: rolling walk-forward summary (secondary, leakage-safe) ────
wf_rows = pd.DataFrame([dict(market=pk, **{k: v for k, v in ev['wf'].items() if k != 'folds'})
                        for pk, ev in evals.items() if ev])
if not wf_rows.empty:
    wf_rows = wf_rows.sort_values(['wf_pass', 'edge_pos_rate', 'median_edge_pct'],
                                  ascending=[False, False, False]).reset_index(drop=True)
display(wf_rows)

,market,n_folds,edge_pos_rate,two_sided_rate,median_edge_pct,median_test_pct,median_stress_edge,worst_edge_pct,median_trades,total_trades,wf_pass
0,BELLS/BTC,8,0.875,0.875,1.779,1.747,0.930,-0.039,30.0,213,True
1,NKYC/USDT,8,0.875,0.625,1.381,0.756,0.691,0.000,24.0,252,True
2,W/USDT,6,0.833,0.667,1.793,-1.075,1.728,-5.468,31.0,207,True
3,BELLS/USDT,8,0.750,0.875,5.105,3.966,3.651,-4.143,31.0,294,True
4,RENDER/USDT,8,0.625,0.500,2.361,2.983,1.728,-7.696,20.0,184,True
5,LINK/USDT,8,0.625,0.625,1.486,1.648,-0.669,-3.840,20.0,174,True
6,XMR/USDC,8,0.625,0.625,1.350,1.154,0.535,-4.258,23.0,190,True
7,DASH/USDT,8,0.625,0.750,1.181,4.222,-1.543,-5.603,21.0,212,True
8,XMR/USDT,8,0.625,0.500,0.690,0.938,0.625,-4.759,25.5,206,True
9,BDX/USDT,8,0.625,0.500,0.407,0.496,0.172,-2.222,36.5,303,True
10,FET/USDT,8,0.875,0.750,3.455,2.253,3.719,-11.618,26.5,208,False
11,MANA/USDT,6,0.833,1.000,3.140,5.629,2.417,-11.649,31.5,203,False
12,ARRR/USDT,8,0.750,1.000,8.341,10.223,4.529,-17.480,38.5,355,False
13,ONDO/USDT,8,0.750,0.500,2.095,3.171,0.440,-19.478,20.5,204,False
14,ZEPH/USDT,8,0.750,0.875,1.699,1.308,-0.289,-9.910,29.5,236,False
15,BCH2/USDT,3,0.667,1.000,11.522,10.224,6.506,-2.828,32.0,118,False
16,DIVI/USDT,8,0.625,0.750,7.474,2.300,4.600,-28.634,23.0,201,False
17,ZEC/USDT,8,0.625,0.875,3.417,7.093,2.014,-25.440,24.0,235,False
18,ARRR/BTC,8,0.625,0.875,3.411,5.344,-0.952,-28.679,26.5,253,False
19,ZANO/USDT,8,0.625,0.875,2.091,5.895,0.554,-15.574,30.5,329,False
20,AVAX/USDT,8,0.625,0.500,0.863,0.927,0.829,-12.212,27.0,212,False
21,DYDX/USDT,5,0.600,0.800,1.626,9.017,1.112,-24.712,37.0,141,False
22,EIGEN/USDT,7,0.571,0.714,2.987,9.719,1.963,-8.666,18.0,147,False
23,LKY/USDT,8,0.500,0.750,1.391,-4.745,0.366,-6.260,20.0,166,False
24,EPIC/XMR,8,0.500,0.625,1.144,-1.556,-1.181,-4.835,22.0,163,False
25,BDX/BTC,8,0.500,0.500,0.625,2.644,-0.201,-2.681,25.5,185,False
26,ARRR/XMR,8,0.500,0.750,0.553,1.809,-1.194,-29.475,33.0,345,False
27,PEP/USDT,8,0.500,0.625,0.502,-6.663,-3.193,-11.658,38.5,361,False
28,SHIB/USDT,8,0.500,0.375,0.346,-0.179,-0.104,-1.536,18.0,135,False
29,INJ/USDT,8,0.500,0.750,0.265,3.220,-0.773,-18.013,18.0,195,False
30,PYTH/USDT,8,0.500,0.625,0.188,3.199,0.103,-12.167,19.5,158,False
31,PEP/USDC,8,0.500,0.625,-1.187,-8.524,-0.128,-12.225,35.0,262,False
32,XVG/USDT,8,0.500,0.500,-1.752,-6.095,-1.475,-10.261,21.5,180,False
33,XLM/USDT,8,0.375,0.375,-0.130,2.526,-0.112,-1.851,28.0,199,False
34,DOGE/USDT,8,0.375,0.375,-0.563,-0.145,-0.630,-5.551,22.5,196,False
35,EPIC/USDT,8,0.375,0.500,-2.220,-7.346,-2.192,-9.799,22.0,184,False
36,AAVE/USDC,8,0.375,0.375,-2.240,-0.611,-2.802,-19.051,26.5,225,False
37,BC2/BTC,8,0.375,0.750,-6.014,-6.159,-9.428,-14.357,33.5,357,False
38,BC2/USDT,8,0.375,0.625,-7.421,-19.538,-6.813,-15.544,34.5,373,False
39,SAL/USDT,8,0.375,0.750,-10.437,-9.969,-7.611,-52.566,25.5,307,False
40,SUN/USDT,7,0.286,0.143,-0.401,-0.003,-0.440,-3.690,23.0,177,False
41,UNI/USDT,8,0.000,0.375,-4.614,-2.666,-3.679,-7.372,18.5,135,False

In [9]:
# ── Cell 9: finalize (v10 gates + holdout/clean gates + sizing), write artifacts ─
final_df, configs = lr.finalize_v11(evals, uni, CFG, yaml_reports)
display(final_df)

print('\n— HOLDOUT (the deciding out-of-sample evidence) —')
ho_view = final_df[['base', 'validation', 'holdout_edge_pct', 'holdout_trades',
                    'holdout_two_sided', 'holdout_active', 'edge_pct',
                    'clean_edge_pos_rate', 'harvest_best_pct_mo',
                    'max_fund', 'max_fund_quote', 'depth_2pct', 'gates']]
display(ho_view)

block_tables = {pk: ev['report']['blocks'] for pk, ev in evals.items() if ev}
written = lr.save_v11_outputs(PREFIX, final_df, configs, wf_rows, yaml_df, block_tables,
                              metadata=dict(exchange=EXCHANGE, run=RUN_TS,
                                            cfg={k: str(v) for k, v in CFG.items() if str(k).startswith('rc_')},
                                            yaml_paths=[p['path'] for p in yamls]))
# ---- v11.3: FULLY DEPLOYABLE YAMLs ----------------------------------------
# One ready-to-run controller config per market that is CONFIRMED, a strong
# CANDIDATE (GATED on the WF process check only, with a two-sided holdout and
# clean blocks), or ALREADY LIVE (a REFRESH re-fit at today's anchor -- never
# drop one over a running config without comparing rungs; bump the id and
# start a clean state file if you adopt it).
deployed_pairs = [lr._pair_key(p['trading_pair']) for p in yamls
                  if not DEPLOYED_CONTROLLERS
                  or p.get('controller_id', p.get('id')) in DEPLOYED_CONTROLLERS]
yaml_paths = lr.save_deploy_yamls(ART / 'deploy_yamls', configs, final_df, CFG,
                                  deployed_pairs=deployed_pairs, run_id=RUN_TS[:8])
print(f'\n{len(yaml_paths)-1} deployable YAMLs -> {ART}/deploy_yamls (see INDEX.md)')
print('Read:', f'{PREFIX}_copy_paste_ladders.md')

,base,trading_pair,src,granularity,validation,rungs,family,spacing,weights,pnl_pct,...,quote_usd_rate,max_fund_quote,max_fund,spread_pct,depth_2pct,depth_used,depth_basis,depth_ladder_band,book_total_usd,gates
0,DASH/USDT,DASH-USDT,NonKYC,5m,CONFIRMED,7+9,quantile,back_loaded,slight_deep,37.414,...,1.0000,1000.000000,1000,0.8417,2.0,30066.0,ladder_band,30066.0,33535.0,
1,BELLS/USDT,BELLS-USDT,NonKYC,5m,CONFIRMED,4+9,quantile,geometric,slight_deep,27.777,...,1.0000,700.000000,700,1.0127,311.0,1394.0,ladder_band,1394.0,12723.0,
2,BELLS/BTC,BELLS-BTC,NonKYC,5m,GATED,4+10,quantile,front_loaded,mild_near,52.649,...,63449.9900,0.003152,200,1.0695,3.0,55.0,min_band_5pct,12.0,7076.0,thin book ($55 in the min_band_5pct)
3,FET/USDT,FET-USDT,NonKYC,5m,GATED,7+4,volatility,geometric,near,13.485,...,1.0000,300.000000,300,0.0632,25090.0,47826.0,ladder_band,47826.0,47852.0,rolling WF (process check) failed
4,BC2/USDT,BC2-USDT,NonKYC,5m,SUSPECT,10+5,pct,back_loaded,near,-13.616,...,1.0000,1000.000000,1000,1.1885,676.0,1914.0,ladder_band,1914.0,8654.0,only 2 ACTIVE blocks (< 4) -- band rarely visi...
5,EPIC/USDT,EPIC-USDT,NonKYC,5m,SUSPECT,5+7,volatility,geometric,mild_near,6.904,...,1.0000,600.000000,600,0.8728,23.0,5807.0,ladder_band,5807.0,63420.0,clean: only 1 ACTIVE blocks (< 4) -- band rare...
6,PEP/USDC,PEP-USDC,NonKYC,5m,SUSPECT,7+9,volatility,back_loaded,slight_deep,-31.340,...,1.0029,199.422000,200,1.0160,7.0,161.0,ladder_band,161.0,141130.0,only 2 ACTIVE blocks (< 4) -- band rarely visi...
7,PEP/USDT,PEP-USDT,NonKYC,5m,SUSPECT,10+8,volatility,back_loaded,slight_deep,-32.350,...,1.0000,800.000000,800,0.1572,138.0,3378.0,ladder_band,3378.0,18923.0,only 2 ACTIVE blocks (< 4) -- band rarely visi...
8,LKY/USDT,LKY-USDT,NonKYC,5m,SUSPECT,10+8,quantile,linear,near,-34.272,...,1.0000,200.000000,200,1.1869,15.0,204.0,ladder_band,204.0,26126.0,only 1 ACTIVE blocks (< 4) -- band rarely visi...
9,XVG/USDT,XVG-USDT,NonKYC,5m,SUSPECT,9+4,pct,back_loaded,near,-33.517,...,1.0000,200.000000,200,1.1096,1.0,25.0,ladder_band,25.0,9115.0,only 3 ACTIVE blocks (< 4) -- band rarely visi...
10,ONDO/USDT,ONDO-USDT,NonKYC,5m,SUSPECT,5+9,quantile,back_loaded,slight_deep,26.780,...,1.0000,200.000000,200,0.2721,17440.0,17457.0,ladder_band,17457.0,18085.0,two_sided_rate 0.12 < 0.5 (active blocks); cle...
11,NKYC/USDT,NKYC-USDT,NonKYC,5m,SUSPECT,7+4,volatility,back_loaded,slight_deep,39.651,...,1.0000,1250.000000,1250,0.1355,2336.0,2552.0,ladder_band,2552.0,5016.0,median 5 trades/ACTIVE block < 8; two_sided_ra...
12,BCH2/USDT,BCH2-USDT,NonKYC,5m,SUSPECT,9+6,quantile,linear,slight_deep,-16.447,...,1.0000,200.000000,200,0.8500,5.0,179.0,ladder_band,179.0,2520.0,clean: only 3 out-of-fit blocks (< 4); rolling...
13,PYTH/USDT,PYTH-USDT,NonKYC,5m,SUSPECT,7+9,quantile,back_loaded,slight_deep,44.921,...,1.0000,300.000000,300,0.6231,24256.0,41262.0,ladder_band,41262.0,50711.0,two_sided_rate 0.36 < 0.5 (active blocks); cle...
14,XLM/USDT,XLM-USDT,NonKYC,5m,SUSPECT,5+7,volatility,back_loaded,slight_deep,36.819,...,1.0000,500.000000,500,0.8102,37459.0,51256.0,ladder_band,51256.0,55565.0,median 6 trades/ACTIVE block < 8; two_sided_ra...
15,INJ/USDT,INJ-USDT,NonKYC,5m,SUSPECT,4+8,quantile,back_loaded,slight_deep,36.242,...,1.0000,1000.000000,1000,0.2090,88463.0,179123.0,ladder_band,179123.0,979208.0,worst block edge -16.48% < -12.5%; clean: only...
16,EPIC/XMR,EPIC-XMR,NonKYC,5m,SUSPECT,8+4,volatility,geometric,slight_deep,58.186,...,325.5000,0.614439,200,1.1299,22.0,320.0,ladder_band,320.0,879.0,worst block edge -14.22% < -12.5%; two_sided_r...
17,AAVE/USDC,AAVE-USDC,NonKYC,5m,SUSPECT,9+8,volatility,back_loaded,slight_deep,-0.478,...,1.0029,299.133000,300,0.2037,1975.0,2082.0,ladder_band,2082.0,2000.0,two_sided_rate 0.09 < 0.5 (active blocks); cle...
18,DYDX/USDT,DYDX-USDT,NonKYC,5m,SUSPECT,7+10,quantile,back_loaded,slight_deep,60.464,...,1.0000,500.000000,500,0.3899,12401.0,17091.0,ladder_band,17091.0,4852928.0,clean: only 5 full blocks (< 6); clean: only 3...
19,ARRR/USDT,ARRR-USDT,NonKYC,5m,SUSPECT,5+5,pct,back_loaded,near,-0.027,...,1.0000,3500.000000,3500,0.8366,8.0,6800.0,ladder_band,6800.0,35730.0,clean: edge_pos_rate 0.60 < 0.65 (over 5 engag...
20,RENDER/USDT,RENDER-USDT,NonKYC,5m,SUSPECT,7+5,quantile,front_loaded,near,12.528,...,1.0000,300.000000,300,0.3963,40801.0,51053.0,ladder_band,51053.0,162051.0,two_sided_rate 0.25 < 0.5 (active blocks); cle...
21,DIVI/USDT,DIVI-USDT,NonKYC,5m,SUSPECT,6+10,quantile,back_loaded,slight_deep,63.553,...,1.0000,300.000000,300,0.5913,9.0,655.0,ladder_band,655.0,116117.0,clean: edge_pos_rate 0.57 < 0.65 (over 7 engag...
22,ZANO/USDT,ZANO-USDT,NonKYC,5m,SUSPECT,8+4,quantile,back_loaded,slight_deep,56.737,...,1.0000,200.000000,200,0.3605,893.0,9477.0,ladder_band,9477.0,12388.0,worst block edge -14.24% < -12.5%; clean: edge...
23,W/USDT,W-USDT,NonKYC,5m,SUSPECT,8+9,quantile,back_loaded,slight_deep,3.990,...,1.0000,2750.000000,2750,0.5266,57866.0,93917.0,ladder_band,93917.0,117668.0,clean: only 5 full blocks (< 6); clean: only 1...
24,UNI/USDT,UNI-USDT,NonKYC,5m,SUSPECT,9+4,quantile,back_loaded,slight_deep,36.474,...,1.0000,300.000000,300,0.7006,186658.0,187182.0,ladder_band,187182.0,187581.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
25,EIGEN/USDT,EIGEN-USDT,NonKYC,5m,SUSPECT,10+6,quantile,back_loaded,slight_deep,31.466,...,1.0000,900.000000,900,0.2621,45652.0,77170.0,ladder_band,77170.0,1048167.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
26,XMR/USDT,XMR-USDT,NonKYC,5m,SUSPECT,8+8,quantile,back_loaded,slight_deep,17.315,...,1.0000,10000.000000,10000,0.0338,60145.0,84368.0,ladder_band,84368.0,88625.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
27,XMR/USDC,XMR-USDC,MEXC,5m,SUSPECT,9+7,quantile,back_loaded,slight_deep,15.440,...,1.0029,398.843000,400,1.3420,11675.0,11710.0,ladder_band,11710.0,11760.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
28,BDX/BTC,BDX-BTC,NonKYC,5m,SUSPECT,5+10,volatility,back_loaded,equal,38.518,...,63449.9900,0.004728,300,0.1731,389.0,547.0,ladder_band,547.0,110801.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
29,MANA/USDT,MANA-USDT,NonKYC,5m,SUSPECT,5+8,quantile,back_loaded,slight_deep,-1.222,...,1.0000,500.000000,500,0.2587,18501.0,18503.0,min_band_5pct,7510.0,2938093.0,edge_pos_rate 0.62 < 0.65 (over 8 engaged bloc...
30,SHIB/USDT,SHIB-USDT,NonKYC,5m,SUSPECT,4+10,volatility,back_loaded,slight_deep,-17.947,...,1.0000,1000.000000,1000,0.2131,98224.0,98237.0,ladder_band,98237.0,1897041.0,edge_pos_rate 0.62 < 0.65 (over 8 engaged bloc...
31,ARRR/XMR,ARRR-XMR,NonKYC,5m,SUSPECT,10+7,volatility,front_loaded,slight_deep,24.225,...,325.5000,0.921659,300,1.0631,2.0,1682.0,ladder_band,1682.0,45356.0,edge_pos_rate 0.58 < 0.65 (over 12 engaged blo...
32,ARRR/BTC,ARRR-BTC,NonKYC,5m,SUSPECT,4+7,pct,back_loaded,slight_deep,-7.334,...,63449.9900,0.011032,700,1.1633,68.0,2247.0,ladder_band,2247.0,491270.0,edge_pos_rate 0.56 < 0.65 (over 9 engaged bloc...
33,LINK/USDT,LINK-USDT,NonKYC,5m,SUSPECT,5+7,quantile,back_loaded,slight_deep,-0.714,...,1.0000,600.000000,600,0.4994,217895.0,340612.0,ladder_band,340612.0,399718.0,edge_pos_rate 0.55 < 0.65 (over 11 engaged blo...
34,SUN/USDT,SUN-USDT,NonKYC,5m,SUSPECT,6+5,quantile,back_loaded,slight_deep,3.892,...,1.0000,400.000000,400,0.7080,6103.0,6112.0,ladder_band,6112.0,6347.0,edge_pos_rate 0.55 < 0.65 (over 11 engaged blo...
35,ZEC/USDT,ZEC-USDT,NonKYC,5m,SUSPECT,9+9,volatility,back_loaded,slight_deep,98.905,...,1.0000,700.000000,700,0.6528,5503.0,24230.0,ladder_band,24230.0,37600.0,edge_pos_rate 0.50 < 0.65 (over 12 engaged blo...
36,BC2/BTC,BC2-BTC,NonKYC,5m,SUSPECT,7+10,volatility,back_loaded,slight_deep,-14.805,...,63449.9900,0.003152,200,1.1919,0.0,73.0,ladder_band,73.0,13967988.0,edge_pos_rate 0.50 < 0.65 (over 4 engaged bloc...
37,BDX/USDT,BDX-USDT,NonKYC,5m,SUSPECT,5+9,pct,back_loaded,slight_deep,9.555,...,1.0000,200.000000,200,0.1756,333.0,497.0,ladder_band,497.0,1057359.0,edge_pos_rate 0.50 < 0.65 (over 8 engaged bloc...
38,DOGE/USDT,DOGE-USDT,NonKYC,5m,SUSPECT,6+10,volatility,back_loaded,slight_deep,-15.199,...,1.0000,500.000000,500,0.2323,107816.0,210535.0,ladder_band,210535.0,211253.0,edge_pos_rate 0.50 < 0.65 (over 10 engaged blo...
39,SAL/USDT,SAL-USDT,NonKYC,5m,SUSPECT,7+5,quantile,back_loaded,near,-32.337,...,1.0000,1000.000000,1000,1.1680,1005.0,3028.0,ladder_band,3028.0,4916.0,only 3 ACTIVE blocks (< 4) -- band rarely visi...
40,ZEPH/USDT,ZEPH-USDT,NonKYC,5m,SUSPECT,9+8,pct,geometric,mild_near,-8.403,...,1.0000,200.000000,200,0.0355,7.0,352.0,ladder_band,352.0,4869.0,edge_pos_rate 0.44 < 0.65 (over 9 engaged bloc...
41,AVAX/USDT,AVAX-USDT,NonKYC,5m,SUSPECT,6+9,quantile,geometric,near,-25.370,...,1.0000,700.000000,700,0.6211,266848.0,299449.0,ladder_band,299449.0,413693.0,edge_pos_rate 0.44 < 0.65 (over 9 engaged bloc...

— HOLDOUT (the deciding out-of-sample evidence) —

,base,validation,holdout_edge_pct,holdout_trades,holdout_two_sided,holdout_active,edge_pct,clean_edge_pos_rate,harvest_best_pct_mo,max_fund,max_fund_quote,depth_2pct,gates
0,DASH/USDT,CONFIRMED,1.429,19,True,True,56.370,0.800,38.411,1000,1000.000000,2.0,
1,BELLS/USDT,CONFIRMED,17.425,102,True,True,43.578,0.800,32.373,700,700.000000,311.0,
2,BELLS/BTC,GATED,-1.721,54,True,True,47.682,0.714,24.713,200,0.003152,3.0,thin book ($55 in the min_band_5pct)
3,FET/USDT,GATED,2.669,46,True,True,35.719,0.800,29.488,300,300.000000,25090.0,rolling WF (process check) failed
4,BC2/USDT,SUSPECT,20.320,130,True,True,24.491,1.000,84.346,1000,1000.000000,676.0,only 2 ACTIVE blocks (< 4) -- band rarely visi...
5,EPIC/USDT,SUSPECT,-2.912,33,False,True,20.577,1.000,32.684,600,600.000000,23.0,clean: only 1 ACTIVE blocks (< 4) -- band rare...
6,PEP/USDC,SUSPECT,-3.998,37,False,True,5.110,1.000,32.398,200,199.422000,7.0,only 2 ACTIVE blocks (< 4) -- band rarely visi...
7,PEP/USDT,SUSPECT,-5.857,49,False,True,4.430,1.000,44.085,800,800.000000,138.0,only 2 ACTIVE blocks (< 4) -- band rarely visi...
8,LKY/USDT,SUSPECT,-15.896,29,True,True,2.853,1.000,29.094,200,200.000000,15.0,only 1 ACTIVE blocks (< 4) -- band rarely visi...
9,XVG/USDT,SUSPECT,-1.568,48,False,True,1.487,1.000,26.770,200,200.000000,1.0,only 3 ACTIVE blocks (< 4) -- band rarely visi...
10,ONDO/USDT,SUSPECT,0.846,33,False,True,36.636,0.667,35.669,200,200.000000,17440.0,two_sided_rate 0.12 < 0.5 (active blocks); cle...
11,NKYC/USDT,SUSPECT,1.335,12,False,True,61.142,0.750,20.933,1250,1250.000000,2336.0,median 5 trades/ACTIVE block < 8; two_sided_ra...
12,BCH2/USDT,SUSPECT,8.852,73,True,True,24.903,NaN,164.179,200,200.000000,5.0,clean: only 3 out-of-fit blocks (< 4); rolling...
13,PYTH/USDT,SUSPECT,-13.052,33,False,True,60.222,0.857,32.832,300,300.000000,24256.0,two_sided_rate 0.36 < 0.5 (active blocks); cle...
14,XLM/USDT,SUSPECT,2.279,43,False,True,45.786,0.714,27.157,500,500.000000,37459.0,median 6 trades/ACTIVE block < 8; two_sided_ra...
15,INJ/USDT,SUSPECT,-0.695,19,False,True,41.808,0.571,33.947,1000,1000.000000,88463.0,worst block edge -16.48% < -12.5%; clean: only...
16,EPIC/XMR,SUSPECT,0.061,27,False,True,35.177,0.667,28.475,200,0.614439,22.0,worst block edge -14.22% < -12.5%; two_sided_r...
17,AAVE/USDC,SUSPECT,-2.743,39,False,True,21.178,0.833,31.616,300,299.133000,1975.0,two_sided_rate 0.09 < 0.5 (active blocks); cle...
18,DYDX/USDT,SUSPECT,12.301,37,True,True,46.206,0.600,43.531,500,500.000000,12401.0,clean: only 5 full blocks (< 6); clean: only 3...
19,ARRR/USDT,SUSPECT,-0.928,50,True,True,30.701,0.600,51.862,3500,3500.000000,8.0,clean: edge_pos_rate 0.60 < 0.65 (over 5 engag...
20,RENDER/USDT,SUSPECT,0.326,3,False,True,30.123,0.800,40.939,300,300.000000,40801.0,two_sided_rate 0.25 < 0.5 (active blocks); cle...
21,DIVI/USDT,SUSPECT,-1.404,33,False,True,68.414,0.571,36.197,300,300.000000,9.0,clean: edge_pos_rate 0.57 < 0.65 (over 7 engag...
22,ZANO/USDT,SUSPECT,5.946,28,True,True,61.383,0.429,24.663,200,200.000000,893.0,worst block edge -14.24% < -12.5%; clean: edge...
23,W/USDT,SUSPECT,2.416,9,True,True,29.878,0.000,35.987,2750,2750.000000,57866.0,clean: only 5 full blocks (< 6); clean: only 1...
24,UNI/USDT,SUSPECT,-4.928,21,True,True,53.757,0.667,9.941,300,300.000000,186658.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
25,EIGEN/USDT,SUSPECT,5.572,39,True,True,45.186,0.500,44.775,900,900.000000,45652.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
26,XMR/USDT,SUSPECT,3.502,27,True,True,42.683,0.667,32.672,10000,10000.000000,60145.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
27,XMR/USDC,SUSPECT,2.762,25,True,True,40.713,0.667,33.713,400,398.843000,11675.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
28,BDX/BTC,SUSPECT,3.677,37,False,True,18.666,0.667,21.095,300,0.004728,389.0,edge_pos_rate 0.64 < 0.65 (over 11 engaged blo...
29,MANA/USDT,SUSPECT,8.029,62,True,True,13.052,0.333,23.015,500,500.000000,18501.0,edge_pos_rate 0.62 < 0.65 (over 8 engaged bloc...
30,SHIB/USDT,SUSPECT,1.017,33,True,True,7.679,0.500,22.395,1000,1000.000000,98224.0,edge_pos_rate 0.62 < 0.65 (over 8 engaged bloc...
31,ARRR/XMR,SUSPECT,-5.612,78,False,True,35.423,0.714,54.239,300,0.921659,2.0,edge_pos_rate 0.58 < 0.65 (over 12 engaged blo...
32,ARRR/BTC,SUSPECT,-7.517,27,False,True,14.721,0.400,51.096,700,0.011032,68.0,edge_pos_rate 0.56 < 0.65 (over 9 engaged bloc...
33,LINK/USDT,SUSPECT,0.685,13,True,True,19.896,0.667,19.456,600,600.000000,217895.0,edge_pos_rate 0.55 < 0.65 (over 11 engaged blo...
34,SUN/USDT,SUSPECT,2.533,90,True,True,9.747,0.500,9.421,400,400.000000,6103.0,edge_pos_rate 0.55 < 0.65 (over 11 engaged blo...
35,ZEC/USDT,SUSPECT,-6.252,106,True,True,79.404,0.429,38.709,700,700.000000,5503.0,edge_pos_rate 0.50 < 0.65 (over 12 engaged blo...
36,BC2/BTC,SUSPECT,6.284,46,True,True,17.835,1.000,65.524,200,0.003152,0.0,edge_pos_rate 0.50 < 0.65 (over 4 engaged bloc...
37,BDX/USDT,SUSPECT,0.325,45,False,True,11.574,0.400,11.825,200,200.000000,333.0,edge_pos_rate 0.50 < 0.65 (over 8 engaged bloc...
38,DOGE/USDT,SUSPECT,2.145,34,True,True,8.722,0.400,23.611,500,500.000000,107816.0,edge_pos_rate 0.50 < 0.65 (over 10 engaged blo...
39,SAL/USDT,SUSPECT,-13.766,44,True,True,3.815,1.000,99.627,1000,1000.000000,1005.0,only 3 ACTIVE blocks (< 4) -- band rarely visi...
40,ZEPH/USDT,SUSPECT,7.297,88,True,True,16.065,0.750,30.673,200,200.000000,7.0,edge_pos_rate 0.44 < 0.65 (over 9 engaged bloc...
41,AVAX/USDT,SUSPECT,2.894,28,False,True,2.522,0.250,24.421,700,700.000000,266848.0,edge_pos_rate 0.44 < 0.65 (over 9 engaged bloc...

  wrote artifacts/nonkyc/20260713-040416/files/NONKYC_recycle_v11_final_summary.csv
  wrote artifacts/nonkyc/20260713-040416/files/NONKYC_recycle_v11_walkforward_summary.csv
  wrote artifacts/nonkyc/20260713-040416/files/NONKYC_recycle_v11_live_yaml_summary.csv
  wrote artifacts/nonkyc/20260713-040416/files/NONKYC_recycle_v11_block_details.csv
  wrote artifacts/nonkyc/20260713-040416/files/NONKYC_recycle_v11_holdout_summary.csv
  wrote artifacts/nonkyc/20260713-040416/files/NONKYC_recycle_v11_deploy_config.json
  wrote artifacts/nonkyc/20260713-040416/files/NONKYC_recycle_v11_copy_paste_ladders.md
  wrote deployable YAML artifacts/nonkyc/20260713-040416/files/deploy_yamls/range_inventory_ladder_bells_usdt_auto_20260713.yml
  wrote deployable YAML artifacts/nonkyc/20260713-040416/files/deploy_yamls/range_inventory_ladder_dash_usdt_auto_20260713.yml
  wrote deployable YAML artifacts/nonkyc/20260713-040416/files/deploy_yamls/range_inventory_ladder_fet_usdt_auto_20260713.yml
  wrote deployable YAML artifacts/nonkyc/20260713-040416/files/deploy_yamls/range_inventory_ladder_sun_usdt_auto_20260713.yml
  wrote deployable YAML artifacts/nonkyc/20260713-040416/files/deploy_yamls/range_inventory_ladder_xmr_usdt_auto_20260713.yml
  wrote deployable YAML artifacts/nonkyc/20260713-040416/files/deploy_yamls/range_inventory_ladder_zano_usdt_auto_20260713.yml

6 deployable YAMLs -> artifacts/nonkyc/20260713-040416/files/deploy_yamls (see INDEX.md)
Read: artifacts/nonkyc/20260713-040416/files/NONKYC_recycle_v11_copy_paste_ladders.md

In [10]:
# ── Cell 10: VERIFY THE BOOKS for the shortlist ───────────────────────
# v11.2: reports the full DEPTH PROFILE (+-2/5/10/25% + whole book) and the
# depth inside each market's OWN deployed ladder span. A fixed +-2% reading
# misjudges ladder-shaped books: NonKYC DASH/USDT quotes dust at the touch
# and parks real size ~2.6% out (+-2% = $2, +-5% = $29,820, book = $33,509).
short = final_df[((final_df.holdout_edge_pct > 1) &
                  (final_df.clean_edge_pos_rate >= 0.6)) |
                 (final_df.validation != 'SUSPECT')]
short_pairs = list(short.base.head(12))
print('verifying books for:', short_pairs)
lads = {pk: evals[pk]['deployed'] for pk in short_pairs if pk in evals}
book_df = lr.verify_books(uni, short_pairs, CFG, samples=5, pause=4.0, ladders=lads)
display(book_df)
book_df.to_csv(f'{PREFIX}_book_verification.csv', index=False)
print('READ THE PROFILE, not one band:')
print('  depth_2pct tiny but depth_5pct large -> dust quoted at the touch, real size')
print('     parked further out. NOT a thin market -- depth_ladder_band is the truth.')
print('  depth_ladder_band = liquidity inside YOUR rungs (what can actually fill them).')
print('  flaky=True -> book swinging >5x across samples; trust no single reading.')
print('  thin_med=True with steady samples -> genuinely thin: size down or skip.')

verifying books for: ['DASH/USDT', 'BELLS/USDT', 'BELLS/BTC', 'FET/USDT', 'BC2/USDT', 'NKYC/USDT', 'XLM/USDT', 'DYDX/USDT', 'XMR/USDT', 'XMR/USDC', 'BDX/BTC', 'BC2/BTC']
  book check DASH/USDT: {'market': 'DASH/USDT', 'samples_ok': 5, 'spread_pct': 0.8417, 'book_total_usd': 33535.0, 'n_bids': 67.0, 'n_asks': 78.0, 'depth_2pct': 2.0, 'depth_5pct': 30043.0, 'depth_10pct': 30057.0, 'depth_25pct': 30204.0, 'flaky': False, 'depth_ladder_band': 30066.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check BELLS/USDT: {'market': 'BELLS/USDT', 'samples_ok': 5, 'spread_pct': 1.0127, 'book_total_usd': 12626.0, 'n_bids': 72.0, 'n_asks': 100.0, 'depth_2pct': 311.0, 'depth_5pct': 548.0, 'depth_10pct': 1227.0, 'depth_25pct': 3062.0, 'flaky': False, 'depth_ladder_band': 1375.0, 'thin_med': False, 'size_suggestion': 688.0}
  book check BELLS/BTC: {'market': 'BELLS/BTC', 'samples_ok': 5, 'spread_pct': 1.0695, 'book_total_usd': 7076.0, 'n_bids': 43.0, 'n_asks': 58.0, 'depth_2pct': 3.0, 'depth_5pct': 55.0, 'depth_10pct': 63.0, 'depth_25pct': 80.0, 'flaky': False, 'depth_ladder_band': 12.0, 'thin_med': True, 'size_suggestion': 6.0}
  book check FET/USDT: {'market': 'FET/USDT', 'samples_ok': 5, 'spread_pct': 0.2524, 'book_total_usd': 48232.0, 'n_bids': 59.0, 'n_asks': 40.0, 'depth_2pct': 26260.0, 'depth_5pct': 48070.0, 'depth_10pct': 48095.0, 'depth_25pct': 48206.0, 'flaky': False, 'depth_ladder_band': 48206.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check BC2/USDT: {'market': 'BC2/USDT', 'samples_ok': 5, 'spread_pct': 1.1885, 'book_total_usd': 8654.0, 'n_bids': 98.0, 'n_asks': 100.0, 'depth_2pct': 676.0, 'depth_5pct': 1744.0, 'depth_10pct': 1934.0, 'depth_25pct': 3304.0, 'flaky': False, 'depth_ladder_band': 1914.0, 'thin_med': False, 'size_suggestion': 957.0}
  book check NKYC/USDT: {'market': 'NKYC/USDT', 'samples_ok': 5, 'spread_pct': 0.1355, 'book_total_usd': 5016.0, 'n_bids': 100.0, 'n_asks': 100.0, 'depth_2pct': 2336.0, 'depth_5pct': 2441.0, 'depth_10pct': 2507.0, 'depth_25pct': 2552.0, 'flaky': False, 'depth_ladder_band': 2552.0, 'thin_med': False, 'size_suggestion': 1276.0}
  book check XLM/USDT: {'market': 'XLM/USDT', 'samples_ok': 5, 'spread_pct': 0.8102, 'book_total_usd': 55823.0, 'n_bids': 73.0, 'n_asks': 66.0, 'depth_2pct': 38444.0, 'depth_5pct': 51332.0, 'depth_10pct': 51430.0, 'depth_25pct': 51554.0, 'flaky': False, 'depth_ladder_band': 51514.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check DYDX/USDT: {'market': 'DYDX/USDT', 'samples_ok': 5, 'spread_pct': 0.4677, 'book_total_usd': 4853975.0, 'n_bids': 41.0, 'n_asks': 44.0, 'depth_2pct': 9403.0, 'depth_5pct': 13104.0, 'depth_10pct': 15336.0, 'depth_25pct': 18067.0, 'flaky': False, 'depth_ladder_band': 18066.0, 'thin_med': False, 'size_suggestion': 9033.0}
  book check XMR/USDT: {'market': 'XMR/USDT', 'samples_ok': 5, 'spread_pct': 0.209, 'book_total_usd': 89893.0, 'n_bids': 100.0, 'n_asks': 100.0, 'depth_2pct': 58787.0, 'depth_5pct': 82030.0, 'depth_10pct': 86949.0, 'depth_25pct': 89893.0, 'flaky': False, 'depth_ladder_band': 86193.0, 'thin_med': False, 'size_suggestion': 10000.0}
  book check XMR/USDC: {'market': 'XMR/USDC', 'samples_ok': 5, 'spread_pct': 1.342, 'book_total_usd': 11780.0, 'n_bids': 45.0, 'n_asks': 41.0, 'depth_2pct': 9226.0, 'depth_5pct': 11704.0, 'depth_10pct': 11716.0, 'depth_25pct': 11762.0, 'flaky': False, 'depth_ladder_band': 11729.0, 'thin_med': False, 'size_suggestion': 5865.0}
  book check BDX/BTC: {'market': 'BDX/BTC', 'samples_ok': 5, 'spread_pct': 0.2106, 'book_total_usd': 110819.0, 'n_bids': 49.0, 'n_asks': 63.0, 'depth_2pct': 423.0, 'depth_5pct': 537.0, 'depth_10pct': 544.0, 'depth_25pct': 567.0, 'flaky': False, 'depth_ladder_band': 564.0, 'thin_med': True, 'size_suggestion': 282.0}
  book check BC2/BTC: {'market': 'BC2/BTC', 'samples_ok': 5, 'spread_pct': 1.1919, 'book_total_usd': 13967988.0, 'n_bids': 48.0, 'n_asks': 62.0, 'depth_2pct': 0.0, 'depth_5pct': 0.0, 'depth_10pct': 1.0, 'depth_25pct': 213.0, 'flaky': False, 'depth_ladder_band': 73.0, 'thin_med': True, 'size_suggestion': 36.0}

,market,samples_ok,spread_pct,book_total_usd,n_bids,n_asks,depth_2pct,depth_5pct,depth_10pct,depth_25pct,flaky,depth_ladder_band,thin_med,size_suggestion
0,DASH/USDT,5,0.8417,33535.0,67.0,78.0,2.0,30043.0,30057.0,30204.0,False,30066.0,False,10000.0
1,BELLS/USDT,5,1.0127,12626.0,72.0,100.0,311.0,548.0,1227.0,3062.0,False,1375.0,False,688.0
2,BELLS/BTC,5,1.0695,7076.0,43.0,58.0,3.0,55.0,63.0,80.0,False,12.0,True,6.0
3,FET/USDT,5,0.2524,48232.0,59.0,40.0,26260.0,48070.0,48095.0,48206.0,False,48206.0,False,10000.0
4,BC2/USDT,5,1.1885,8654.0,98.0,100.0,676.0,1744.0,1934.0,3304.0,False,1914.0,False,957.0
5,NKYC/USDT,5,0.1355,5016.0,100.0,100.0,2336.0,2441.0,2507.0,2552.0,False,2552.0,False,1276.0
6,XLM/USDT,5,0.8102,55823.0,73.0,66.0,38444.0,51332.0,51430.0,51554.0,False,51514.0,False,10000.0
7,DYDX/USDT,5,0.4677,4853975.0,41.0,44.0,9403.0,13104.0,15336.0,18067.0,False,18066.0,False,9033.0
8,XMR/USDT,5,0.2090,89893.0,100.0,100.0,58787.0,82030.0,86949.0,89893.0,False,86193.0,False,10000.0
9,XMR/USDC,5,1.3420,11780.0,45.0,41.0,9226.0,11704.0,11716.0,11762.0,False,11729.0,False,5865.0
10,BDX/BTC,5,0.2106,110819.0,49.0,63.0,423.0,537.0,544.0,567.0,False,564.0,True,282.0
11,BC2/BTC,5,1.1919,13967988.0,48.0,62.0,0.0,0.0,1.0,213.0,False,73.0,True,36.0

READ THE PROFILE, not one band:
  depth_2pct tiny but depth_5pct large -> dust quoted at the touch, real size
     parked further out. NOT a thin market -- depth_ladder_band is the truth.
  depth_ladder_band = liquidity inside YOUR rungs (what can actually fill them).
  flaky=True -> book swinging >5x across samples; trust no single reading.
  thin_med=True with steady samples -> genuinely thin: size down or skip.

In [11]:
# ── Cell 11 (optional): calibrate the fill model against LIVE fills ───
# Point each pair at ONE OR MANY controller diagnostic JSONL files -- a single
# path, a list, and/or glob patterns. Rotated/overlapping logs are safe: fills
# are merged chronologically and deduplicated on (ts, side, price, amount).
#
# How much data is meaningful (rule of thumb: count error ~ 1/sqrt(N fills)):
#   < 15 fills / <10d  -> directional hint only, do NOT tune knobs
#   30+ fills, 15d+    -> first honest sim/live ratio (one full block)
#   60+ fills, 30d+    -> tune rc_volume_cap_frac / rc_fill_penetration_pct
#                         until sim_over_live_fill_ratio ~= 0.8-1.2
# If your controllers have been logging since deployment, you may already
# have months of data -- point globs at the whole log directory.
DIAG_FILES = {
    # 'XMR/USDT': '/path/to/xmr_diag.jsonl',                       # single file
    # 'XMR/USDT': ['/logs/xmr_*.jsonl', '/old_logs/xmr_2026*.jsonl'],  # globs+lists
}

DIAG_FILES = {
    'XMR/USDT': ['./diagnostics/nonkyc/range_inventory_ladder_xmr_usdt_diagnostic*.jsonl'],  # globs+lists
    'DASH/USDT': ['./diagnostics/nonkyc/range_inventory_ladder_dash_usdt_diagnostic*.jsonl'],  # globs+lists
    'ZANO/USDT': ['./diagnostics/nonkyc/range_inventory_ladder_zano_usdt_diagnostic*.jsonl'],  # globs+lists
    'SUN/USDT': ['./diagnostics/nonkyc/range_inventory_ladder_sun_usdt_diagnostic*.jsonl']  # globs+lists
}

for pk, paths in DIAG_FILES.items():
    print(f'=== {pk} ===')
    fills = lr.collect_jsonl_fills(paths)
    print(lr.fills_sufficiency(fills))
    if fills.empty:
        first = lr.first_existing(paths)          # glob-safe (v11.1.2 fix)
        if first is None:
            print(f'no files matched: {paths} -- check the path/glob')
        else:
            print(f'no fills extracted from {first} -- schema sniff:')
            display(lr.summarize_diagnostic_jsonl(first))
        continue
    print(fills.groupby('source_file').size().to_string())
    ladder = next((lr.controller_to_ladder(p, CFG) for p in yamls
                   if lr._pair_key(p['trading_pair']) == pk), None)
    h = hist_report.get(pk, hist_h.get(pk))
    if ladder is not None and h is not None:
        pdec = uni.get('pdec', {}).get(pk)
        book_half = lr.market_book_half_spread_pct(uni, pk, CFG)
        cfg_m, _ = lr.quote_scaled_cfg(uni, pk, CFG)
        cmp_ = lr.compare_live_vs_sim_v11(fills, h['bars'], ladder, cfg_m,
                                          pdec=pdec, book_half=book_half)
        for k, v in cmp_.items():
            print(f'  {k:28s} {v}')
    else:
        print('  (no matching controller YAML or history for the sim side)')

# refresh the health table with live-fill recency, now that fills are loaded
if DIAG_FILES and yaml_reports:
    fills_map = {pk: lr.collect_jsonl_fills(paths) for pk, paths in DIAG_FILES.items()}
    health = lr.live_strategy_health(yaml_df, yaml_reports, CFG, fills_by_pair=fills_map)
    lr.print_health_banners(health)
    display(health)
    health.to_csv(f'{PREFIX}_live_health.csv', index=False)

=== XMR/USDT ===
5 fills over 0.4d (~181/15d, +-45% count error) -> TOO THIN: directional hint only, do not tune knobs on this
source_file
./diagnostics/nonkyc/range_inventory_ladder_xmr_usdt_diagnostic_20260712-0816-20260712-081634.jsonl    5
  window_days                  0.4
  live_buy_fills               2
  live_sell_fills              3
  live_fills_per_day           12.1
  sim_buy_fills                3
  sim_sell_fills               6
  sim_fills_per_day            21.78
  sim_pnl_pct                  0.422
  sim_edge_pct                 -0.052
  vol_capped_fills             0
  fill_model                   v11
  fills_sufficiency            5 fills over 0.4d (~181/15d, +-45% count error) -> TOO THIN: directional hint only, do not tune knobs on this
  sim_over_live_fill_ratio     1.8
=== DASH/USDT ===
4 fills over 0.1d (~804/15d, +-50% count error) -> TOO THIN: directional hint only, do not tune knobs on this
source_file
./diagnostics/nonkyc/range_inventory_ladder_dash_usdt_diagnostic_20260712-0816-20260712-081634.jsonl    4
  window_days                  0.1
  live_buy_fills               0
  live_sell_fills              4
  live_fills_per_day           53.59
  sim_buy_fills                0
  sim_sell_fills               1
  sim_fills_per_day            13.4
  sim_pnl_pct                  0.272
  sim_edge_pct                 -0.072
  vol_capped_fills             0
  fill_model                   v11
  fills_sufficiency            4 fills over 0.1d (~804/15d, +-50% count error) -> TOO THIN: directional hint only, do not tune knobs on this
  sim_over_live_fill_ratio     0.25
=== ZANO/USDT ===
3 fill(s), window ~0.0h -> TOO THIN: a rate needs at least a few fills spread over time; keep logging
source_file
./diagnostics/nonkyc/range_inventory_ladder_zano_usdt_diagnostic_20260712-0816-20260712-081634.jsonl    3
  note                         only 3 fill(s) over 0.0h -- no meaningful rate; keep logging
  fills_sufficiency            3 fill(s), window ~0.0h -> TOO THIN: a rate needs at least a few fills spread over time; keep logging
=== SUN/USDT ===
1 fill(s), window ~0.0h -> TOO THIN: a rate needs at least a few fills spread over time; keep logging
source_file
./diagnostics/nonkyc/range_inventory_ladder_sun_usdt_diagnostic_20260712-0816-20260712-081634.jsonl    1
  note                         only 1 fill(s) over 0.0h -- no meaningful rate; keep logging
  fills_sufficiency            1 fill(s), window ~0.0h -> TOO THIN: a rate needs at least a few fills spread over time; keep logging

,controller,pair,status,recent_blocks,recent_days,recent_pnl_pct,recent_hold_pct,recent_edge_pct,recent_trades,recent_two_sided_blocks,last_block_pnl_pct,full_pnl_pct,full_edge_pct,days_since_live_fill
0,range_inventory_ladder_dash_V1,DASH/USDT,HEALTHY,3,45.0,6.25,-2.95,9.20,65,3,1.410,11.262,23.402,0.4
1,range_inventory_ladder_sun_V1,SUN/USDT,HEALTHY,3,45.0,7.47,-8.59,16.05,32,1,7.332,5.561,15.627,0.2
2,range_inventory_ladder_zano_V1,ZANO/USDT,HEALTHY,3,45.0,16.44,-1.57,18.00,38,3,6.872,40.167,49.423,0.5
3,range_inventory_ladder_xmr_V1,XMR/USDT,HEALTHY,3,45.0,18.92,-6.67,25.59,240,3,6.887,-9.067,34.457,0.4

## Reading the results (v11 evidence hierarchy)

Work down this list; each level is weaker evidence than the one above it.

1. **`holdout_edge_pct`** (Cell 9 holdout view / `*_holdout_summary.csv`) — the fitted,
   train-anchored ladder on 15 days it never saw. This is the only fully out-of-sample
   number for the geometry you deploy. Positive and two-sided ⇒ real signal; dormant
   (`holdout_active=False`) ⇒ no evidence either way, and the gate says so.
2. **Clean blocks** (`clean_edge_pos_rate`, `clean_worst_block_edge`) — the frozen report's
   blocks that do *not* overlap the fit window. The headline `edge_pct`/`edge_pos_rate`
   still include the fit window (kept for v10 comparability) — prefer the clean ones.
3. **Your live YAMLs** (Cell 6) — ground truth for the fill model itself. If the sim's
   trades/block is far from your JSONL fills, recalibrate in Cell 11 before trusting anything.
4. **Rolling WF** — validates the *fitting process*, not the deployed ladder. A wf_pass with
   a bad holdout means the process is fine but this particular fit is a bad draw: refit later.
5. **`harvest_best_pct_mo`** — model-free ceiling on what any grid can extract at cost.
   If it's near zero, no amount of ladder tuning will make the pair work.

`vol_capped_fills` > 0 tells you the book, not the price path, limited the sim — size DOWN
(`max_fund_value_quote`) rather than dismissing the pair. `fit_score_gap` large (≫ typical)
suggests the winner is a lucky draw among 240 candidates — prefer pairs where holdout,
clean blocks *and* WF agree.

**NonKYC note:** native 5m candles omit trade-less periods; the engine grid-snaps them (`candle_gap_fill` in the summary shows how much was missing). A high gap-fill fraction plus `vol_capped_fills` > 0 = a genuinely thin market: believe the capped numbers, not your eyes on the chart.

**Deployment discipline:** deploy only `CONFIRMED`, at the suggested `max_fund_value_quote`
or less, and treat the FIRST live 15-day block as the final gate — if it underperforms the
holdout badly, stop and recalibrate (Cell 11) instead of re-fitting harder.